act_code: '162419'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 27 декабря 2021 года № 9/12
title:
  rus: Об утверждении бюджета Ленинского сельского округа Тимирязевского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Тимирязев ауданы Ленин ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '165012000002'
version_date:
  kaz: 2022-06-30
  rus: 2022-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/162419/kaz/30.06.2022
  rus: https://zan.gov.kz/client/#!/doc/162419/rus/30.06.2022
caused_by:
  code: '169442'
  requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 30 июня 2022 года № 13/30
  title:
    rus: О внесении изменений и дополнения в решение Тимирязевского районного маслихата от 27 декабря 2021 года № 9/12 «Об утверждении бюджета Ленинского сельского округа Тимирязевского района на 2022-2024 годы»
    kaz: Тимирязев аудандық мәслихатының 2021 жылғы 27 желтоқсандағы № 9/12 «2022-2024 жылдарға арналған Тимирязев ауданы Ленин ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169442/rus
