act_code: '163721'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 30 декабря 2021 года № 14/149
title:
  rus: Об утверждении бюджета Явленского сельского округа Есильского района Северо-Казахстанской области на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Солтүстік Қазақстан облысы Есіл ауданы Явленка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '165006000002'
version_date:
  kaz: 2022-05-30
  rus: 2022-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/163721/kaz/30.05.2022
  rus: https://zan.gov.kz/client/#!/doc/163721/rus/30.05.2022
caused_by:
  code: '168468'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 30 мая 2022 года № 19/233
  title:
    rus: О внесении изменений в решение маслихата Есильского района Северо-Казахстанской области от 30 декабря 2021 года № 14/149 «Об утверждении бюджета Явленского сельского округа Есильского района Северо-Казахстанской области на 2022-2024 годы»
    kaz: «2022-2024 жылдарға арналған Солтүстік Қазақстан облысы Есіл ауданы Явленка ауылдық округінің бюджетін бекіту туралы» Солтүстік Қазақстан облысы Есіл ауданы мәслихатыының 2021 жылғы 30 желтоқсандағы № 14/149 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/168468/rus
