act_code: '150042'
requisite: Решение акима Якорьского сельского округа Кызылжарского района Северо-Казахстанской области от 15 декабря 2020 года № 63. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 декабря 2020 года № 6813
title:
  rus: О присвоении наименований безымянным улицам села Вишневка Якорьского сельского округа Кызылжарского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданы Якорь ауылдық округінің Вишневка ауылындағы атауы жоқ көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '165008020002'
version_date:
  kaz: 2020-12-15
  rus: 2020-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/150042/kaz/15.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150042/rus/15.12.2020
