act_code: '70088'
requisite: Решение маслихата Уалихановского района Северо-Казахстанской области от 20 декабря 2012 года № 2-9с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 января 2013 года № 2051. Утратило силу (письмо маслихата Уалихановского района Северо-Казахстанской области от 04.08.2014 № 14.2.3-3/167)
title:
  rus: О районном бюджете на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '165013000002'
version_date:
  rus: 2013-07-09
source:
  rus: https://zan.gov.kz/client/#!/doc/70088/rus/09.07.2013
caused_by:
  code: '73617'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 9 июля 2013 года № 2-13с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 июля 2013 года № 2329.  Утратило силу (письмо маслихата Уалихановского района Северо-Казахстанской области от 04.08.2014 № 14.2.3-3/167)
  title:
    rus: О внесении изменений и дополнения в решение Уалихановского районного маслихата от 20 декабря 2012 года № 2-9с "О районном бюджете на 2013-2015 годы"
    kaz: '"2013-2015 жылдарға арналған аудандық бюджет туралы" Уәлиханов аудандық мәслихатының 2012 жылғы 20 желтоқсандағы № 2-9с шешіміне өзгерістер мен толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/73617/rus
