act_code: '206438'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2024 года № 23-8. Утратило силу решением маслихата Аккайынского района Северо-Казахстанской области от 8 мая 2025 года № 26-9 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета Полтавского сельского округа Аккайынского района на 2025 -2027 годы
  kaz: 2025-2027 жылдарға арналған Аққайың ауданының Полтавка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '165005000002'
version_date:
  kaz: 2025-03-27
  rus: 2025-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206438/kaz/27.03.2025
  rus: https://zan.gov.kz/client/#!/doc/206438/rus/27.03.2025
caused_by:
  code: '208583'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 27 марта 2025 года № 24-18. Утратило силу решением маслихата Аккайынского района Северо-Казахстанской области от 8 мая 2025 года № 26-9 (вводится в действие с 1 января 2025 года)
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2024 года № 23-8 «Об утверждении бюджета Полтавского сельского округа Аккайынского района на 2025-2027 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2024 жылғы 30 желтоқсандағы № 23-8 «2025-2027 жылдарға арналған Аққайың ауданының Полтавка ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208583/rus
