act_code: '155106'
requisite: Решение акима Семипольского сельского округа района Шал акына Северо-Казахстанской области от 21 апреля 2021 года № 4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 апреля 2021 года № 7308
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-21
approved_by:
- '165010009002'
version_date:
  kaz: 2021-04-21
  rus: 2021-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/155106/kaz/21.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155106/rus/21.04.2021
