act_code: '148862'
requisite: Решение акима Асановского сельского округа Кызылжарского района Северо-Казахстанской области от 23 ноября 2020 года № 32. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 ноября 2020 года № 6699
title:
  rus: О присвоении наименования безымянной улице села Михайловка Асановского сельского округа Кызылжарского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданы Асаново ауылдық округінің Михайловка ауылындағы атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-11-23
approved_by:
- '165008002002'
version_date:
  kaz: 2020-11-23
  rus: 2020-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/148862/kaz/23.11.2020
  rus: https://zan.gov.kz/client/#!/doc/148862/rus/23.11.2020
