act_code: '210131'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 8 мая 2025 года № 8-26-9
title:
  rus: Об утверждении бюджета Камсактинского сельского округа Айыртауского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Айыртау ауданы Қамсақты ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-08
approved_by:
- '165003000002'
version_date:
  kaz: 2025-09-12
  rus: 2025-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/210131/kaz/12.09.2025
  rus: https://zan.gov.kz/client/#!/doc/210131/rus/12.09.2025
caused_by:
  code: '214339'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 12 сентября 2025 года № 8-31-7
  title:
    rus: О внесении изменений в решение Айыртауского районного маслихата от 08 мая 2025 года № 8-26-9 «Об утверждении бюджета Камсактинского сельского округа Айыртауского района на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған Айыртау ауданы Қамсақты ауылдық округінің бюджетін бекіту туралы» Айыртау аудандық мәслихатының 2025 жылғы 08 мамырдағы № 8-26-9 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214339/rus
