act_code: '61796'
requisite: Солтүстік Қазақстан облысы Уәлиханов ауданы Қулыкөл ауылдық округі әкімінің 2011 жылғы 11 қарашадағы № 10-III шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2011 жылғы 7 желтоқсанда № 13-13-148 тіркелді
title:
  rus: Солтүстік Қазақстан облысы Уәлиханов ауданы Қулыкөл ауылының көшесінің атауын өзгерту туралы
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Қулыкөл ауылының көшесінің атауын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-11
approved_by:
- '165013010002'
version_date:
  kaz: 2011-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/61796/kaz/11.11.2011
