act_code: '155301'
requisite: Решение акима Украинского сельского округа Айыртауского района Северо-Казахстанской области от 22 апреля 2021 года № 12. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 апреля 2021 года № 7332
title:
  rus: О переименовании улицы Ленина в улицу Абай в селе Кирилловка Айыртауского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданының Кирилловка ауылындағы Ленин көшесін Абай көшесі деп қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-22
approved_by:
- '165003015002'
version_date:
  kaz: 2021-04-22
  rus: 2021-04-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/155301/kaz/22.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155301/rus/22.04.2021
