act_code: '4042'
requisite: Решение акима Северо-Казахстанской области от 22 июня 1998 года № 152. Зарегистрировано Управлением юстиции Северо-Казахстанской области 15 июля 1998 года за № 31. Утратило силу решением акима Северо-Казахстанской области от 24 августа 2005 года № 24
title:
  rus: Об Уставе регионального фонда по поддержке малообеспеченных граждан
  kaz: Аз қамтамасыз етілген азаматтарды қолдау жөніндегі аймақтық қордың Жарғысы жөнінде
form: РЕШ
type_codes:
- РЕШ
- УСТ
approved_on: 1998-06-21
approved_by:
- '165000000003'
version_date:
  kaz: 1998-06-21
  rus: 1998-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/4042/kaz/21.06.1998
  rus: https://zan.gov.kz/client/#!/doc/4042/rus/21.06.1998
