act_code: '86351'
requisite: Решение Северо-Казахстанского областного маслихата от 26 декабря 2014 года № 31/3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 января 2015 года № 3084
title:
  rus: О ставках платы за пользование водными ресурсами поверхностных источников на 2015 год
  kaz: 2015 жылға арналған жер үсті көздерінің су ресурстарын пайдаланғаны үшін төлемақы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-26
approved_by:
- '165000000002'
version_date:
  kaz: 2014-12-26
  rus: 2014-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/86351/kaz/26.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86351/rus/26.12.2014
