act_code: '87591'
requisite: Решение акима города Петропавловска Северо-Казахстанской области от 27 февраля 2015 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 3 марта 2015 года № 3133. Утратило силу решением акима города Петропавловска Северо-Казахстанской области от 21 октября 2015 года № 35
title:
  rus: Об образовании избирательных участков на территории города Петропавловска
  kaz: Петропавл қаласының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-27
approved_by:
- '165002000001'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/87591/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/87591/rus/27.03.2015
caused_by:
  code: '88122'
  requisite: Решение акима города Петропавловска Северо-Казахстанской области от 27 марта 2015 года № 7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 марта 2015 года № 3185. Утратило силу решением акима города Петропавловска Северо-Казахстанской области от 21 октября 2015 года № 35
  title:
    rus: О внесении изменений в решение акима города Петропавловска от 27 февраля 2015 года № 5 «Об образовании избирательных участков на территории города Петропавловска»
    kaz: «Петропавл қаласының аумағында сайлау учаскелерін құру туралы» Петропавл қаласы әкімінің 2015 жылғы 27 ақпандағы № 5 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88122/rus
