act_code: '87591'
requisite: Решение акима города Петропавловска Северо-Казахстанской области от 27 февраля 2015 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 3 марта 2015 года № 3133. Утратило силу решением акима города Петропавловска Северо-Казахстанской области от 21 октября 2015 года № 35
title:
  rus: Об образовании избирательных участков на территории города Петропавловска
  kaz: Петропавл қаласының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-02-27
approved_by:
- '165002000001'
version_date:
  kaz: 2015-02-27
  rus: 2015-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/87591/kaz/27.02.2015
  rus: https://zan.gov.kz/client/#!/doc/87591/rus/27.02.2015
