act_code: '160840'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 12 ноября 2021 года № 13-11 с. Зарегистрировано в Министерстве юстиции Республики Казахстан 29 ноября 2021 года № 25449
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Уалихановском районе
  kaz: Уәлиханов ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-11-12
approved_by:
- '165013000002'
version_date:
  kaz: 2021-11-12
  rus: 2021-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/160840/kaz/12.11.2021
  rus: https://zan.gov.kz/client/#!/doc/160840/rus/12.11.2021
