act_code: '180232'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 4 апреля 2023 года № 8-2 с
title:
  rus: Об утверждении Положения коммунального государственного учреждения «Аппарат Уалихановского районного маслихата»
  kaz: «Уәлиханов аудандық мәслихатының аппараты» коммуналдық мемлекеттік мекемесінің ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2023-04-04
approved_by:
- '165013000002'
version_date:
  kaz: 2023-04-04
  rus: 2023-04-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/180232/kaz/04.04.2023
  rus: https://zan.gov.kz/client/#!/doc/180232/rus/04.04.2023
