act_code: '150390'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 22 декабря 2020 года № 59/3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 декабря 2020 года № 6846
title:
  rus: О предоставлении в 2020 году подъемного пособия и социальной поддержки для приобретения или строительства жилья специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, государственным служащим аппаратов акимов сельских округов, прибывшим для работы и проживания в сельские населенные пункты Кызылжарского района Северо-Казахстанской области
  kaz: 2020 жылы Солтүстік Қазақстан облысы Қызылжар ауданының ауылдық елді мекендерге жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға, ауылдық округтер әкімдері аппараттарының мемлекеттік қызметшілеріне көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-22
approved_by:
- '165008000002'
version_date:
  kaz: 2020-12-22
  rus: 2020-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/150390/kaz/22.12.2020
  rus: https://zan.gov.kz/client/#!/doc/150390/rus/22.12.2020
