act_code: '200246'
requisite: Решение акима Дзержинского сельского округа Тимирязевского района Северо-Казахстанской области от 27 августа 2024 года № 3
title:
  rus: О предоставлении права ограниченного целевого пользования (публичный сервитут) на земельный участок
  kaz: Жер учаскесіне шектеулі нысаналы пайдалану (қауымдық сервитут) құқығын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-27
approved_by:
- '165012005002'
version_date:
  kaz: 2024-08-27
  rus: 2024-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/200246/kaz/27.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200246/rus/27.08.2024
