act_code: '210215'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 8 мая 2025 года № 26-10
title:
  rus: Об утверждении бюджета Смирновского сельского округа Аккайынского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Аққайың ауданының Смирново ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-08
approved_by:
- '165005000002'
version_date:
  kaz: 2025-06-03
  rus: 2025-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/210215/kaz/03.06.2025
  rus: https://zan.gov.kz/client/#!/doc/210215/rus/03.06.2025
caused_by:
  code: '211189'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 3 июня 2025 года № 27-21
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 8 мая 2025 года № 26-10 «Об утверждении бюджета Смирновского сельского округа Аккайынского района на 2025-2027 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2025 жылғы 8 мамырдағы № 26-10 «2025-2027 жылдарға арналған Аққайың ауданының Смирново ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211189/rus
