act_code: '45327'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 13 апреля 2009 года № 16/105. Зарегистрировано Управлением юстиции Есильского района Северо-Казахстанской области 16 апреля 2009 года № 13-6-114. Утратило силу - решением маслихата Есильского района Северо-Казахстанской области от 20 декабря 2012 года № 13/68
title:
  rus: О стоимости разовых талонов и ставкам фиксированного налога по отдельным видам деятельности
  kaz: Жекелеген қызмет түрлері бойынша біржолғы талондардың құны және белгіленген салық мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-13
approved_by:
- '165006000002'
version_date:
  kaz: 2009-04-13
  rus: 2009-04-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/45327/kaz/13.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45327/rus/13.04.2009
