act_code: '18552'
requisite: Решение Есильского районного маслихата Северо-Казахстанской области от 30 декабря 2003 года № 3с-3-21. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 6 февраля 2004 года № 1137. Утратило силу решением Есильского районного маслихата Северо-Казахстанской области от 26 октября 2006 года № 208
title:
  rus: О регламенте Есильского районного маслихата
  kaz: Есіл аудандық мәслихатының регламенті туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2003-12-30
approved_by:
- '165006000002'
version_date:
  kaz: 2003-12-30
  rus: 2003-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/18552/kaz/30.12.2003
  rus: https://zan.gov.kz/client/#!/doc/18552/rus/30.12.2003
