act_code: '177900'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 29 декабря 2022 года № 6-26 c
title:
  rus: Об утверждении бюджета Кишкенекольского сельского округа Уалихановского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Уәлиханов ауданы Кішкенекөл ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '165013000002'
version_date:
  kaz: 2023-09-05
  rus: 2023-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/177900/kaz/05.09.2023
  rus: https://zan.gov.kz/client/#!/doc/177900/rus/05.09.2023
caused_by:
  code: '186105'
  requisite: Решение маслихата Уалихановского района Северо-Казахстанской области от 05 сентября 2023 года № 6-7 с
  title:
    rus: О внесении изменений и дополнений в решение Уалихановского районного маслихата от 29 декабря 2022 года № 6-26 с «Об утверждении бюджета Кишкенекольского сельского округа Уалихановского района на 2023-2025 годы»
    kaz: Уәлиханов аудандық мәслихатының 2022 жылғы 29 желтоқсандағы № 6-26 с «2023-2025 жылдарға арналған Уәлиханов ауданы Кішкенекөл ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186105/rus
