act_code: '166325'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2021 года № 10-11
title:
  rus: Об утверждении бюджета сельского округа Бәйтерек района Магжана Жумабаева на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Мағжан Жұмабаев ауданы Бәйтерек ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '165015000002'
version_date:
  kaz: 2022-03-15
  rus: 2022-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/166325/kaz/15.03.2022
  rus: https://zan.gov.kz/client/#!/doc/166325/rus/15.03.2022
caused_by:
  code: '165958'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 15 марта 2022 года № 12-11
  title:
    rus: О внесении изменений и дополнений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2021 года № 10-11 «Об утверждении бюджета сельского округа Бәйтерек района Магжана Жумабаева на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2021 жылғы 30 желтоқсандағы № 10-11 «2022-2024 жылдарға арналған Мағжан Жұмабаев ауданы Бәйтерек ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165958/rus
