act_code: '134682'
requisite: Решение акима Кишкенекольского сельского округа Уалихановского района Северо-Казахстанской области от 12 сентября 2019 года № 76. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 сентября 2019 года № 5564
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-09-12
approved_by:
- '165013001002'
version_date:
  kaz: 2019-09-12
  rus: 2019-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/134682/kaz/12.09.2019
  rus: https://zan.gov.kz/client/#!/doc/134682/rus/12.09.2019
