act_code: '192593'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 28 декабря 2023 года № 5-13 с
title:
  rus: Об утверждении бюджета Бидайыкского сельского округа Уалихановского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Уәлиханов ауданы Бидайық ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '165013000002'
version_date:
  kaz: 2023-12-28
  rus: 2023-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/192593/kaz/28.12.2023
  rus: https://zan.gov.kz/client/#!/doc/192593/rus/28.12.2023
