act_code: '53910'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 28 июня 2010 года № 30/178. Зарегистрировано Управлением юстиции Есильского района Северо-Казахстанской области 9 августа 2010 года № 13-6-151. Утратило силу - решением маслихата Есильского района Северо-Казахстанской области от 7 июня 2012 года № 6/29
title:
  rus: О Правилах благоустройства территорий, содержание зеленых насаждений и объектов инфраструктуры в населенных пунктах Есильского района
  kaz: Есіл ауданының елді мекендеріндегі аумақтарды абаттандыру, жасыл көшеттерді және инфрақұрылым нысаналарын ұстау Ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-06-28
approved_by:
- '165006000002'
version_date:
  kaz: 2010-06-30
  rus: 2010-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/53910/kaz/30.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53910/rus/30.06.2010
