act_code: '67522'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2012 жылғы 8 тамыздағы № 5-5с шешімі. Солтүстік Қазақстан облысының Әділет департаментінде 2012 жылғы 7 қыркүйекте № 1825 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2013 жылғы 14 ақпандағы № 02-03-03/40 хаты)
title:
  rus: 2012 жылы Уәлиханов ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдауды ұсыну туралы
  kaz: 2012 жылы Уәлиханов ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-08-08
approved_by:
- '165013000002'
version_date:
  kaz: 2012-08-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/67522/kaz/08.08.2012
