act_code: '85736'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 19 декабря 2014 года № 35/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 8 января 2015 года № 3045
title:
  rus: О Кызылжарском районном бюджете на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған Қызылжар аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-19
approved_by:
- '165008000002'
version_date:
  kaz: 2014-12-19
  rus: 2014-12-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/85736/kaz/19.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85736/rus/19.12.2014
