act_code: '137686'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 25 декабря 2019 года № 6-38-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 декабря 2019 года № 5774
title:
  rus: Об утверждении Регламента собрания местного сообщества сельских округов Айыртауского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданы ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2019-12-25
approved_by:
- '165003000002'
version_date:
  kaz: 2019-12-25
  rus: 2019-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/137686/kaz/25.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137686/rus/25.12.2019
