act_code: '120610'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 30 марта 2018 года № 23/2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 апреля 2018 года № 4657. Утратило силу решением маслихата района Шал акына Северо-Казахстанской области от 17 марта 2020 года № 44/7 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по району Шал акына
  kaz: Шал ақын ауданы бойынша ауылшаруашылығы мақсатындағы пайдаланылмайтын жерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-30
approved_by:
- '165010000002'
version_date:
  kaz: 2018-03-30
  rus: 2018-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/120610/kaz/30.03.2018
  rus: https://zan.gov.kz/client/#!/doc/120610/rus/30.03.2018
