act_code: '181004'
requisite: Решение акима города Петропавловска Северо-Казахстанской области от 10 мая 2023 года № 15. Утратило силу решением акима города Петропавловска Северо-Казахстанской области от 24 октября 2024 года № 33 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба в городе Петропавловск
  kaz: Петропавл қаласында жергілікті ауқымдағы техногендік сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-10
approved_by:
- '165002000003'
version_date:
  kaz: 2023-05-10
  rus: 2023-05-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/181004/kaz/10.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181004/rus/10.05.2023
