act_code: '48673'
requisite: Решение акима города Петропавловска Северо-Казахстанской области от 11 ноября 2009 года № 17. Зарегистрировано Управлением юстиции города Петропавловска Северо-Казахстанской области 18 ноября 2009 года № 13-1-163. Утратило силу - решением акима города Петропавловска Северо-Казахстанской области от 31 мая 2012 года № 12
title:
  rus: О предоставлении социальной помощи на зубопротезирование отдельным категориям граждан города Петропавловска на 2009 год
  kaz: Петропавл қаласы азаматтарының жекелеген санаттарына тістерін протездеуге 2009 жылы әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-11
approved_by:
- '165002000003'
version_date:
  kaz: 2009-11-11
  rus: 2009-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/48673/kaz/11.11.2009
  rus: https://zan.gov.kz/client/#!/doc/48673/rus/11.11.2009
