act_code: '137785'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 23 декабря 2019 года № 1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области от 31 декабря 2019 года № 5778
title:
  rus: Об утверждении бюджета города Петропавловска на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Петропавл қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '165002000002'
version_date:
  kaz: 2020-03-19
  rus: 2020-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/137785/kaz/19.03.2020
  rus: https://zan.gov.kz/client/#!/doc/137785/rus/19.03.2020
caused_by:
  code: '140556'
  requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 19 марта 2020 года № 1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области от 20 марта 2020 года № 6110
  title:
    rus: О внесении изменений и дополнений в решение Петропавловского городского маслихата от 23 декабря 2019 года № 1 «Об утверждении бюджета города Петропавловска на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Петропавл қаласының бюджеті бекіту туралы» Петропавл қалалық мәслихатының 2019 жылғы 23 желтоқсандағы № 1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140556/rus
