act_code: '152765'
requisite: Решение акима Амандыкского сельского округа Тайыншинского района Северо-Казахстанской области от 8 февраля 2021 года № 3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 февраля 2021 года № 7122
title:
  rus: О присвоении наименования безымянной улице
  kaz: Атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-02-08
approved_by:
- '165011004002'
version_date:
  kaz: 2021-02-08
  rus: 2021-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/152765/kaz/08.02.2021
  rus: https://zan.gov.kz/client/#!/doc/152765/rus/08.02.2021
