act_code: '142164'
requisite: Решение акима Акжарского района Северо-Казахстанской области от 23 апреля 2020 года № 8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 23 апреля 2020 года № 6259. Утратило силу решением акима Акжарского района Северо-Казахстанской области от 6 апреля 2021 года № 3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении на территории Акжарского района Северо-Казахстанской области чрезвычайной ситуации природного характера местного масштаба
  kaz: Солтүстік Қазақстан облысы Ақжар ауданының аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайлар жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-23
approved_by:
- '165004000003'
version_date:
  kaz: 2020-04-23
  rus: 2020-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/142164/kaz/23.04.2020
  rus: https://zan.gov.kz/client/#!/doc/142164/rus/23.04.2020
