act_code: '50499'
requisite: Решение акима Тимирязевского района Северо-Казахстанской области от 3 сентября 2009 года № 23. Зарегистрировано Управлением юстиции Тимирязевского района Северо-Казахстанской области 7 октября 2009 года № 13-12-94. Утратило силу - решением акима Тимирязевского района Северо-Казахстанской области от 24 февраля 2010 года № 9
title:
  rus: О предоставлении социальной помощи на зубопротезирование
  kaz: Тіс протезіне әлеуметтік көмек көрсетуін ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-09-03
approved_by:
- '165012000003'
version_date:
  kaz: 2009-09-03
  rus: 2009-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/50499/kaz/03.09.2009
  rus: https://zan.gov.kz/client/#!/doc/50499/rus/03.09.2009
