act_code: '117664'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 21 декабря 2017 года № 22-10. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2018 года № 4488
title:
  rus: О бюджете Ленинградского сельского округа Акжарского района Северо-Казахстанской области на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Солтүстік Қазақстан облысы Ақжар ауданы Ленинград ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-21
approved_by:
- '165004000002'
version_date:
  kaz: 2018-12-06
  rus: 2018-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/117664/kaz/06.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117664/rus/06.12.2018
caused_by:
  code: '126811'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 6 декабря 2018 года № 34-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 декабря 2018 года № 5064
  title:
    rus: О внесении изменения в решение Акжарского районного маслихата Северо-Казахстанской области от 21 декабря 2017 года № 22-10 «О бюджете Ленинградского сельского округа Акжарского района Северо-Казахстанской области на 2018-2020 годы»
    kaz: Солтүстік Қазақстан облысы Ақжар аудандық мәслихатының 2017 жылғы 21 желтоқсандағы № 22-10 «2018-2020 жылдарға арналған Солтүстік Қазақстан облысы Ақжар ауданы Ленинград ауылдық округінің бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/126811/rus
