act_code: '182933'
requisite: Решение акима Кладбинского сельского округа Жамбылского района Северо-Казахстанской области от 13 июня 2023 года № 15. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 июня 2023 года № 7535-15
title:
  rus: О переименовании улиц села Кладбинка Кладбинского сельского округа Жамбылского района Северо-Казахстансккой области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданы Кладбинка ауылдық округі Кладбинка ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-13
approved_by:
- '165007008002'
version_date:
  kaz: 2023-06-13
  rus: 2023-06-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/182933/kaz/13.06.2023
  rus: https://zan.gov.kz/client/#!/doc/182933/rus/13.06.2023
