act_code: '195413'
requisite: Решение акима Кызылжарского района Северо-Казахстанской области от 8 апреля 2024 года № 4
title:
  rus: Об объявлении на территории Кызылжарского района Северо-Казахстанской области чрезвычайной ситуации природного характера местного масштаба
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданы аумағында жергілікті масштабтағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-08
approved_by:
- '165008000003'
version_date:
  kaz: 2025-04-25
  rus: 2025-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/195413/kaz/25.04.2025
  rus: https://zan.gov.kz/client/#!/doc/195413/rus/25.04.2025
caused_by:
  code: '209668'
  requisite: Решение акима Кызылжарского района Северо-Казахстанской области от 25 апреля 2025 года № 7
  title:
    rus: О внесении изменения в решение акима Кызылжарского района Северо-Казахстанской области от 08 апреля 2024 года № 04 «Об объявлении на территории Кызылжарского  района Северо-Казахстанской области чрезвычайной ситуации природного характера местного масштаба»
    kaz: Солтүстік Қазақстан облысы Қызылжар ауданы әкімінің 2024 жылғы 08 сәуірдегі № 04 «Солтүстік Қазақстан облысы Қызылжар ауданы аумағында жергілікті масштабтағы табиғи сипаттағы төтенше жағдайды жариялау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209668/rus
