act_code: '195413'
requisite: Решение акима Кызылжарского района Северо-Казахстанской области от 8 апреля 2024 года № 4
title:
  rus: Об объявлении на территории Кызылжарского района Северо-Казахстанской области чрезвычайной ситуации природного характера местного масштаба
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданы аумағында жергілікті масштабтағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-08
approved_by:
- '165008000003'
version_date:
  kaz: 2024-04-08
  rus: 2024-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/195413/kaz/08.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195413/rus/08.04.2024
