act_code: '57122'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 6-25с шешімі. Солтүстік Қазақстан облысының Әділет департаментінде 2011 жылғы 25 қаңтарда № 13-13-135 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов ауданы мәслихатының 2012 жылғы 10 желтоқсандағы № 02-03-03/237 хаты)
title:
  rus: 2011-2013 жылдарға арналған аудан бюджеті туралы
  kaz: 2011-2013 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '165013000002'
version_date:
  kaz: 2011-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/57122/kaz/16.11.2011
caused_by:
  code: '61965'
  requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2011 жылғы 16 қарашадағы № 4-35с шешімі. Солтүстік Қазақстан облысының Әділет департаментінде 2011 жылғы 14 желтоқсанда № 13-13-151 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов ауданы мәслихатының 2012 жылғы 10 желтоқсандағы № 02-03-03/237 хаты)
  title:
    rus: '"2011-2013 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2010 жылғы 24 желтоқсандағы № 6-25с шешіміне өзгерістер енгізу туралы'
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2010 жылғы 24 желтоқсандағы № 6-25с шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61965/rus
