act_code: '73223'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 24 мая 2013 года № 13-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 июня 2013 года № 2299. Утратило силу решением маслихата района имени Габита Мусрепова Северо-Казахстанской области от 3 июля 2018 года № 26-4
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в районе имени Габита Мусрепова
  kaz: Ғабит Мүсірепов атындағы ауданында тұратын аз қамтамасыз етілген отбасыларына (азаматтарына) тұрғын үй көмегін көрсету Қағидасын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- ПРЧ
- РЕШ
approved_on: 2013-05-24
approved_by:
- '165014000002'
version_date:
  kaz: 2013-12-24
  rus: 2013-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/73223/kaz/24.12.2013
  rus: https://zan.gov.kz/client/#!/doc/73223/rus/24.12.2013
caused_by:
  code: '77034'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 24 декабря 2013 года № 22-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 января 2014 года № 2508. Утратило силу решением маслихата района имени Габита Мусрепова Северо-Казахстанской области от 3 июля 2018 года № 26-4
  title:
    rus: О внесении изменений в решение маслихата района имени Габита Мусрепова от 24 мая 2013 года № 13-2 "Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим в районе имени Габита Мусрепова"
    kaz: Ғабит Мүсірепов атындағы аудан мәслихатының 2013 жылғы 24 мамырдағы № 13-2 "Ғабит Мүсірепов атындағы ауданында тұратын аз қамтамасыз етілген отбасыларына (азаматтарына) тұрғын үй көмегін көрсету Қағидасын бекіту туралы" шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/77034/rus
