act_code: '1057'
requisite: Решение акима Северо-Казахстанской области от 8 июня 1998 года № 138. Зарегистрировано Управлением юстиции Северо-Казахстанской области 1 июля 1998 года за № 27. Утратило силу решением акима Северо-Казахстанской области от 20 декабря 2017 года № 41
title:
  rus: Об открытии СДЮШОР по велосипедному спорту областного управления туризма и спорта
  kaz: Облыстық туризм және спорт басқармасының велосипед спорты жөніндегі балалар мен жасөспірімдердің мамандандырылған олимпиялық резерв мектебін /БЖМОРМ/ ашу жөнінде
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-06-07
approved_by:
- '165000000003'
version_date:
  kaz: 1998-06-07
  rus: 1998-06-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/1057/kaz/07.06.1998
  rus: https://zan.gov.kz/client/#!/doc/1057/rus/07.06.1998
