act_code: '214824'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 25 сентября 2025 года № 25/5
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов для населения, юридических лиц на сбор, транспортировку, твердых бытовых отходов по Кызылжарскому району
  kaz: Қызылжар ауданында тұрмыстық қалдықтарды қалыптастыру және жинақтау нормативтерін, тұрмыстық қатты қалдықтарды жинау, тасымалдау бойынша халыққа, заңды тұлғаларға тарифтерді бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2025-09-25
approved_by:
- '165008000002'
version_date:
  kaz: 2025-09-25
  rus: 2025-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/214824/kaz/25.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214824/rus/25.09.2025
