act_code: '97872'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 23 декабря 2015 года № 3-36с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 января 2016 года № 3546
title:
  rus: О районном бюджете Уалихановского района на 2016 -2018 годы
  kaz: 2016-2018 жылдарға арналған Уәлиханов ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '165013000002'
version_date:
  kaz: 2016-03-24
  rus: 2016-03-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/97872/kaz/24.03.2016
  rus: https://zan.gov.kz/client/#!/doc/97872/rus/24.03.2016
caused_by:
  code: '101246'
  requisite: Решение маслихата Уалихановского района Северо-Казахстанской области от 24 марта 2016 года № 2-40с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 7 апреля 2016 года № 3690
  title:
    rus: О внесении изменений и дополнений в решение Уалихановского районного маслихата от 23 декабря 2015 года № 3-36 с «О районном бюджете Уалихановского района на 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған Уәлиханов ауданының бюджеті туралы» Уәлиханов аудандық мәслихатының 2015 жылғы 23 желтоқсандағы № 3-36 с шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/101246/rus
