act_code: '50084'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 25 декабря 2009 года № 18-1. Зарегистрировано Управлением юстиции Аккайынского района Северо-Казахстанской области 20 января 2010 года № 13-2-112. Утратило силу (письмо Департамента юстиции Северо-Казахстанской области от 2 апреля 2013 года № 04-07/1933)
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '165005000002'
version_date:
  kaz: 2010-03-31
  rus: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/50084/kaz/31.03.2010
  rus: https://zan.gov.kz/client/#!/doc/50084/rus/31.03.2010
caused_by:
  code: '52031'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 31 марта 2010 года № 20-1. Зарегистрировано Управлением юстиции Аккайынского района Северо-Казахстанской области 23 апреля 2010 года № 13-2-114. Утратило силу (письмо Департамента юстиции Северо-Казахстанской области от 2 апреля 2013 года № 04-07/1933)
  title:
    rus: О внесении изменений и дополнений в решение сессии Аккайынского районного маслихата от 25 декабря 2009 года № 18-1 "О районном бюджете на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Аққайың аудандық мәслихат сессиясының 2009 жылғы 25 желтоқсандағы № 18-1 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/52031/rus
