act_code: '56824'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 22 декабря 2010 года № 36/213. Зарегистрировано Управлением юстиции Есильского района Северо-Казахстанской области 20 января 2011 года № 13-6-158. Утратило силу - решением маслихата Есильского района Северо-Казахстанской области от 22 декабря 2011 года № 51/277
title:
  rus: О льготном проезде на сельском общественном транспорте (кроме такси) учащихся общеобразовательных учебных заведений
  kaz: Жалпы білім беретін оқу орындары оқушыларының селолық қоғамдық көлікте (таксиден басқа) жеңілдікпен жүрулері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '165006000002'
version_date:
  kaz: 2010-12-22
  rus: 2010-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/56824/kaz/22.12.2010
  rus: https://zan.gov.kz/client/#!/doc/56824/rus/22.12.2010
