act_code: '6817'
requisite: Решение акима Северо-Казахстанской области от 3 августа 1999 года № 143. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 апреля 2000 года № 119. Утратило силу решением акима Северо-Казахстанской области от 20 декабря 2017 года № 41
title:
  rus: О создании областного департамента финансов, районных и Петропавловского городского управлений финансов
  kaz: Облыстық қаржы департаментін, аудандық және Петропавл қалалық қаржы басқармаларын құру туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 1999-08-02
approved_by:
- '165000000003'
version_date:
  kaz: 1999-08-02
  rus: 1999-08-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/6817/kaz/02.08.1999
  rus: https://zan.gov.kz/client/#!/doc/6817/rus/02.08.1999
