act_code: '97891'
requisite: Решение Северо-Казахстанского областного маслихата от 14 декабря 2015 года № 40/9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 января 2016 года № 3563. Утратило силу - решением Северо-Казахстанского областного маслихата от 14 ноября 2017 года № 16/6
title:
  rus: О предоставлении гражданам Северо-Казахстанской области бесплатного проезда на лечение за пределы области за счет бюджетных средств
  kaz: Солтүстік Қазақстан облысының азаматтарына облыстан тысқары емделуге бюджет қаражаты есебінен ақысыз жол жүруді ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-14
approved_by:
- '165000000002'
version_date:
  kaz: 2015-12-14
  rus: 2015-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/97891/kaz/14.12.2015
  rus: https://zan.gov.kz/client/#!/doc/97891/rus/14.12.2015
