act_code: '54829'
requisite: Решение акима Драгомировского сельского округа Тайыншинского района Северо-Казахстанской области от 27 сентября 2010 года № 4. Зарегистрировано Управлением юстиции Тайыншинского района Северо-Казахстанской области 11 октября 2010 года № 13-11-193
title:
  rus: О присвоении наименований составных частей населенных пунктов Драгомировского сельского округа Тайыншинского района
  kaz: Тайынша ауданы Драгомиров ауылдық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-27
approved_by:
- '165011007002'
version_date:
  kaz: 2010-09-27
  rus: 2010-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/54829/kaz/27.09.2010
  rus: https://zan.gov.kz/client/#!/doc/54829/rus/27.09.2010
