act_code: '54829'
requisite: Решение акима Драгомировского сельского округа Тайыншинского района Северо-Казахстанской области от 27 сентября 2010 года № 4. Зарегистрировано Управлением юстиции Тайыншинского района Северо-Казахстанской области 11 октября 2010 года № 13-11-193
title:
  rus: О присвоении наименований составных частей населенных пунктов Драгомировского сельского округа Тайыншинского района
  kaz: Тайынша ауданы Драгомиров ауылдық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-09-27
approved_by:
- '165011007002'
version_date:
  kaz: 2018-06-27
  rus: 2018-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/54829/kaz/27.06.2018
  rus: https://zan.gov.kz/client/#!/doc/54829/rus/27.06.2018
caused_by:
  code: '123327'
  requisite: Решение акима Драгомировского сельского округа Тайыншинского района Северо-Казахстанской области от 27 июня 2018 года № 4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июля 2018 года № 4817
  title:
    rus: О внесении изменений в решение акима Драгомировского сельского округа Тайыншинского района Северо-Казахстанской области от 27 сентября 2010 года № 4 «О присвоении наименований составных частей населенных пунктов Драгомировского сельского округа Тайыншинского района»
    kaz: «Тайынша ауданы Драгомиров селолық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы» Солтүстік Қазақстан облысы Тайынша ауданы Драгомиров ауылдық округі әкімінің 2010 жылғы 27 қыркүйектегі № 4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123327/rus
