act_code: '36796'
requisite: Решение маслихата города Петропавловска Северо-Казахстанской области от 15 декабря 2007 года № 2. Зарегистрировано Управлением юстиции города Петропавловска Северо-Казахстанской области 15 января 2008 года № 13-1-109
title:
  rus: О бюджете города Петропавловска на 2008 год
  kaz: 2008 жылға арналған Петропавл қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-15
approved_by:
- '165002000002'
version_date:
  kaz: 2008-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/36796/kaz/14.11.2008
