act_code: '122966'
requisite: Решение акима Прибрежного сельского округа Кызылжарского района Северо-Казахстанской области от 19 июня 2018 года № 103. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 июня 2018 года № 4780
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-19
approved_by:
- '165008015002'
version_date:
  kaz: 2018-06-19
  rus: 2018-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/122966/kaz/19.06.2018
  rus: https://zan.gov.kz/client/#!/doc/122966/rus/19.06.2018
