act_code: '50054'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2009 жылғы 24 желтоқсандағы № 2-18с шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2010 жылғы 19 қаңтарда № 13-13-118 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2011 жылғы 3 қазандағы № 02-03-03/222 хаты)
title:
  rus: 2010-2012 жылдарға арналған аудандық бюджет туралы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-24
approved_by:
- '165013000002'
version_date:
  kaz: 2010-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/50054/kaz/24.12.2010
caused_by:
  code: '56771'
  requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 5-25с шешімі. Солтүстік Қазақстан облысының Әділет департаментінде 2011 жылғы 18 қаңтарда № 13-13-133 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2011 жылғы 3 қазандағы № 02-03-03/222 хаты)
  title:
    rus: '"2010-2012 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2009 жылғы 24 желтоқсандағы № 2-18с шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2009 жылғы 24 желтоқсандағы № 2-18с шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/56771/rus
