act_code: '29395'
requisite: Решение Маслихата города Петропавловска Северо-Казахстанской области от 7 июля 2006 года № 5. Зарегистрировано Управлением юстиции города Петропавловска Северо-Казахстанской области 16 августа 2006 года № 13-1-50. Утратило силу - решением Маслихата города Петропавловска Северо-Казахстанской области от 6 марта 2012 года № 3
title:
  rus: О Правилах содержания животных и птиц
  kaz: Мал және құс ұстау ережесін бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2006-07-07
approved_by:
- '165002000002'
version_date:
  kaz: 2006-07-07
  rus: 2006-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/29395/kaz/07.07.2006
  rus: https://zan.gov.kz/client/#!/doc/29395/rus/07.07.2006
