act_code: '53677'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 21 июня 2010 года № 24/3. Зарегистрировано Управлением юстиции Жамбылского района Северо-Казахстанской области 26 июля 2010 года № 13-7-132. Утратило силу решением маслихата Жамбылского района Северо-Казахстанской области от 21 января 2015 года № 35/3
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры и спорта проживающим и работающим в сельских населенных пунктах Жамбылского района
  kaz: Жамбыл ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сактау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-21
approved_by:
- '165007000002'
version_date:
  rus: 2011-07-28
source:
  rus: https://zan.gov.kz/client/#!/doc/53677/rus/28.07.2011
caused_by:
  code: '60106'
  requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 28 июля 2011 года № 34/3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 августа 2011 года № 13-7-154. Утратило силу решением маслихата Жамбылского района Северо-Казахстанской области от 21 января 2015 года № 35/3
  title:
    rus: О внесении дополнения в решение районного маслихата от 21 июня 2010 года № 24/3 "О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры и спорта проживающим и работающим в сельских населенных пунктах Жамбылского района"
    kaz: '"Жамбыл ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет және спорт ұйымдарының мамандарына отын сатып алу үшін әлеуметтік көмек беру туралы" аудандық мәслихаттың 2010 жылғы 21 маусымдағы № 24/3 шешіміне толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/60106/rus
