act_code: '17025'
requisite: Решение акима Мамлютского района Северо-Казахстанской области от 27 августа 2003 года № 8. Зарегистрировано Управлением юстиции Северо-Казахстанской области 22 сентября 2003 года № 1022
title:
  rus: О признании утратившим силу решения акима района от 15 декабря 2000 года № 343 (регистрационный номер № 225 от 24 января 2001 года) "Об утверждении состава и Положения о районной комиссии по обеспечению безопасности на транспорте"
  kaz: Аудан әкімінің "Көлікте қауіпсіздікті қамтамасыз ету жөніндегі аудандық комиссия туралы Ереже мен комиссия құрамын бекіту туралы" (Тіркеу нөмірі № 225, 2001 жылғы 24 қаңтар) 2000 жылғы 15 желтоқсандағы № 343 шешімін күшін жойған деп тану туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-08-26
approved_by:
- '165009000003'
version_date:
  kaz: 2003-08-26
  rus: 2003-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/17025/kaz/26.08.2003
  rus: https://zan.gov.kz/client/#!/doc/17025/rus/26.08.2003
