act_code: '169165'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 20 июня 2022 года № 17/2. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 июня 2022 года № 28553
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год на территории Жамбылского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданының аумағында шетелдіктер үшін 2022 жылға арналған туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-06-20
approved_by:
- '165007000002'
version_date:
  kaz: 2022-06-20
  rus: 2022-06-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/169165/kaz/20.06.2022
  rus: https://zan.gov.kz/client/#!/doc/169165/rus/20.06.2022
