act_code: '1197'
requisite: Решение акима Северо-Казахстанской области от 30 января 1998 года № 24. Зарегистрировано Управлением юстиции Северо-Казахстанской области 27 мая 1998 года за № 11. Утратило силу решением акима Северо-Казахстанской области от 21 августа 2014 года № 26
title:
  rus: О реализации постановления Правительства Республики Казахстан № 639 от 23.04.1997 г. "О дополнительных мероприятиях по этническому возрождению немцев, проживающих в Республике Казахстан"
  kaz: Қазақстан Республикасы Үкіметінің 23.04.1997 ж. "Қазақстан Республикасында тұратын немістерді этникалық жағынан қайтадан өркендетудің қосымша шаралары" № 639 қаулысын жүзеге асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-01-30
approved_by:
- '165000000003'
version_date:
  kaz: 1998-01-30
  rus: 1998-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/1197/kaz/30.01.1998
  rus: https://zan.gov.kz/client/#!/doc/1197/rus/30.01.1998
