act_code: '36736'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 24 декабря 2007 года № 4-3. Зарегистрировано Управлением юстиции района имени Габита Мусрепова Северо-Казахстанской области 16 января 2008 года № 13-5-50. Утратило силу решением маслихата района имени Габита Мусрепова Северо-Казахстанской области от 7 октября 2024 года № 21-25 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении ставок по отдельным видам платежей
  kaz: Салық және бюджетке төленетін басқа да міндетті төлемдер туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '165014000002'
version_date:
  kaz: 2007-12-24
  rus: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36736/kaz/24.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36736/rus/24.12.2007
