act_code: '42567'
requisite: Решение акима Бишкульского сельского округа Кызылжарского района Северо-Казахстанской области от 26 ноября 2008 № 233. Зарегистрировано Управлением юстиции Кызылжарского района Северо-Казахстанской области 28 ноября 2008 года № 13-8-94
title:
  rus: О присвоении наименований некоторым улицам села Бишкуль Кызылжарского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданы Бескөл ауылының кейбір көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-11-26
approved_by:
- '165008004001'
version_date:
  kaz: 2018-11-27
  rus: 2018-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/42567/kaz/27.11.2018
  rus: https://zan.gov.kz/client/#!/doc/42567/rus/27.11.2018
caused_by:
  code: '127152'
  requisite: Решение акима Бескольского сельского округа Кызылжарского района Северо-Казахстанской области от 27 ноября 2018 года № 411. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 декабря 2018 года № 5081
  title:
    rus: О внесении изменений в решение акима Бишкульского сельского округа Кызылжарского района Северо – Казахстанской области от 26 ноября 2008 года № 233 «О присвоении наименований некоторым улицам села Бишкуль Кызылжарского района Северо - Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Қызылжар ауданы Бескөл селолық округі әкімінің 2008 жылғы 26 қарашадағы № 233 «Солтүстік Қазақстан облысы Қызылжар ауданы Бескөл селосының кейбір көшелеріне атаулар беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127152/rus
