act_code: '6711'
requisite: Решение акима Северо-Казахстанской области от 6 июля 1999 года № 129. Зарегистрировано Управлением юстиции Северо-Казахстанской области 7 апреля 2000 года № 105. Утратило силу постановлением акимата Северо-Казахстанской области от 23 января 2002 года № 10
title:
  rus: О плане мероприятий по профилактике и борьбе со СПИДом и другими болезнями, передающимися половым путем, в Северо-Казахстанской области на 1999-2000 годы
  kaz: Солтүстік Қазақстан облысында 1999-2000 жылдарға жыныс жолымен берілетін СПИД және басқа аурулардың алдын алу және күрес жөніндегі іс-шаралар жоспары туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 1999-07-05
approved_by:
- '165000000003'
version_date:
  kaz: 1999-07-05
  rus: 1999-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/6711/kaz/05.07.1999
  rus: https://zan.gov.kz/client/#!/doc/6711/rus/05.07.1999
