act_code: '69408'
requisite: Решение акима района Шал акына Северо-Казахстанской области от 29 ноября 2012 года № 15. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 декабря 2012 года № 2001. Утратило силу в связи с истечением срока действия (письмо акима района Шал акына Северо-Казахстанской области от 12 июня 2015 года № 15.1.5-11/314)
title:
  rus: Об организации и обеспечении на территории района Шал акына приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2013 года
  kaz: Шал ақын ауданының аумағында 2013 жылғы қаңтар-наурыз аралығында Қазақстан Республикасы ер азаматтарының тіркелуін және медициналық куәландыруын ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-11-29
approved_by:
- '165010000003'
version_date:
  kaz: 2012-11-29
  rus: 2012-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/69408/kaz/29.11.2012
  rus: https://zan.gov.kz/client/#!/doc/69408/rus/29.11.2012
