act_code: '49860'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 25 декабря 2009 года № 20/1. Зарегистрировано Управлением юстиции Кызылжарского района Северо-Казахстанской области 11 января 2010 года № 13-8-115. Утратило силу - решением маслихата Кызылжарского района Северо-Казахстанской области от 16 апреля 2012 года № 4/4
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '165008000002'
version_date:
  kaz: 2010-10-28
  rus: 2010-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/49860/kaz/28.10.2010
  rus: https://zan.gov.kz/client/#!/doc/49860/rus/28.10.2010
caused_by:
  code: '55620'
  requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 28 октября 2010 года № 28/1. Зарегистрировано Управлением юстиции Кызылжарского района Северо-Казахстанской области 26 ноября 2010 № 13-8-133. Утратило силу - решением маслихата Кызылжарского района Северо-Казахстанской области от 16 апреля 2012 года № 4/4
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 25 декабря 2009 года № 20/1 "О районном бюджете на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2009 жылғы 25 желтоқсандағы № 20/1 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/55620/rus
