act_code: '43955'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 22 декабря 2008 года № 12/87. Зарегистрировано Управлением юстиции Есильского района Северо-Казахстанской области 30 января 2009 года № 13-6-109. Утратило силу - решением маслихата Есильского района Северо-Казахстанской области от 25 декабря 2009 года № 24/149
title:
  rus: О льготном проезде на сельском общественном транспорте (кроме такси) учащихся общеобразовательных учебных заведений
  kaz: Жалпы білім беретін оқу орындары оқушыларының селолық қоғамдық колікте (таксиден басқа) жеңілдікпен жүруі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-22
approved_by:
- '165006000002'
version_date:
  kaz: 2008-12-22
  rus: 2008-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/43955/kaz/22.12.2008
  rus: https://zan.gov.kz/client/#!/doc/43955/rus/22.12.2008
