act_code: '77732'
requisite: Решение маслихата Айыртауского района Северо-Казахстанской области от 29 января 2014 года № 5-22-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 февраля 2014 года № 2570. Утратило силу решением Айыртауского районного маслихата Северо-Казахстанской области от 6 апреля 2017 года № 6-9-1
title:
  rus: О Правилах оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Айыртауского района
  kaz: Айыртау ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидалары туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-01-29
approved_by:
- '165003000002'
version_date:
  kaz: 2014-01-29
  rus: 2014-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/77732/kaz/29.01.2014
  rus: https://zan.gov.kz/client/#!/doc/77732/rus/29.01.2014
