act_code: '3609'
requisite: Решение акима Северо-Казахстанской области от 10 января 1999 года № 6. Зарегистрировано Управлением юстиции Северо-Казахстанской области 11 марта 1999 года за № 61
title:
  rus: О переименовании Ленинского сельского округа Советского района в "Лесной"
  kaz: Совет ауданы Ленин селолық округінің атауын Лесной селолық округі деп өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-01-10
approved_by:
- '165000000003'
version_date:
  kaz: 1999-01-10
  rus: 1999-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/3609/kaz/10.01.1999
  rus: https://zan.gov.kz/client/#!/doc/3609/rus/10.01.1999
