act_code: '213941'
requisite: Решение акима Лесного сельского округа Аккайынского района Северо-Казахстанской области от 3 сентября 2025 года № 18
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-03
approved_by:
- '165005007002'
version_date:
  kaz: 2025-09-03
  rus: 2025-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/213941/kaz/03.09.2025
  rus: https://zan.gov.kz/client/#!/doc/213941/rus/03.09.2025
