act_code: '43953'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 24 декабря 2008 года № 11/2. Зарегистрировано Управлением юстиции Мамлютского района Северо-Казахстанской области 4 февраля 2009 года № 13-10-76. Утратило силу в связи с истечением срока применения (письмо маслихата Мамлютского района Северо-Казахстанской области от 14 октября 2011 года № 129)
title:
  rus: О районном бюджете на 2009 год
  kaz: 2009 жылғы аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '165009000002'
version_date:
  kaz: 2009-04-27
  rus: 2009-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/43953/kaz/27.04.2009
  rus: https://zan.gov.kz/client/#!/doc/43953/rus/27.04.2009
caused_by:
  code: '46047'
  requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 27 апреля 2009 года № 14/4. Зарегистрировано Управлением юстиции Мамлютского района Северо-Казахстанской области 22 мая 2009 года № 13-10-85. Утратило силу в связи с истечением срока применения (письмо маслихата Мамлютского района Северо-Казахстанской области от 14 октября 2011 года № 129)
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 24 декабря 2008 года № 11/2 "О районном бюджете на 2009 год"
    kaz: Аудандық мәслихаттың 2008 жылғы 24 желтоқсандағы "2009 жылға арналған аудандық бюджет туралы" № 11/2 шешіміне өзгертулер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/46047/rus
