act_code: '149908'
requisite: Решение акима Уалихановского района Северо-Казахстанской области от 10 декабря 2020 года № 25. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 декабря 2020 года № 6801. Утратило силу решением акима Уалихановского района Северо-Казахстанской области от 6 мая 2021 года № 9 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-10
approved_by:
- '165013000003'
version_date:
  kaz: 2020-12-10
  rus: 2020-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/149908/kaz/10.12.2020
  rus: https://zan.gov.kz/client/#!/doc/149908/rus/10.12.2020
