act_code: '49990'
requisite: Решение маслихата Северо-Казахстанской области от 29 декабря 2009 года № 20/7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 января 2010 года № 1737. Утратило силу (письмо маслихата Северо-Казахстанской области от 6 января 2015 года № 2.1-11/05)
title:
  rus: О ставках платы за лесные пользования в государственном лесном фонде и в том числе в особо охраняемых природных территориях по Северо-Казахстанской области на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған мемлекеттік орман қорында соның ішінде ерекше қорғалатын табиғи аумақтарда орманды пайдаланғаны үшін төлем ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-29
approved_by:
- '165000000002'
version_date:
  kaz: 2011-03-15
  rus: 2011-03-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/49990/kaz/15.03.2011
  rus: https://zan.gov.kz/client/#!/doc/49990/rus/15.03.2011
caused_by:
  code: '57951'
  requisite: Решение маслихата Северо-Казахстанской области от 15 марта 2011 года № 32/14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 1 апреля 2011 года № 1772. Утратило силу (письмо маслихата Северо-Казахстанской области от 10 апреля 2013 года № 01.20/126)
  title:
    rus: О внесении изменений и дополнений в решение сессии областного маслихата от 29 декабря 2009 года № 20/7 "О ставках платы за лесные пользования в государственном лесном фонде и особо охраняемых природных территориях по Северо-Казахстанской области на 2010-2012 годы"
    kaz: '"Солтүстік Қазақстан облысы бойынша 2010-2012 жылдарға арналған мемлекеттік орман қорында соның ішінде ерекше қорғалатын табиғи аумақтарда орманды пайдаланғаны үшін төлем ставкалары туралы" облыстық мәслихат сессиясының 2009 жылғы 29 желтоқсандағы № 20/7'
  link: https://zan.gov.kz/client/#!/doc/57951/rus
