act_code: '164918'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 14 февраля 2022 года № 11-4. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 октября 2023 года № 7-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей жителей  улиц города Булаево и сел сельских округов для участия в сходе местного сообщества в районе Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізудің және жергілікті қоғамдастық жиынына қатысу үшін Булаев қаласының және ауылдық округтердегі ауылдардың көшелері тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-02-14
approved_by:
- '165015000002'
version_date:
  kaz: 2022-02-14
  rus: 2022-02-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/164918/kaz/14.02.2022
  rus: https://zan.gov.kz/client/#!/doc/164918/rus/14.02.2022
