act_code: '191911'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 29 декабря 2023 года № 109/9
title:
  rus: Об утверждении бюджета Абайского сельского округа Тайыншинского района Северо-Казахстанской области на 2024 - 2026 годы
  kaz: Солтүстік Қазақстан облысы Тайынша ауданы Абай ауылдық округінің 2024 – 2026 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '165011000002'
version_date:
  kaz: 2024-11-08
  rus: 2024-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/191911/kaz/08.11.2024
  rus: https://zan.gov.kz/client/#!/doc/191911/rus/08.11.2024
caused_by:
  code: '202470'
  requisite: Решение Тайыншинского районного маслихата Северо-Казахстанской области от 8 ноября 2024 года № 223/18
  title:
    rus: О внесении изменений в решение маслихата Тайыншинского района Северо-Казахстанской области от 29 декабря 2023 года № 109/9 «Об утверждении бюджета Абайского сельского округа Тайыншинского района Северо-Казахстанской области на 2024-2026 годы»
    kaz: Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2023 жылғы 29 желтоқсадағы № 109/9 «Солтүстік Қазақстан облысы Тайынша ауданы Абай ауылдық округінің 2024-2026 жылдарға арналған бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202470/rus
