act_code: '75904'
requisite: Решение акима Тайыншинского района Северо-Казахстанской области от 6 декабря 2013 года № 28. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 декабря 2013 года № 2425. Утратило силу в связи с истечением срока действия (письмо аппарата акима Тайыншинского района Северо-Казахстанской области от 19 марта 2015 года № 12.1.7-1/518)
title:
  rus: Об организации и обеспечении на территории Тайыншинского района приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2014 года
  kaz: Қазақстан Республикасының ер азаматтарын 2014 жылдың қаңтарынан наурызына дейін Тайынша ауданының аумағында тіркеуді және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-06
approved_by:
- '165011000003'
version_date:
  kaz: 2013-12-06
  rus: 2013-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/75904/kaz/06.12.2013
  rus: https://zan.gov.kz/client/#!/doc/75904/rus/06.12.2013
