act_code: '163157'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 29 декабря 2021 года № 11/2
title:
  rus: Об утверждении бюджета Благовещенского сельского округа Жамбылского района Северо-Казахстанской области на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Солтүстік Қазақстан облысы Жамбыл ауданы Благовещенка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '165007000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/163157/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163157/rus/29.12.2021
