act_code: '69392'
requisite: Решение акима Есильского района Северо-Казахстанской области от 7 декабря 2012 года № 28. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 декабря 2012 года № 2008. Утратило силу (письмо заместителя акима Есильского района Северо-Казахстанской области от 5 апреля 2013 года № 02.04.06-12/179)
title:
  rus: Об организации и обеспечении на территории Есильского района Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2013 года
  kaz: Қазақстан Республикасының ер азаматтарын 2013 жылдың қаңтарынан наурызына дейін Солтүстік Қазақстан облысы Есіл ауданының аумағында тіркеуді және медициналық куәландырылуды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-07
approved_by:
- '165006000003'
version_date:
  kaz: 2012-12-07
  rus: 2012-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/69392/kaz/07.12.2012
  rus: https://zan.gov.kz/client/#!/doc/69392/rus/07.12.2012
