act_code: '50243'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 23 декабря 2009 года № 162. Зарегистрировано Управлением юстиции Тайыншинского района Северо-Казахстанской области 25 января 2010 года № 13-11-164. Утратило силу в связи с истечением срока действия (письмо маслихата Тайыншинского района Северо-Казахстанской области от 28 июня 2012 года № 04-05-92)
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-23
approved_by:
- '165011000002'
version_date:
  kaz: 2010-04-12
  rus: 2010-04-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/50243/kaz/12.04.2010
  rus: https://zan.gov.kz/client/#!/doc/50243/rus/12.04.2010
caused_by:
  code: '52142'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 12 апреля 2010 года № 189. Зарегистрировано Управлением юстиции Тайыншинского района Северо-Казахстанской области 22 апреля 2010 года № 13-11-173. Утратило силу в связи с истечением срока действия (письмо маслихата Тайыншинского района Северо-Казахстанской области от 16 октября 2012 года № 05-20-149)
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 23 декабря 2009 года № 162 "О районном бюджете на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2009 жылғы 23 желтоқсандағы № 162 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/52142/rus
