act_code: '84663'
requisite: Решение акима Есильского района Северо-Казахстанской области от 11 ноября 2014 года № 18. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 ноября 2014 года № 2993. Утратило силу (письмо заместителя акима Есильского района Северо-Казахстанской области от 23 апреля 2015 года № 7.1.8-15/293)
title:
  rus: Об организации и обеспечении на территории Есильского района Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2015 года
  kaz: Қазақстан Республикасының ер азаматтарын 2015 жылдың қаңтарынан наурызына дейін Солтүстік Қазақстан облысы Есіл ауданының аумағында тіркеуді және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-11
approved_by:
- '165006000003'
version_date:
  kaz: 2014-11-11
  rus: 2014-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/84663/kaz/11.11.2014
  rus: https://zan.gov.kz/client/#!/doc/84663/rus/11.11.2014
