act_code: '176402'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 27 декабря 2022 года № 17/14
title:
  rus: Об утверждении бюджета Москворецкого сельского округа Тимирязевского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Тимирязев ауданы Москворецк ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '165012000002'
version_date:
  kaz: 2023-09-25
  rus: 2023-09-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/176402/kaz/25.09.2023
  rus: https://zan.gov.kz/client/#!/doc/176402/rus/25.09.2023
caused_by:
  code: '186549'
  requisite: Решение маслихата Тимирязевского района Северо-Казахстанской области от 25 сентября 2023 года № 6/6
  title:
    rus: О внесении изменений в решение Тимирязевского районного маслихата от 27 декабря 2022 года № 17/14 «Об утверждении бюджета Москворецкого сельского округа Тимирязевского района на 2023-2025 годы»
    kaz: «2023-2025 жылдарға арналған Тимирязев ауданы Москворецк ауылдық округінің бюджетін бекіту туралы» Тимирязев аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 17/14 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186549/rus
