act_code: '151484'
requisite: Решение акима Актуесайского сельского округа Уалихановского района Северо-Казахстанской области от 31 декабря 2020 года № 24. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 5 января 2021 года № 6883
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-31
approved_by:
- '165013002002'
version_date:
  kaz: 2020-12-31
  rus: 2020-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/151484/kaz/31.12.2020
  rus: https://zan.gov.kz/client/#!/doc/151484/rus/31.12.2020
