act_code: '70159'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 20 декабря 2012 года № 8-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 16 января 2013 года № 2068
title:
  rus: О предоставлении в 2013 году мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии прибывшим для работы и проживания в селькие населенные пункты Акжарского района
  kaz: Ақжар ауданының елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына 2013 жылғы әлеуметтік шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '165004000002'
version_date:
  kaz: 2012-12-20
  rus: 2012-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/70159/kaz/20.12.2012
  rus: https://zan.gov.kz/client/#!/doc/70159/rus/20.12.2012
