act_code: '55198'
requisite: Решение акима Юбилейного сельского округа района Шал акына Северо-Казахстанской области от 8 октября 2010 года № 7. Зарегистрировано Управлением юстиции района Шал акына Северо-Казахстанской области 28 октября 2010 года № 13-14-110
title:
  rus: О присвоении наименований составным частям населенных пунктов Юбилейного сельского округа района Шал акына
  kaz: Шал ақын ауданы Юбилейный ауылдық округінің елді мекендерінің құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-08
approved_by:
- '165010012002'
version_date:
  kaz: 2010-10-08
  rus: 2010-10-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/55198/kaz/08.10.2010
  rus: https://zan.gov.kz/client/#!/doc/55198/rus/08.10.2010
