act_code: '43749'
requisite: Решение акима Айыртауского района Северо-Казахстанской области от 14 января 2009 года № 1. Зарегистрировано Управлением юстиции Айыртауского района Северо-Казахстанской области 27 января 2009 года № 13-3-91. Утратило силу - решением акима Айыртауского района Северо-Казахстанской области от 10 июля 2009 года № 21
title:
  rus: О приписке граждан Республики Казахстан мужского пола 1992 года рождения к призывному участку Айыртауского района в период с января по март 2009 года
  kaz: 2009 жылдың қаңтарынан наурызына дейінгі кезеңінде Айыртау ауданының шақыру учаскесіне Қазақстан Республикасының 1992 жылғы еркек жынысты азаматтарды тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-14
approved_by:
- '165003000003'
version_date:
  kaz: 2009-01-14
  rus: 2009-01-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/43749/kaz/14.01.2009
  rus: https://zan.gov.kz/client/#!/doc/43749/rus/14.01.2009
