act_code: '153972'
requisite: Решение Северо-Казахстанского областного маслихата от 17 марта 2021 года № 3/3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 марта 2021 года № 7197
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников по Северо-Казахстанской области на 2021 год
  kaz: Солтүстік Қазақстан облысы бойынша 2021 жылға арналған жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-17
approved_by:
- '165000000002'
version_date:
  kaz: 2021-03-17
  rus: 2021-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/153972/kaz/17.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153972/rus/17.03.2021
