act_code: '191218'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 27 декабря 2023 года № 8/4. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 28 декабря 2023 года № 7668-15
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Кызылжарском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-27
approved_by:
- '165008000002'
version_date:
  kaz: 2025-01-28
  rus: 2025-01-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/191218/kaz/28.01.2025
  rus: https://zan.gov.kz/client/#!/doc/191218/rus/28.01.2025
caused_by:
  code: '206848'
  requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 28 января 2025 года № 20/3. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 30 января 2025 года № 7855-15
  title:
    rus: О внесении изменения в решение Кызылжарского районного маслихата Северо-Казахстанской области от 27 декабря 2023 года № 8/4 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Кызылжарском районе Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Қызылжар ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Солтүстік Қазақстан облысы Қызылжар аудандық мәслихатының 2023 жылғы 27 желтоқсанда № 8/4 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/206848/rus
