act_code: '52465'
requisite: Солтүстік Қазақстан облысы Уәлиханов ауданы Кішкенекөл селолық округі әкімінің 2010 жылғы 21 сәуірдегі № 14 шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2010 жылғы 14 мамырда № 13-13-124 тіркелді
title:
  rus: Уәлиханов ауданы Кішкенекөл селосының көше атауларын өзгерту туралы
  kaz: Уәлиханов ауданы Кішкенекөл селосының көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-21
approved_by:
- '165013001002'
version_date:
  kaz: 2010-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/52465/kaz/21.04.2010
