act_code: '204061'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 9 декабря 2024 года № 35/14
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию в Мамлютском районе Северо-Казахстанской области на 2024-2028 годы
  kaz: 2024-2028 жылдарға арналған Солтүстік Қазақстан облысы Мамлют ауданында жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2024-12-09
approved_by:
- '165009000002'
version_date:
  kaz: 2025-03-14
  rus: 2025-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/204061/kaz/14.03.2025
  rus: https://zan.gov.kz/client/#!/doc/204061/rus/14.03.2025
caused_by:
  code: '208320'
  requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 14 марта 2025 года № 39/8
  title:
    rus: О внесении изменений в решение маслихата Мамлютского района Северо-Казахстанской области от 9 декабря 2024 года № 35/14 «Об утверждении Плана по управлению пастбищами и их использованию в Мамлютском районе Северо-Казахстанской области на 2024-2028 годы»
    kaz: Солтүстік Қазақстан облысы Мамлют ауданы мәслихатының 2024 жылғы 9 желтоқсандағы № 35/14 «2024-2028 жылдарға арналған Солтүстік Қазақстан облысы Мамлют ауданында жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208320/rus
