act_code: '206319'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2024 года № 23-10. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 12 мая 2025 года № 27-11 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета Лебяжинского сельского округа района Магжана Жумабаева на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Мағжан Жұмабаев ауданы Лебяжье ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '165015000002'
version_date:
  kaz: 2025-02-28
  rus: 2025-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/206319/kaz/28.02.2025
  rus: https://zan.gov.kz/client/#!/doc/206319/rus/28.02.2025
caused_by:
  code: '207699'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 28 февраля 2025 года № 25-12. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 12 мая 2025 года № 27-11 (вводится в действие с 1 января 2025 года)
  title:
    rus: О внесении изменений и дополнений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2024 года № 23-10 «Об утверждении бюджета Лебяжинского сельского округа района Магжана Жумабаева на 2025-2027 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2024 жылғы 30 желтоқсандағы № 23-10 «2025-2027 жылдарға арналған Мағжан Жұмабаев ауданы Лебяжье ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207699/rus
