act_code: '195512'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 29 марта 2024 года № 8-13-1. Зарегистрирован в Департаменте юстиции Северо-Казахстанской области 8 апреля 2024 года № 7743-15
title:
  rus: Об определении размера и Правил оказания жилищной помощи в Айыртауском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-03-29
approved_by:
- '165003000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195512/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195512/rus/29.03.2024
