act_code: '190652'
requisite: Решение Северо-Казахстанского областного маслихата от 15 декабря 2023 года № 9/1
title:
  rus: Об утверждении областного бюджета Северо-Казахстанской области на 2024 – 2026 годы
  kaz: Солтүстік Қазақстан облысының 2024 - 2026 жылдарға арналған облыстық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-15
approved_by:
- '165000000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/190652/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190652/rus/15.12.2023
