act_code: '203719'
requisite: Решение акима Светлопольского сельского округа Кызылжарского района Северо-Казахстанской области от 5 декабря 2024 года № 16
title:
  rus: Об установлении права ограниченного целевого землепользования (публичный сервитут) акционерному обществу «Казахтелеком»
  kaz: «Қазақтелеком» акционерлік қоғамына шектеулі нысаналы жер пайдалану құқығын (қауымдық сервитут) белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-05
approved_by:
- '165008018002'
version_date:
  kaz: 2024-12-05
  rus: 2024-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/203719/kaz/05.12.2024
  rus: https://zan.gov.kz/client/#!/doc/203719/rus/05.12.2024
