act_code: '127013'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 29 ноября 2018 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 декабря 2018 года № 5072. Утратило силу решением Петропавловского городского маслихата Северо-Казахстанской области от 20 апреля 2026 года № 6/33 (вводится в действие с 01 января 2026 года)
title:
  rus: О корректировке базовых ставок земельного налога по городу Петропавловску
  kaz: Петропавл қаласы бойынша жер салығының базалық мөлшерлемелерін түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-29
approved_by:
- '165002000002'
version_date:
  kaz: 2018-11-29
  rus: 2018-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/127013/kaz/29.11.2018
  rus: https://zan.gov.kz/client/#!/doc/127013/rus/29.11.2018
