act_code: '107349'
requisite: Решение акима Кишкенекольского сельского округа Уалихановского района Северо-Казахстанской области от 25 октября 2016 года № 70. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 7 ноября 2016 года № 3915
title:
  rus: О снятии ограничительных мероприятий по бруцеллезу крупного рогатого скота на стадо товарищество с ограниченной ответственностью «КЗЫЛ-ТУ АГРО» на территории села Кишкенеколь Кишкенекольского сельского округа Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Кішкенекөл ауылдық округі Кішкенекөл ауылының аумағында «КЗЫЛ-ТУ АГРО» жауапкершілігі шектеулі серіктестігі ірі қара мал табына бруцеллез шектеу шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-10-25
approved_by:
- '165013001001'
version_date:
  kaz: 2016-10-25
  rus: 2016-10-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/107349/kaz/25.10.2016
  rus: https://zan.gov.kz/client/#!/doc/107349/rus/25.10.2016
