act_code: '139476'
requisite: Решение акима Светлопольского сельского округа Кызылжарского района Северо-Казахстанской области от 6 февраля 2020 года № 3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 февраля 2020 года № 5995
title:
  rus: О присвоении наименований безымянным улицам
  kaz: Атауы жоқ көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-06
approved_by:
- '165008018002'
version_date:
  kaz: 2020-02-06
  rus: 2020-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/139476/kaz/06.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139476/rus/06.02.2020
