act_code: '118291'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 26 декабря 2017 года № 6-15-13. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 17 января 2018 года № 4536
title:
  rus: О бюджете Казанского сельского округа Айыртауского района на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Айыртау ауданы Казанка ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-26
approved_by:
- '165003000002'
version_date:
  kaz: 2018-09-28
  rus: 2018-09-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/118291/kaz/28.09.2018
  rus: https://zan.gov.kz/client/#!/doc/118291/rus/28.09.2018
caused_by:
  code: '125162'
  requisite: Решение маслихата Айыртауского района Северо-Казахстанской области от 28 сентября 2018 года № 6-22-4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 октября 2018 года № 4927
  title:
    rus: О внесении изменения в решение Айыртауского районного маслихата от 26 декабря 2017 года № 6-15-13 «О бюджете Казанского сельского округа Айыртауского района на 2018-2020 годы»
    kaz: Айыртау аудандық мәслихатының 2017 жылғы 26 желтоқсандағы № 6-15-13 «2018-2020 жылдарға арналған Айыртау ауданы Казанка ауылдық округінің бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125162/rus
