act_code: '171216'
requisite: Решение Северо-Казахстанского областного маслихата от 31 августа 2022 года № 20/8. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 сентября 2022 года № 29410. Утратило силу решением Северо-Казахстанского областного маслихата от 23 июня 2026 года № 37/3 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об утверждении размера платы за один кубический метр поданной питьевой воды населению из особо важных групповых и локальных систем водоснабжения, являющихся безальтернативными источниками питьевого водоснабжения по Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы бойынша ауызсумен жабдықтаудың баламасыз көздері болып табылатын сумен жабдықтаудың ерекше маңызды топтық және оқшау жүйелерінен халыққа берілген ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-08-31
approved_by:
- '165000000002'
version_date:
  kaz: 2025-01-01
  rus: 2025-01-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/171216/kaz/01.01.2025
  rus: https://zan.gov.kz/client/#!/doc/171216/rus/01.01.2025
caused_by:
  code: '204412'
  requisite: Решение Северо-Казахстанского областного маслихата от 12 декабря 2024 года № 20/4. Утратило силу решением Северо-Казахстанского областного маслихата от 23 июня 2026 года № 37/4 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Северо-Казахстанского областного маслихата от 31 августа 2022 года № 20/8 «Об утверждении размера платы за один кубический метр поданной питьевой воды населению из особо важных групповых и локальных систем водоснабжения, являющихся безальтернативными источниками питьевого водоснабжения по Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облыстық мәслихатының 2022 жылғы 31 тамыздағы № 20/8 «Солтүстік Қазақстан облысы бойынша ауызсумен жабдықтаудың баламасыз көздері болып табылатын сумен жабдықтаудың ерекше маңызды топтық және оқшау жүйелерінен халыққа берілген ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204412/rus
