act_code: '218298'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 27 ноября 2025 года № 35/3
title:
  rus: О корректировке базовых налоговых ставок земельного налога в районе Шал акына
  kaz: Шал ақын ауданында жер салығының базалық салықтық мөлшерлемелерін түзету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-27
approved_by:
- '165010000002'
version_date:
  kaz: 2025-11-27
  rus: 2025-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/218298/kaz/27.11.2025
  rus: https://zan.gov.kz/client/#!/doc/218298/rus/27.11.2025
