act_code: '92251'
requisite: Решение маслихата Северо-Казахстанской области от 29 июня 2015 года № 36/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 июля 2015 года № 3331
title:
  rus: Об утверждении перечня социально значимых железнодорожных пассажирских межрайонных (междугородных внутриобластных) сообщений по Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы бойынша әлеуметтік мәні бар ауданаралық (облысішілік қалааралық) теміржол жолаушылар қатынастарының тiзбесін бекіту туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2015-06-29
approved_by:
- '165000000002'
version_date:
  kaz: 2015-06-29
  rus: 2015-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/92251/kaz/29.06.2015
  rus: https://zan.gov.kz/client/#!/doc/92251/rus/29.06.2015
