act_code: '171528'
requisite: Решение акима района имени Габита Мусрепова Северо-Казахстанской области от 8 сентября 2022 года № 8. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 сентября 2022 года № 29553. Утратило силу решением акима района имени Габита Мусрепова Северо-Казахстанской области от 12 октября  2022 года № 9 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба
  kaz: Жергілікті ауқымдағы техногендік сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-08
approved_by:
- '165014000003'
version_date:
  kaz: 2022-09-08
  rus: 2022-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/171528/kaz/08.09.2022
  rus: https://zan.gov.kz/client/#!/doc/171528/rus/08.09.2022
