act_code: '18124'
requisite: Решение Северо-Казахстанского маслихата от 13 декабря 2003 года № 3/4. Зарегистрировано Управлением юстиции Северо-Казахстанской области 29 декабря 2003 года за № 1097. Утратило силу - решением маслихата Северо-Казахстанской области от 23 июля 2010 года № 27/10
title:
  rus: Об областном бюджете на 2004 год
  kaz: 2004 жылға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2003-12-13
approved_by:
- '165000000002'
version_date:
  kaz: 2004-10-06
  rus: 2004-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/18124/kaz/06.10.2004
  rus: https://zan.gov.kz/client/#!/doc/18124/rus/06.10.2004
caused_by:
  code: '21760'
  requisite: Решение Северо-Казахстанского маслихата от 7 октября 2004 года № 10/1. Зарегистрировано Департаменом юстиции Северо-Казахстанской области 1 ноября 2004 года за № 1376. Утратило силу - решением маслихата Северо-Казахстанской области от 23 июля 2010 года № 27/10
  title:
    rus: О внесении изменений и дополнений в решение областного маслихата № 3/4 от 13 декабря 2003 года "Об областном бюджете на 2004 год"
    kaz: '"2004 жылға арналған облыстық бюджет туралы" облыстық мәслихаттың 2003 жылғы 13 желтоқсандағы № 3/4 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/21760/rus
