act_code: '85718'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 25 декабря 2014 года № 32-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2015 года № 3049
title:
  rus: О бюджете района имени Габита Мусрепова на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған Ғабит Мүсірепов атындағы ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '165014000002'
version_date:
  kaz: 2015-03-27
  rus: 2015-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/85718/kaz/27.03.2015
  rus: https://zan.gov.kz/client/#!/doc/85718/rus/27.03.2015
caused_by:
  code: '88533'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 27 марта 2015 года № 34-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 апреля 2015 года № 3196
  title:
    rus: О внесении изменений и дополнений в решение маслихата  района имени Габита Мусрепова от 25 декабря 2014 года № 32-2 «О бюджете района имени Габита Мусрепова на 2015-2017 годы»
    kaz: Ғабит Мүсірепов атындағы ауданы мәслихатының 2014 жылғы 25 желтоқсандағы № 32-2 «2015-2017 жылдарға арналған Ғабит Мүсірепов атындағы ауданының бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/88533/rus
