act_code: '46074'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 27 апреля 2009 года № 16-13с. Зарегистрировано Управлением юстиции Уалихановского района Северо-Казахстанской области 21 мая 2009 года № 13-13-104
title:
  rus: Жер салығының базалық ставкасын бекіту туралы
  kaz: Жер салығының базалық ставкасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-27
approved_by:
- '165013000002'
version_date:
  kaz: 2009-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/46074/kaz/27.04.2009
