act_code: '85341'
requisite: Решение акима Акжарского района Северо-Казахстанской области от 3 декабря 2014 года № 14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 декабря 2014 года № 3024
title:
  rus: Об организации и обеспечении на территории Акжарского района приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2015 года
  kaz: 2015 жылдың қаңтарынан бастап наурызға дейін Қазақстан Республикасы ер азаматтарының Ақжар ауданының аумағында тіркеуін және медициналық куәландырылуын ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-03
approved_by:
- '165004000001'
version_date:
  kaz: 2014-12-03
  rus: 2014-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/85341/kaz/03.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85341/rus/03.12.2014
