act_code: '176282'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 27 декабря 2022 года № 17/3
title:
  rus: Об утверждении бюджета Аксуатского сельского округа Тимирязевского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Тимирязев ауданы Ақсуат ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '165012000002'
version_date:
  kaz: 2023-04-25
  rus: 2023-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/176282/kaz/25.04.2023
  rus: https://zan.gov.kz/client/#!/doc/176282/rus/25.04.2023
caused_by:
  code: '180332'
  requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 25 апреля 2023 года № 2/3
  title:
    rus: О внесении изменений и дополнений в решение Тимирязевского районного маслихата от 27 декабря 2022 года № 17/3 «Об утверждении бюджета Аксуатского сельского округа Тимирязевского района на 2023-2025 годы»
    kaz: Тимирязев аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 17/3 «2023-2025 жылдарға арналған Тимирязев ауданы Ақсуат ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180332/rus
