act_code: '137578'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 24 декабря 2019 года № 51-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 декабря 2019 года № 5756
title:
  rus: Об утверждении бюджета Акжарского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ақжар аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '165004000002'
version_date:
  kaz: 2020-08-18
  rus: 2020-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/137578/kaz/18.08.2020
  rus: https://zan.gov.kz/client/#!/doc/137578/rus/18.08.2020
caused_by:
  code: '145735'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 18 августа 2020 года № 61-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 25 августа 2020 года № 6486
  title:
    rus: О внесении изменений в решение Акжарского районного маслихата от 24 декабря 2019 года № 51-1 «Об утверждении бюджета Акжарского района на 2020-2022 годы»
    kaz: Ақжар аудандық мәслихатының 2019 жылғы 24 желтоқсандағы № 51-1 «2020-2022 жылдарға арналған Ақжар аудандық бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145735/rus
