act_code: '187703'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 октября 2023 года № 7-4
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей жителей улиц города Булаево и сел сельских округов для участия в сходе местного сообщества в районе Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін Булаев қаласының көшелері мен ауылдық округтердің ауылдары тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-24
approved_by:
- '165015000002'
version_date:
  kaz: 2023-10-24
  rus: 2023-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/187703/kaz/24.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187703/rus/24.10.2023
