act_code: '112905'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 5 мая 2017 года № 7-15 с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 16 июня 2017 года № 4225
title:
  rus: Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки села Кишкенеколь и населенных пунктов Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Кішкенекөл ауылы және ауылдық елді мекендерінің жер учаскелеріне базалық мөлшерлемелер төлеміне түзету коэффициенттерін және жерлерді аймақтау жобасын (схемасын), бағалау аймақтарының шекараларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-05-05
approved_by:
- '165013000002'
version_date:
  kaz: 2022-09-13
  rus: 2022-09-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/112905/kaz/13.09.2022
  rus: https://zan.gov.kz/client/#!/doc/112905/rus/13.09.2022
caused_by:
  code: '171622'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 13 сентября 2022 года № 18-22 c. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 сентября 2022 года № 29596
  title:
    rus: О внесении изменения в решение Уалихановского районного маслихата Северо-Казахстанской области от 5 мая 2017 года №7-15 с «Об утверждении проекта (схемы) зонирования земель, границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки села Кишкенеколь и населенных пунктов Уалихановского района Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2017 жылғы 5 мамырдағы № 7-15 с «Солтүстік Қазақстан облысы Уәлиханов ауданы Кішкенекөл ауылы және ауылдық елді мекендерінің жер учаскелеріне базалық мөлшерлемелер төлеміне түзету коэффициенттерін және жерлерді аймақтау жобасын (схемасын), бағалау аймақтарының шекараларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171622/rus
