act_code: '68093'
requisite: Решение акима Астраханского сельского округа Аккайынского района Северо-Казахстанской области от 12 сентября 2012 года № 16. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 октября 2012 года № 1900
title:
  rus: О присвоении наименований улицам в селе Каратомар Аккайынского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданының Қаратомар ауылы көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-12
approved_by:
- '165005002001'
version_date:
  kaz: 2018-07-11
  rus: 2018-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/68093/kaz/11.07.2018
  rus: https://zan.gov.kz/client/#!/doc/68093/rus/11.07.2018
caused_by:
  code: '123894'
  requisite: Решение акима Астраханского сельского округа Аккайынского района Северо-Казахстанской области от 11 июля 2018 года № 8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 23 июля 2018 года № 4857
  title:
    rus: О внесении изменений в решение акима Астраханского сельского округа Аккайынского района Северо-Казахстанской области от 12 сентября 2012 года №16 «О присвоении наименований улицам в селе Каратомар Аккайынского района Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Аққайың ауданының Қаратомар селосы көшелеріне атау беру туралы» Солтүстік Қазақстан облысы Аққайың ауданы Астраханка ауылдық округі әкімінің 2012 жылғы 12 қыркүйектегі № 16 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123894/rus
