act_code: '68093'
requisite: Решение акима Астраханского сельского округа Аккайынского района Северо-Казахстанской области от 12 сентября 2012 года № 16. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 октября 2012 года № 1900
title:
  rus: О присвоении наименований улицам в селе Каратомар Аккайынского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданының Қаратомар ауылы көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-12
approved_by:
- '165005002001'
version_date:
  kaz: 2012-09-12
  rus: 2012-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/68093/kaz/12.09.2012
  rus: https://zan.gov.kz/client/#!/doc/68093/rus/12.09.2012
