act_code: '55974'
requisite: Солтүстік Қазақстан облысы Уәлиханов ауданы әкімінің 2010 жылғы 6 желтоқсандағы № 22 шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2010 жылғы 14 желтоқсанда № 13-13-132 тіркелді. Күші жойылды - Солтүстік Қазақстан облысы Уәлиханов ауданы әкімінің 2011 жылғы 30 қарашадағы № 33 Шешімімен
title:
  rus: Уәлиханов ауданының шақыру учаскесіне 1994 жылы туған еркек жынысты азаматтарын 2011 жылдың қаңтар-наурыз айларында тіркеуін ұйымдастыру және қамтамасыз ету туралы
  kaz: Уәлиханов ауданының шақыру учаскесіне 1994 жылы туған еркек жынысты азаматтарын 2011 жылдың қаңтар-наурыз айларында тіркеуін ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-06
approved_by:
- '165013000003'
version_date:
  kaz: 2010-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/55974/kaz/06.12.2010
