act_code: '1053'
requisite: Решение акима Северо-Казахстанской области от 6 февраля 1998 года № 32. Зарегистрировано Управлением юстиции Северо-Казахстанской области 15 мая 1998 года за № 12. Утратило силу решением акима Северо-Казахстанской области от 24 августа 2005 года № 24
title:
  rus: Об упорядочении сборов и поступлений в местный бюджет налога на имущество, земельного налога, налога на транспортные средства с физических лиц
  kaz: Жеке тұлғалардан жергілікті бюджетке мүлік салығы, жер салығы, көлік құралдары үшін салық жөніндегі алымдар мен түсімдерді жинауды ретке келтіру жөнінде
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-02-06
approved_by:
- '165000000003'
version_date:
  kaz: 1998-02-06
  rus: 1998-02-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/1053/kaz/06.02.1998
  rus: https://zan.gov.kz/client/#!/doc/1053/rus/06.02.1998
