act_code: '163267'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 29 декабря 2021 года № 11/21
title:
  rus: Об утверждении бюджета Петерфельдского сельского округа Кызылжарского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Қызылжар ауданының Петерфельд ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '165008000002'
version_date:
  kaz: 2021-12-29
  rus: 2021-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/163267/kaz/29.12.2021
  rus: https://zan.gov.kz/client/#!/doc/163267/rus/29.12.2021
