act_code: '69388'
requisite: Решение акима Акжарского района Северо-Казахстанской области от 29 ноября 2012 года № 14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 декабря 2012 года № 2003
title:
  rus: Об организации и обеспечении на территории Акжарского района приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2013 года
  kaz: 2013 жылдың қаңтарынан бастап наурызға дейін Қазақстан Республикасының ер азаматтарының Ақжар ауданының аумағында тіркеуін және медициналық куәландырылуын ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-11-29
approved_by:
- '165004000001'
version_date:
  kaz: 2012-11-29
  rus: 2012-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/69388/kaz/29.11.2012
  rus: https://zan.gov.kz/client/#!/doc/69388/rus/29.11.2012
