act_code: '174333'
requisite: Решение акима Заградовского сельского округа Есильского района Северо-Казахстанской области от 25 ноября 2022 года № 28. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 ноября 2022 года № 30780
title:
  rus: О переименовании улицы села Горное Заградовского сельского округа Есильского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Есіл ауданы Заградовка ауылдық округі Горный ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-25
approved_by:
- '165006015002'
version_date:
  kaz: 2022-11-25
  rus: 2022-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/174333/kaz/25.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174333/rus/25.11.2022
