act_code: '85820'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 26 ноября 2014 года № 31-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 января 2015 года № 3061. Утратило силу решением маслихата Акжарского района Северо-Казахстанской области от 08 сентября 2015 года № 37-4
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Акжарском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысының Ақжар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-11-26
approved_by:
- '165004000002'
version_date:
  kaz: 2014-11-26
  rus: 2014-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/85820/kaz/26.11.2014
  rus: https://zan.gov.kz/client/#!/doc/85820/rus/26.11.2014
