act_code: '193777'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 19 февраля 2024 года № 9/7. Утратило силу решением Кызылжарского районного маслихата Северо-Казахстанской области от 28 января 2025 года № 20/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Кызылжарскому району на 2024-2025 годы
  kaz: Қызылжар ауданы бойынша 2024-2025 жылдарға арналған жайылымдарды басқару және оларды пайдалану жөніндегі жоспарын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-19
approved_by:
- '165008000002'
version_date:
  kaz: 2024-02-19
  rus: 2024-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/193777/kaz/19.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193777/rus/19.02.2024
