act_code: '155313'
requisite: Решение акима Березовского сельского округа Кызылжарского района Северо-Казахстанской области от 27 апреля 2021 года № 9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 апреля 2021 года № 7359. Утратило силу - решением акима Березовского сельского округа Кызылжарского района Северо-Казахстанской области от 3 июля 2021 года № 19 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-27
approved_by:
- '165008003002'
version_date:
  kaz: 2021-04-27
  rus: 2021-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/155313/kaz/27.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155313/rus/27.04.2021
