act_code: '120481'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 26 марта 2018 года № 26/3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 апреля 2018 года № 4645. Утратило силу решением маслихата Мамлютского района Северо-Казахстанской области от 22 декабря 2025 года № 50/6 (вводится в действие с 1 января 2026 года)
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-26
approved_by:
- '165009000002'
version_date:
  kaz: 2022-02-02
  rus: 2022-02-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/120481/kaz/02.02.2022
  rus: https://zan.gov.kz/client/#!/doc/120481/rus/02.02.2022
caused_by:
  code: '164380'
  requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 2 февраля 2022 года № 17/5. Зарегистрировано в Министерстве юстиции Республики Казахстан 9 февраля 2022 года № 26765. Утратило силу решением маслихата Мамлютского района Северо-Казахстанской области от 22 декабря 2025 года № 50/6 (вводится в действие с 1 января 2026 года)
  title:
    rus: О внесении изменений в решение маслихата Мамлютского района Северо-Казахстанской области от 26 марта 2018 года № 26/3 «О ставках земельного налога»
    kaz: Солтүстік Қазақстан облысы Мамлют ауданы мәслихатының 2018 жылғы 26 наурыздағы № 26/3 «Жер салығының мөлшерлемелері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/164380/rus
