act_code: '138054'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 8 января 2020 года № 35-21. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2020 года № 5816
title:
  rus: Об утверждении бюджета сельского округа Шагалалы Аккайынского района на 2020 -2022 годы
  kaz: 2020-2022 жылдарға арналған Аққайың ауданының Шағалалы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165005000002'
version_date:
  kaz: 2020-07-01
  rus: 2020-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/138054/kaz/01.07.2020
  rus: https://zan.gov.kz/client/#!/doc/138054/rus/01.07.2020
caused_by:
  code: '144377'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 1 июля 2020 года № 39-18. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 2 июля 2020 года № 6424
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 8 января 2020 года № 35-21 «Об утверждении бюджета сельского округа Шагалалы Аккайынского района на 2020-2022 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2020 жылғы 8 қаңтардағы № 35-21 «2020-2022 жылдарға арналған Аққайың ауданының Шағалалы ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144377/rus
