act_code: '75911'
requisite: Решение акима района Магжана Жумабаева Северо-Казахстанской области от 9 декабря 2013 года № 17. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 декабря 2013 года № 2433. Утратило силу в связи с истечением срока действия (письмо аппарата акима района Магжана Жумабаева Северо-Казахстанской области от 3 апреля 2014 года № 10.1.5-7/290)
title:
  rus: Об организации и обеспечении на территории района Магжана Жумабаева Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2014 года
  kaz: Солтүстiк Қазақстан облысы Мағжан Жұмабаев ауданының аумағында 2014 жылғы қаңтар-наурыз аралығында Қазақстан Республикасының ер азаматтарын тiркеудi және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-09
approved_by:
- '165015000003'
version_date:
  kaz: 2013-12-09
  rus: 2013-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/75911/kaz/09.12.2013
  rus: https://zan.gov.kz/client/#!/doc/75911/rus/09.12.2013
