act_code: '146170'
requisite: Решение акима Бидайыкского сельского округа Уалихановского района Северо-Казахстанской области от 8 сентября 2020 года № 25. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 сентября 2020 года № 6527
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-08
approved_by:
- '165013004002'
version_date:
  kaz: 2020-09-08
  rus: 2020-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/146170/kaz/08.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146170/rus/08.09.2020
