act_code: '220983'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 декабря 2025 года № 34-7
title:
  rus: Об утверждении бюджета сельского округа Аққайың района Магжана Жумабаева на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Мағжан Жұмабаев ауданы Аққайың ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-24
approved_by:
- '165015000002'
version_date:
  kaz: 2026-02-12
  rus: 2026-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/220983/kaz/12.02.2026
  rus: https://zan.gov.kz/client/#!/doc/220983/rus/12.02.2026
caused_by:
  code: '222238'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 12 февраля 2026 года № 37-4
  title:
    rus: О внесении изменений и дополнения в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 декабря 2025 года № 34-7 «Об утверждении бюджета сельского округа Аққайың района Магжана Жумабаева на 2026-2028 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2025 жылғы 24 желтоқсандағы № 34-7 «2026-2028 жылдарға арналған Мағжан Жұмабаев ауданы Аққайың ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222238/rus
