act_code: '189109'
requisite: Решение акима Камсактинского сельского округа Айыртауского района Северо-Казахстанской области от 23 ноября 2023 года № 24-р
title:
  rus: О переименовании улиц села Карасевка Камсактинского сельского округа Айыртауского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданы Қамсақты ауылдық округі Карасевка ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-23
approved_by:
- '165003009002'
version_date:
  kaz: 2023-11-23
  rus: 2023-11-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/189109/kaz/23.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189109/rus/23.11.2023
