act_code: '154664'
requisite: Решение акима Тельжанского сельского округа Уалихановского района Северо-Казахстанской области от 14 апреля 2021 года № 8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 апреля 2021 года № 7292
title:
  rus: О присвоении наименования безымянной улице села Тельжан Тельжанского сельского округа Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Телжан ауылдық округі Телжан ауылының атауы жоқ көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-14
approved_by:
- '165013011002'
version_date:
  kaz: 2021-04-14
  rus: 2021-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/154664/kaz/14.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154664/rus/14.04.2021
