act_code: '162408'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 27 декабря 2021 года № 9/8
title:
  rus: Об утверждении бюджета Есильского сельского округа Тимирязевского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Тимирязев ауданы Есіл ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '165012000002'
version_date:
  kaz: 2022-06-30
  rus: 2022-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/162408/kaz/30.06.2022
  rus: https://zan.gov.kz/client/#!/doc/162408/rus/30.06.2022
caused_by:
  code: '169449'
  requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 30 июня 2022 года № 13/26
  title:
    rus: О внесении изменений и дополнений в решение Тимирязевского районного маслихата от 27 декабря 2021 года № 9/8 «Об утверждении бюджета Есильского сельского округа Тимирязевского района на 2022-2024 годы»
    kaz: Тимирязев аудандық мәслихатының 2021 жылғы 27 желтоқсандағы № 9/8 «2022-2024 жылдарға арналған Тимирязев ауданы Есіл ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169449/rus
