act_code: '162408'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 27 декабря 2021 года № 9/8
title:
  rus: Об утверждении бюджета Есильского сельского округа Тимирязевского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Тимирязев ауданы Есіл ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '165012000002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/162408/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162408/rus/27.12.2021
