act_code: '79806'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 27 марта 2014 года № 29/170. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 5 мая 2014 года № 2738. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 28 ноября 2016 года № 8/45
title:
  rus: Об утверждении Регламента маслихата Есильского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысының Есіл ауданы мәслихатының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-03-27
approved_by:
- '165006000002'
version_date:
  kaz: 2014-03-27
  rus: 2014-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/79806/kaz/27.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79806/rus/27.03.2014
