act_code: '206131'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 27 декабря 2024 года № 25/2. Утратило силу решением маслихата Жамбылского района Северо-Казахстанской области от 12 мая 2025 года № 30/3 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета Благовещенского сельского округа Жамбылского района Северо-Казахстанской области на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Солтүстік Қазақстан облысы Жамбыл ауданы Благовещенка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '165007000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206131/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206131/rus/27.12.2024
