act_code: '81603'
requisite: Решение акима Лобановского сельского округа Айыртауского района Северо-Казахстанской области от 30 июня 2014 года N 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 июля 2014 года N 2881. Утратило силу решением акима Лобановского сельского округа Айыртауского района Северо-Казахстанской области от 9 ноября 2015 года № 17
title:
  rus: Об установлении ограничительных мероприятий по бруцеллезу крупного рогатого скота в селе Альжан Лобановского сельского округа Айыртауского района Северо Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданы Лобанов ауылдық округінің Әлжан ауылында ірі қара малға бруцеллез бойынша шектеу шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-06-30
approved_by:
- '165003012001'
version_date:
  kaz: 2014-06-30
  rus: 2014-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/81603/kaz/30.06.2014
  rus: https://zan.gov.kz/client/#!/doc/81603/rus/30.06.2014
