act_code: '206554'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 27 декабря 2024 года № 11-25 с. Утратило силу решением Уалихановского районного маслихата Северо-Казахстанской области от 6 мая 2025 года № 11-30 с (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета Кулыкольского сельского округа Уалихановского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Уәлиханов ауданы Қулыкөл ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '165013000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206554/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206554/rus/27.12.2024
