act_code: '94233'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 8 сентября 2015 года № 37-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 сентября 2015 года № 3395. Утратило силу решением Акжарского районного маслихата Северо-Казахстанской области от 23 января 2017 года № 10-3
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Акжарского районного маслихата»
  kaz: «Ақжар аудандық мәслихаттың аппараты» мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-09-08
approved_by:
- '165004000002'
version_date:
  kaz: 2015-09-08
  rus: 2015-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/94233/kaz/08.09.2015
  rus: https://zan.gov.kz/client/#!/doc/94233/rus/08.09.2015
