act_code: '9934'
requisite: Решение Северо-Казахстанского областного маслихата от 28 июня 2001 года № 12/2. Зарегистрировано управлением юстиции Северо-Казахстанской области 7 августа 2001 года № 411. Утратило силу решением Северо-Казахстанского областного маслихата области № 12/7 от 21 декабря 2004 года.
title:
  rus: Об утверждении Регламента Северо-Казахстанского областного маслихата
  kaz: Солтүстік Қазақстан облыстық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2001-06-27
approved_by:
- '165000000002'
version_date:
  kaz: 2001-06-27
  rus: 2001-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/9934/kaz/27.06.2001
  rus: https://zan.gov.kz/client/#!/doc/9934/rus/27.06.2001
