act_code: '197848'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 18 июня 2024 года № 19/4. Зарегистрирован в Департаменте юстиции Северо-Казахстанской области 19 июня 2024 года № 7766-15
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на территории района Шал акына Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Шал ақын ауданының аумағында шетелдіктер үшін арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-18
approved_by:
- '165010000002'
version_date:
  kaz: 2024-06-18
  rus: 2024-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/197848/kaz/18.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197848/rus/18.06.2024
