act_code: '169768'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 11 июля 2022 года № 7-19-5
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» коммунального государственного учреждения «Аппарат маслихата Айыртауского района Северо-Казахстанской области»
  kaz: «Солтүстік Қазақстан облысы Айыртау ауданы мәслихатының аппараты» коммуналдық мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2022-07-11
approved_by:
- '165003000002'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/169768/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/169768/rus/08.09.2025
caused_by:
  code: '214065'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 8 сентября 2025 года № 8-31-2
  title:
    rus: О внесении изменения в решение Айыртауского районного маслихата Северо-Казахстанской области от 11 июля 2022 года № 7-19-5 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» коммунального государственного учреждения «Аппарат маслихата Айыртауского района Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Айыртау аудандық мәслихатының 2022 жылғы 11 шілдедегі № 7-9-15 «Солтүстік Қазақстан облысы Айыртау ауданы мәслихатының аппараты» коммуналдық мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214065/rus
