act_code: '50037'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 25 декабря 2009 года № 24/144. Зарегистрировано Управлением юстиции Есильского района Северо-Казахстанской области 20 января 2010 года № 13-6-136. Утратило силу - решением маслихата Есильского района Северо-Казахстанской области от 22 декабря 2010 года № 36/208
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '165006000002'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/50037/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/50037/rus/25.12.2009
