act_code: '35350'
requisite: Решение акима города Сергеевки района Шал акына Северо-Казахстанской области от 12 сентября 2007 года № 153. Зарегистрировано Управлением юстиции района Шал акына Северо-Казахстанской области 15 октября 2007 года № 13-14-51
title:
  rus: О переименовании в городе Сергеевке района Шал акына улицы Лесной в улицу Ермека Конарбаева
  kaz: Шал ақын ауданы Сергеевка қаласының Лесная көшесін Ермек Қоңарбаев атына ауыстыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-09-12
approved_by:
- '165010013001'
version_date:
  kaz: 2007-09-12
  rus: 2007-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/35350/kaz/12.09.2007
  rus: https://zan.gov.kz/client/#!/doc/35350/rus/12.09.2007
