act_code: '49973'
requisite: Решение акима Жамбылского района Северо-Казахстанской области от 10 января 2010 года № 1. Зарегистрировано Управлением юстиции Жамбылского района Северо-Казахстанской области 18 января 2010 года № 13-7-118. Утратило силу в связи с истечением срока действия (письмо аппарата акима Жамбылского района Северо-Казахстанской области от 22 мая 2012 года № 02-05-1.4-2/328
title:
  rus: О проведении приписки граждан к призывному участку отдела по делам обороны Жамбылского района
  kaz: Жамбыл ауданы қорғаныс істері жөніндегі бөлімінің шақыру учаскесіне азаматтарды тіркеуді жүргізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-01-10
approved_by:
- '165007000003'
version_date:
  kaz: 2010-01-10
  rus: 2010-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/49973/kaz/10.01.2010
  rus: https://zan.gov.kz/client/#!/doc/49973/rus/10.01.2010
