act_code: '168026'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 19 мая 2022 года № 4-18 c. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 мая 2022 года № 28161
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2022 год по Уалихановскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы бойынша шетелдіктер үшін 2022 жылға арналған туристік жарна мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-19
approved_by:
- '165013000002'
version_date:
  kaz: 2022-05-19
  rus: 2022-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/168026/kaz/19.05.2022
  rus: https://zan.gov.kz/client/#!/doc/168026/rus/19.05.2022
