act_code: '22157'
requisite: Решение Есильского районного маслихата Северо-Казахстанской области от 17 ноября 2004 года № 78. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 декабря 2004 года № 1411. Утратило силу решением Есильского районного маслихата Северо-Казахстанской области от 10 февраля 2010 года № 25/158
title:
  rus: Правила оказания социальной помощи специалистам государственных организаций здравоохранения, образования, социального обеспечения, культуры и спорта, проживающим и работающим в (аульной) сельской местности на приобретение топлива
  kaz: Селолық (ауылды) жерде тұратын және істейтін денсаулық сақтау, білім беру, әлеуметтік қамтамасыз ету мәдениет және мемлекеттік ұйымдарының мамандарына отын алу үшін әлеуметтік көмек көрсету ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-11-17
approved_by:
- '165006000002'
version_date:
  kaz: 2004-11-17
  rus: 2004-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/22157/kaz/17.11.2004
  rus: https://zan.gov.kz/client/#!/doc/22157/rus/17.11.2004
