act_code: '117112'
requisite: Решение акима Кокалажарского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 13 декабря 2017 года № 12. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 декабря 2017 года № 4455
title:
  rus: О снятии ограничительных мероприятий на территории села Мадениет Кокалажарского сельского округа района имени Габита Мусрепова Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданның Көкалажар ауылдық округі Мәдениет ауылының аумағында шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-13
approved_by:
- '165014007002'
version_date:
  kaz: 2017-12-13
  rus: 2017-12-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/117112/kaz/13.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117112/rus/13.12.2017
