act_code: '138056'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 8 января 2020 года № 35-20. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2020 года № 5818
title:
  rus: Об утверждении бюджета Черкасского сельского округа Аккайынского района на 2020 -2022 годы
  kaz: 2020-2022 жылдарға арналған Аққайың ауданының Черкас ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165005000002'
version_date:
  kaz: 2020-01-08
  rus: 2020-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/138056/kaz/08.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138056/rus/08.01.2020
