act_code: '3123'
requisite: Решение акима Сергеевского района Северо-Казахстанской области от 1 марта 1999 года № 28. Зарегистрировано Управлением юстиции Северо-Казахстанской области 3 мая 1999 года № 74
title:
  rus: Вопросы учреждений-администраторов программ образования, финансируемых из местного бюджета
  kaz: Жергілікті бюджеттен қаржыланатын мекеме-әкімшіліктердің сұрақтары
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-03-01
approved_by:
- '165010000003'
version_date:
  kaz: 1999-03-01
  rus: 1999-03-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/3123/kaz/01.03.1999
  rus: https://zan.gov.kz/client/#!/doc/3123/rus/01.03.1999
