act_code: '196170'
requisite: Решение Тайыншинского районного маслихата Северо-Казахстанской области от 19 апреля 2024 года № 151/13. Зарегистрирован в Департаменте юстиции Северо-Казахстанской области 29 апреля 2024 года № 7750-15
title:
  rus: Об определении размера и Правил оказания жилищной помощи в Тайыншинском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тайынша ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-04-19
approved_by:
- '165011000002'
version_date:
  kaz: 2026-04-29
  rus: 2026-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/196170/kaz/29.04.2026
  rus: https://zan.gov.kz/client/#!/doc/196170/rus/29.04.2026
caused_by:
  code: '225006'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 29 апреля 2026 года № 482/31. Зарегистрировано в Министерстве юстиции Республики Казахстан 30 апреля 2026 года № 38592
  title:
    rus: О внесении изменения в решение маслихата Тайыншинского района Северо-Казахстанской области от 19 апреля 2024 года № 151/13 «Об определении размера и Правил оказания жилищной помощи в Тайыншинском районе Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2024 жылғы 19 сәуірдегі № 151/13 «Солтүстік Қазақстан облысы Тайынша ауданында тұрғын-үй көмегін көрсетудің мөлшері мен қағидаларын айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225006/rus
