act_code: '196170'
requisite: Решение Тайыншинского районного маслихата Северо-Казахстанской области от 19 апреля 2024 года № 151/13. Зарегистрирован в Департаменте юстиции Северо-Казахстанской области 29 апреля 2024 года № 7750-15
title:
  rus: Об определении размера и Правил оказания жилищной помощи в Тайыншинском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тайынша ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидаларын айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-04-19
approved_by:
- '165011000002'
version_date:
  kaz: 2025-05-12
  rus: 2025-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/196170/kaz/12.05.2025
  rus: https://zan.gov.kz/client/#!/doc/196170/rus/12.05.2025
caused_by:
  code: '210091'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 12 мая 2025 года № 318/23. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 14 мая 2025 года № 7924-15
  title:
    rus: О внесении изменений в решение маслихата Тайыншинского района Северо-Казахстанской области от 19 апреля 2024 года № 151/13 «Об определении размера и порядка оказания жилищной помощи в Тайыншинском районе Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2024 жылғы 19 сәуірдегі № 151/13 «Солтүстік Қазақстан облысы Тайынша ауданында тұрғын-үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210091/rus
