act_code: '205224'
requisite: Решение акима Кладбинского сельского округа Жамбылского района Северо-Казахстанской области от 23 декабря 2024 года № 23
title:
  rus: Об определении порядка и условий установления стимулирующей надбавки к должностному окладу работников коммунального государственного учреждения «Аппарат акима Кладбинского сельского округа Жамбылского района Северо-Казахстанской области» финансируемых из местного бюджета
  kaz: Жергілікті бюджеттен қаржыландырылатын "Солтүстік Қазақстан облысы Жамбыл ауданы Кладбинка ауылдық округі әкімінің аппараты" коммуналдық мемлекеттік мекемесі қызметкерлерінің лауазымдық жалақысына ынталандырушы үстемеақыны белгілеудің тәртібі мен шарттарын айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
- УСЛ
approved_on: 2024-12-23
approved_by:
- '165007008002'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/205224/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205224/rus/23.12.2024
