act_code: '817'
requisite: Решение акима Северо-Казахстанской области от 26 марта 1998 года № 67. Зарегистрировано Управлением юстиции Северо-Казахстанской области 15 мая 1998 года № 8. Утратило силу - решением акима Северо-Казахстанской области от 22 апреля 1999 года № 85
title:
  rus: О создании областного управления по миграции и демографии
  kaz: Көшi-қон және демография жөніндегi облыстық басқарма құру туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 1998-03-26
approved_by:
- '165000000003'
version_date:
  kaz: 1998-03-26
  rus: 1998-03-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/817/kaz/26.03.1998
  rus: https://zan.gov.kz/client/#!/doc/817/rus/26.03.1998
