act_code: '146451'
requisite: Решение акима Амангельдинского сельского округа Уалихановского района Северо-Казахстанской области от 17 сентября 2020 года № 9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 18 сентября 2020 года № 6537
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-17
approved_by:
- '165013003002'
version_date:
  kaz: 2020-09-17
  rus: 2020-09-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/146451/kaz/17.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146451/rus/17.09.2020
