act_code: '163648'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2021 года № 8-24
title:
  rus: Об утверждении бюджета сельского округа Шагалалы Аккайынского района на 2022 -2024 годы
  kaz: 2022-2024 жылдарға арналған Аққайың ауданының Шағалалы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '165005000002'
version_date:
  kaz: 2022-11-18
  rus: 2022-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/163648/kaz/18.11.2022
  rus: https://zan.gov.kz/client/#!/doc/163648/rus/18.11.2022
caused_by:
  code: '174678'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 18 ноября 2022 года № 21-12
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2021 года № 8-24 «Об утверждении бюджета сельского округа Шагалалы Аккайынского района на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2021 жылғы 30 желтоқсандағы № 8-24 «2022-2024 жылдарға арналған Аққайың ауданының Шағалалы ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174678/rus
