act_code: '11253'
requisite: Решение Северо-Казахстанского областного маслихата от 22 декабря 2001 года № 14/4. Зарегистрировано управлением юстиции Северо-казахстанской области 23 января 2002 года за № 505. Утратило силу решением Северо-Казахстанского областного маслихата области № 12/7 от 21 декабря 2004 года.
title:
  rus: Об утверждении ставок по отдельным видам платежей
  kaz: Төлемдердің жеке түрлері бойынша мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-12-22
approved_by:
- '165000000002'
version_date:
  kaz: 2001-12-22
  rus: 2001-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/11253/kaz/22.12.2001
  rus: https://zan.gov.kz/client/#!/doc/11253/rus/22.12.2001
