act_code: '152504'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 15 января 2021 года № 7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 25 января 2021 года № 7104. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 13 ноября 2023 года № 87 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Тайыншинском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тайынша ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-15
approved_by:
- '165011000002'
version_date:
  kaz: 2021-08-17
  rus: 2021-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/152504/kaz/17.08.2021
  rus: https://zan.gov.kz/client/#!/doc/152504/rus/17.08.2021
caused_by:
  code: '158242'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 17 августа 2021 года № 78. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 сентября 2021 года № 24194. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 13 ноября 2023 года № 87 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата Тайыншинского района Северо-Казахстанской области от 15 января 2021 года № 7 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Тайыншинского района Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Тайынша ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2021 жылғы 15 қаңтардағы № 7 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158242/rus
