act_code: '76808'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 23 декабря 2013 года № 24/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 января 2014 года № 2486. Утратило силу в связи с истечением срока действия (письмо аппарата маслихата Мамлютского района Северо-Казахстанской области от 29 января 2015 года № 17)
title:
  rus: О районном бюджете на 2014-2016 годы
  kaz: 2014-2016 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-23
approved_by:
- '165009000002'
version_date:
  kaz: 2014-06-26
  rus: 2014-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/76808/kaz/26.06.2014
  rus: https://zan.gov.kz/client/#!/doc/76808/rus/26.06.2014
caused_by:
  code: '81103'
  requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 26 июня 2014 года № 33/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 3 июля 2014 года № 2844. Утратило силу в связи с истечением срока действия (письмо аппарата маслихата Мамлютского района Северо-Казахстанской области от 29 января 2015 года № 17)
  title:
    rus: О внесении изменений и дополнений в решение маслихата Мамлютского района Северо-Казахстанской области от 23 декабря 2013 года № 24/1 "О районном бюджете на 2014-2016 годы"
    kaz: Солтүстік Қазақстан облысы Мамлют ауданы мәслихатының 2013 жылғы 23 желтоқсандағы № 24/1 "2014-2016 жылдарға арналған аудандық бюджет туралы" шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/81103/rus
