act_code: '206106'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 27 декабря 2024 года № 37/7. Утратило силу решением маслихата Мамлютского района Северо-Казахстанской области от 19 мая 2025 года № 42/7 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета Кызыласкерского сельского округа Мамлютского района Северо-Казахстанской области на 2025-2027 годы
  kaz: Солтүстік Қазақстан облысы Мамлют ауданы Қызыләскер ауылдық округінің 2025-2027 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '165009000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206106/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206106/rus/27.12.2024
