act_code: '206086'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 27 декабря 2024 года № 26/11. Утратило силу решением маслихата района Шал акына Северо-Казахстанской области от 8 мая 2025 года № 30/5 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета Аютасского сельского округа района Шал акына на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Шал ақын ауданы Аютас ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '165010000002'
version_date:
  kaz: 2025-02-28
  rus: 2025-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/206086/kaz/28.02.2025
  rus: https://zan.gov.kz/client/#!/doc/206086/rus/28.02.2025
caused_by:
  code: '207751'
  requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 28 февраля 2025 года № 28/7. Утратило силу решением маслихата района Шал акына Северо-Казахстанской области от 8 мая 2025 года № 30/5 (вводится в действие с 1 января 2025 года)
  title:
    rus: О внесении изменений в решение маслихата района Шал акына Северо-Казахстанской области от 27 декабря 2024 года № 26/11 «Об утверждении бюджета Аютасского сельского округа района Шал акына на 2025-2027 годы»
    kaz: Солтүстік Қазақстан облысы Шал ақын ауданы мәслихатының 2024 жылғы 27 желтоқсандағы № 26/11 «2025-2027 жылдарға арналған Шал ақын ауданы Аютас ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207751/rus
