act_code: '59272'
requisite: Решение Жамбылского районного маслихата Северо-Казахстанской области от 23 мая 2011 года № 33/5. Зарегистрировано Управлением юстиции Жамбылского района Северо-Казахстанской области 13 июня 2011 года № 13-7-150. Утратило силу - решением Жамбылского районного маслихата Северо-Казахстанской области от 28 марта 2013 года № 13/6
title:
  rus: Об установлении стоимости разовых талонов, для лиц осуществляющих деятельность эпизодического характера по Жамбылскому району
  kaz: Жамбыл ауданы бойынша эпизодиялық қызметін жүзеге асыратын тұлғаларға бір реттік талондардың кұнын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-05-23
approved_by:
- '165007000002'
version_date:
  kaz: 2011-07-28
  rus: 2011-07-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/59272/kaz/28.07.2011
  rus: https://zan.gov.kz/client/#!/doc/59272/rus/28.07.2011
caused_by:
  code: '60347'
  requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 28 июля 2011 года № 34/5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 1 сентября 2011 года № 13-7-155. Утратило силу - решением Жамбылского районного маслихата Северо-Казахстанской области от 28 марта 2013 года № 13/6
  title:
    rus: О внесении изменений в решение Жамбылского районного маслихата от 23 мая 2011 года № 33/5 "Об установлении стоимости разовых талонов для лиц, осуществляющих деятельность эпизодического характера по Жамбылскому району"
    kaz: '"Жамбыл ауданы бойынша эпизодтық қызметін жүзеге асыратын тұлғаларға бір реттік талондардың құнын бекіту туралы" Жамбыл аудандық мәслихаттың 2011 жылғы 23 мамырдағы № 33/5 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/60347/rus
