act_code: '77033'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 20 декабря 2013 года № 25/149. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 января 2014 года № 2507
title:
  rus: О льготном проезде на общественном транспорте (кроме такси) обучающихся и воспитанников всех организаций образования очной формы обучения в 2014 году
  kaz: Барлық білім беру ұйымдарының күндізгі оқу нысаны бойынша білім алушылары мен тәрбиеленушілеріне 2014 жылы қоғамдық көлікте (таксиден басқа) жеңілдікпен жол жүрулері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-20
approved_by:
- '165006000002'
version_date:
  kaz: 2013-12-20
  rus: 2013-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/77033/kaz/20.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77033/rus/20.12.2013
