act_code: '140856'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 19 марта 2020 года № 37-4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 марта 2020 года № 6137. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 октября  2023 года № 7-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан района Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-03-19
approved_by:
- '165015000002'
version_date:
  kaz: 2020-06-12
  rus: 2020-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/140856/kaz/12.06.2020
  rus: https://zan.gov.kz/client/#!/doc/140856/rus/12.06.2020
caused_by:
  code: '144036'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 12 июня 2020 года № 39-6. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 23 июня 2020 года № 6386. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 октября  2023 года № 7-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 19 марта 2020 года № 37-4 «Об утверждении Правил оказания социальной помощи, размеров и определения перечня отдельных категорий нуждающихся граждан района Магжана Жумабаева Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2020 жылғы 19 наурыздағы № 37-4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144036/rus
