act_code: '77075'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 23 декабря 2013 года № 21-4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 января 2014 года № 2516. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 15 февраля 2019 года № 27-2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания жилищной помощи малообеспеченным семьям (гражданам), проживающим на территории района Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы аумағында тұратын аз қамтамасыз етілген отбасыларға (азаматтарға) тұрғын үй көмегін көрсету қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2013-12-23
approved_by:
- '165015000002'
version_date:
  kaz: 2013-12-23
  rus: 2013-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/77075/kaz/23.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77075/rus/23.12.2013
