act_code: '53933'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 24 июня 2010 года № 24-6. Зарегистрировано Управлением юстиции Акжарского района Северо-Казахстанской области 6 августа 2010 года № 13-4-105. Утратило силу решением Акжарского районного маслихата Северо-Казахстанской области от 18 июня 2018 года № 28-4
title:
  rus: О ставках земельного налога
  kaz: Жер салығы ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-24
approved_by:
- '165004000002'
version_date:
  kaz: 2010-06-24
  rus: 2010-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/53933/kaz/24.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53933/rus/24.06.2010
