act_code: '158468'
requisite: Решение акима Асановского сельского округа Кызылжарского района Северо-Казахстанской области от 3 сентября 2021 года № 33. Зарегистрировано в Министерстве юстиции Республики Казахстан 10 сентября 2021 года № 24294. Утратил силу решением акима Асановского сельского округа Кызылжарского района Северо-Казахстанской области от 4 ноября 2021 года № 44 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-09-03
approved_by:
- '165008002002'
version_date:
  kaz: 2021-09-03
  rus: 2021-09-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/158468/kaz/03.09.2021
  rus: https://zan.gov.kz/client/#!/doc/158468/rus/03.09.2021
