act_code: '144928'
requisite: Решение акима Жанажолского сельского округа района Шал акына Северо-Казахстанской области от 15 июля 2020 года № 4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 17 июля 2020 года № 6452. Утратил силу решением акима Жанажолского сельского округа района Шал акына Северо-Казахстанской области от 29 ноября 2021 года № 10 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-07-15
approved_by:
- '165010004002'
version_date:
  kaz: 2020-07-15
  rus: 2020-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/144928/kaz/15.07.2020
  rus: https://zan.gov.kz/client/#!/doc/144928/rus/15.07.2020
