act_code: '206345'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 27 декабря 2024 года № 268/20. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 8 мая 2025 года № 306/23 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета Яснополянского сельского округа Тайыншинского района Северо-Казахстанской области на 2025-2027 годы
  kaz: Солтүстік Қазақстан облысы Тайынша ауданы Яснополян ауылдық округінің 2025-2027 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '165011000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/206345/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206345/rus/27.12.2024
