act_code: '163364'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2021 года № 10-18
title:
  rus: Об утверждении бюджета сельского округа Магжан района Магжана Жумабаева на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Мағжан Жұмабаев ауданы Мағжан ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '165015000002'
version_date:
  kaz: 2022-08-23
  rus: 2022-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/163364/kaz/23.08.2022
  rus: https://zan.gov.kz/client/#!/doc/163364/rus/23.08.2022
caused_by:
  code: '171438'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 23 августа 2022 года № 17-12
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2021 года № 10-18 «Об утверждении бюджета сельского округа Магжан района Магжана Жумабаева на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2021 жылғы 30 желтоқсандағы № 10-18 «2022-2024 жылдарға арналған Мағжан Жұмабаев ауданы Мағжан ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171438/rus
