act_code: '70093'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 20 декабря 2012 года № 8-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 января 2013 года № 2056
title:
  rus: О бюджете Акжарского района на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған Ақжар аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '165004000002'
version_date:
  rus: 2013-10-09
source:
  rus: https://zan.gov.kz/client/#!/doc/70093/rus/09.10.2013
caused_by:
  code: '74454'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 9 сентября 2013 года № 14-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 сентября 2013 года № 2363
  title:
    rus: О внесении изменений и дополнений в решение Акжарского районного маслихата Северо-Казахстанской области от 20 декабря 2012 года № 8-1 "О бюджете Акжарского района на 2013-2015 годы"
    kaz: '"2013-2015 жылдарға арналған Ақжар аудандық бюджет туралы" Солтүстік Қазақстан облысының Ақжар аудандық мәслихатының 2012 жылғы 20 желтоқсандағы № 8-1 шешіміне өзгертулер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/74454/rus
