act_code: '70093'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 20 декабря 2012 года № 8-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 января 2013 года № 2056
title:
  rus: О бюджете Акжарского района на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған Ақжар аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '165004000002'
version_date:
  kaz: 2013-09-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/70093/kaz/09.09.2013
