act_code: '168040'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 13 мая 2022 года № 191. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 мая 2022 года № 28166
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Тайыншинскому району Северо-Казахстанской области на 2022 год
  kaz: 2022 жылға арналған Солтүстік Қазақстан облысы Тайынша ауданы бойынша кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-05-13
approved_by:
- '165011000002'
version_date:
  kaz: 2022-05-13
  rus: 2022-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/168040/kaz/13.05.2022
  rus: https://zan.gov.kz/client/#!/doc/168040/rus/13.05.2022
