act_code: '129348'
requisite: Решение акима Коктерекского сельского округа Уалихановского района Северо-Казахстанской области от 27 февраля 2019 года № 9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 февраля 2019 года № 5239
title:
  rus: О снятии ограничительных мероприятий по бруцеллезу крупного рогатого скота находящегося на территории села Мортык Коктерекского сельского округа Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Көктерек ауылдық округі Мортық ауылының аумағында орналасқан ірі қара мал бруцеллезіне шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-02-27
approved_by:
- '165013009002'
version_date:
  kaz: 2019-02-27
  rus: 2019-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/129348/kaz/27.02.2019
  rus: https://zan.gov.kz/client/#!/doc/129348/rus/27.02.2019
