act_code: '85259'
requisite: Решение акима Тимирязевского района Северо-Казахстанской области от 26 ноября 2014 года № 33. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 23 декабря 2014 года № 3020
title:
  rus: Об организации и обеспечении на территории Тимирязевского района Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2015 года
  kaz: Қазақстан Республикасының ер азаматтарын 2015 жылғы қаңтардан бастап наурызға дейін Солтүстік Қазақстан облысы Тимирязев ауданының аумағында тіркеу және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-26
approved_by:
- '165012000001'
version_date:
  kaz: 2014-11-26
  rus: 2014-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/85259/kaz/26.11.2014
  rus: https://zan.gov.kz/client/#!/doc/85259/rus/26.11.2014
