act_code: '78686'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 28 февраля 2014 года № 4-21с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 апреля 2014 года № 2660. Утратил силу решением Уалихановского районного маслихата Северо-Казахстанской области от 24 декабря 2021 года № 8-13 с (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей улиц села Бидайык и сел Бидайыкского сельского округа Уалихановского района Северо-Казахстанской области для участия в сходе местного сообщества
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Бидайық ауылдық округінің ауылдары және Бидайық ауылы көшелері тұрғындарының жергілікті қоғамдастық жиынына қатысу үшін бөлек жергілікті қоғамдастық жиындарын өткізу қағидасын және тұрғындар өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-28
approved_by:
- '165013000002'
version_date:
  kaz: 2014-02-28
  rus: 2014-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/78686/kaz/28.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78686/rus/28.02.2014
