act_code: '188417'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 15 ноября 2023 года № 13-10 с. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 16 ноября 2023 года № 7623-15
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-15
approved_by:
- '165013000002'
version_date:
  kaz: 2024-03-19
  rus: 2024-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/188417/kaz/19.03.2024
  rus: https://zan.gov.kz/client/#!/doc/188417/rus/19.03.2024
caused_by:
  code: '194623'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 19 марта 2024 года № 5-16 с. Зарегистрирован в Департаменте юстиции Северо-Казахстанской области 20 марта 2024 года № 7720-15
  title:
    rus: О внесении изменений в решение Уалихановского районного маслихата Северо-Казахстанской области от 15 ноября 2023 года № 13-10с «Об утверждении правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Уалихановского района Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2023 жылғы 15 қарашадағы № 13-10с «Солтүстік Қазақстан облысы Уәлиханов ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194623/rus
