act_code: '53696'
requisite: Решение акима Володарского сельского округа Айыртауского района Северо-Казахстанской области от 29 июня 2010 года № 24. Зарегистрировано Управлением юстиции Айыртауского района Северо-Казахстанской области 28 июля 2010 года № 13-3-121
title:
  rus: О переименовании улицы Озерная села Саумалколь Айыртауского района Северо-Казахстанской области на улицу Сыздыкова Даулетбая Сыздыковича села Саумалколь Айыртауского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданы Саумалколь селосының Озерная көшесінің атауын Солтүстік Қазақстан облысы Айыртау ауданы Саумалколь селосының Сыздықов Дәулетбай Сыздықұлы көшесіне өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-29
approved_by:
- '165003003001'
version_date:
  kaz: 2010-06-29
  rus: 2010-06-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/53696/kaz/29.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53696/rus/29.06.2010
