act_code: '2851'
requisite: Решение акима Северо-Казахстанской области от 7 октября 1998 года № 207. Зарегистрировано Управлением юстиции Северо-Казахстанской области 18 декабря 1998 года за № 46
title:
  rus: О ходе выполнения Постановления Правительства РК от 24 декабря 1996 года № 1598 «О дополнительных мерах по укреплению общественного порядка и повышению роли участковых уполномоченных органов внутренних дел в предупреждении и профилактике правонарушений»
  kaz: Қазақстан Республикасы Үкіметінің "Қоғамдық тәрттіпті нығайту және құқық бұзушылықты болдырмау жене оның алдын алудағы ішкі істер органдарының учаскелік уәкілдерінің ролін көтеру жөніндегі қосымша шаралар туралы" І99б ж. 24 желтоқсандағы № 1598 қаулысын орындау барысы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-10-06
approved_by:
- '165000000003'
version_date:
  kaz: 1998-10-06
  rus: 1998-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/2851/kaz/06.10.1998
  rus: https://zan.gov.kz/client/#!/doc/2851/rus/06.10.1998
