act_code: '75910'
requisite: Решение акима района Шал акына Северо-Казахстанской области от 3 декабря 2013 года № 21. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 декабря 2013 года № 2432. Утратило силу в связи с истечением срока действия (письмо акима района Шал акына Северо-Казахстанской области от 12 июня 2015 года № 15.1.5-11/314)
title:
  rus: Об организации и обеспечении на территории района Шал акына Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2014 года
  kaz: Солтүстік Қазақстан облысы Шал ақын ауданының аумағында 2014 жылғы қаңтар-наурыз аралығында Қазақстан Республикасы ер азаматтарының тіркелуін және медициналық куәландыруын ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-03
approved_by:
- '165010000003'
version_date:
  kaz: 2013-12-03
  rus: 2013-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/75910/kaz/03.12.2013
  rus: https://zan.gov.kz/client/#!/doc/75910/rus/03.12.2013
