act_code: '162796'
requisite: Решение акима Новоишимского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 27 декабря 2021 года № 256. Зарегистрировано в Министерстве юстиции Республики Казахстан 31 декабря 2021 года № 26294
title:
  rus: О переименовании улицы Чапаева села Новоишимское Новоишимского сельского округа района имени Габита Мусрепова Северо - Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданының Новоишим ауылдық округінің Новоишим ауылының Чапаев көшесі атауын қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-27
approved_by:
- '165014001002'
version_date:
  kaz: 2021-12-27
  rus: 2021-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/162796/kaz/27.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162796/rus/27.12.2021
