act_code: '138139'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 8 января 2020 года № 56-15. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2020 года № 5834
title:
  rus: Об утверждении бюджета Чистопольского сельского округа района имени Габита Мусрепова на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Чистопол ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165014000002'
version_date:
  kaz: 2020-01-08
  rus: 2020-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/138139/kaz/08.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138139/rus/08.01.2020
