act_code: '156990'
requisite: Решение акима Конюховского сельского округа района Магжана Жумабаева Северо-Казахстанской области от 7 июля 2021 года № 9. Зарегистрирован в Министерстве юстиции Республики Казахстан 14 июля 2021 года № 23519
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын алу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-07-07
approved_by:
- '165015010002'
version_date:
  kaz: 2021-07-07
  rus: 2021-07-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/156990/kaz/07.07.2021
  rus: https://zan.gov.kz/client/#!/doc/156990/rus/07.07.2021
