act_code: '33866'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2007 жылғы 24 мамырдағы № 7-32 с шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2007 жылғы 27 маусымда № 13-13-51 болып тіркелді
title:
  rus: Үй жануарлары мен құстарды ұстаудың Ережелері туралы
  kaz: Үй жануарлары мен құстарды ұстаудың Ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-05-24
approved_by:
- '165013000002'
version_date:
  kaz: 2007-05-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/33866/kaz/24.05.2007
