act_code: '138555'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 6 января 2020 года № 35-4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 января 2020 года № 5960
title:
  rus: Об утверждении бюджета сельского округа Бәйтерек района Магжана Жумабаева на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Мағжан Жұмабаев ауданы Бәйтерек ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-06
approved_by:
- '165015000002'
version_date:
  kaz: 2020-11-16
  rus: 2020-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/138555/kaz/16.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138555/rus/16.11.2020
caused_by:
  code: '148679'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 16 ноября 2020 года № 43-4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 ноября 2020 года № 6678
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 6 января 2020 года № 35-4 «Об утверждении бюджета сельского округа Бәйтерек района Магжана Жумабаева на 2020-2022 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2020 жылғы 6 қаңтардағы № 35-4 «2020-2022 жылдарға арналған Мағжан Жұмабаев ауданы Бәйтерек ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/148679/rus
