act_code: '75746'
requisite: Решение Северо-Казахстанского областного маслихата от 26 ноября 2013 года № 22/9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 декабря 2013 года № 2418. Утратило силу (письмо маслихата Северо-Казахстанской области от 06.01.2015 № 2.1-11/05)
title:
  rus: Об утверждении ставок платы за лесные пользования на участках государственного лесного фонда и особо охраняемых природных территориях и норм сбора физическими лицами для собственных нужд побочных лесных ресурсов на территории государственного лесного фонда Северо-Казахстанской области на 2013-2014 годы
  kaz: 2013-2014 жылдарға арналған Солтүстік Қазақстан облысының мемлекеттік орман қоры учаскелерінде және ерекше қорғалатын табиғи аумақтарында орман пайдалану үшін төлем ставкаларын және мемлекеттік орман қоры учаскелерінде өз қажеттіліктері үшін жеке тұлғалардың жанама орман ресурстарын жинау нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-11-26
approved_by:
- '165000000002'
version_date:
  kaz: 2013-11-26
  rus: 2013-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/75746/kaz/26.11.2013
  rus: https://zan.gov.kz/client/#!/doc/75746/rus/26.11.2013
