act_code: '76973'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 20 декабря 2013 года № 25/148. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 января 2014 года № 2501. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 3 июля 2014 года № 33/206
title:
  rus: О предоставлении в 2014 году подъемного пособия и бюджетного кредита для приобретения или строительства жилья специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Есильского района
  kaz: Есіл ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына тұрғын үй сатып алу немесе салу үшін 2014 жылы көтерме жәрдемақы мен бюджеттік несие беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-20
approved_by:
- '165006000002'
version_date:
  kaz: 2013-12-20
  rus: 2013-12-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/76973/kaz/20.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76973/rus/20.12.2013
