act_code: '85944'
requisite: Решение маслихата Уалихановского района Северо-Казахстанской области от 26 декабря 2014 года № 2-29с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2015 года № 3052
title:
  rus: О районном бюджете Уалихановского района на 2015 -2017 годы
  kaz: 2015-2017 жылдарға арналған Уәлиханов ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-26
approved_by:
- '165013000002'
version_date:
  kaz: 2015-03-30
  rus: 2015-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/85944/kaz/30.03.2015
  rus: https://zan.gov.kz/client/#!/doc/85944/rus/30.03.2015
caused_by:
  code: '89176'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 30 марта 2015 года № 2-31с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 апреля 2015 года № 3198
  title:
    rus: О внесении изменений и дополнений в решение Уалихановского районного маслихата от 26 декабря 2014 года № 2-29 с «О районном бюджете на 2015-2017 годы»
    kaz: «2015-2017 жылдарға арналған аудандық бюджет туралы» Уәлиханов аудандық мәслихатының 2014 жылғы 26 желтоқсандағы № 2-29 с шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/89176/rus
