act_code: '127895'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 28 декабря 2018 года № 6-26-11. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 3 января 2019 года № 5129
title:
  rus: Об утверждении бюджета Камсактинского сельского округа Айыртауского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Айыртау ауданы Қамсақты ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '165003000002'
version_date:
  kaz: 2018-12-28
  rus: 2018-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/127895/kaz/28.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127895/rus/28.12.2018
