act_code: '1059'
requisite: Решение акима Северо-Казахстанской области от 16 июля 1998 года № 160. Зарегистрировано Управлением юстиции Северо-Казахстанской области 28 июля 1998 года за № 33. Утратило силу решением акима Северо-Казахстанской области от 28 октября 2004 года № 36
title:
  rus: Об упорядочении торговли и оборота алкогольной продукции на территории области
  kaz: Облыс аумағындағы алкогольдік өнімдер саудасы мен айналымын тәртіпке келтіру жөнінде
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-07-15
approved_by:
- '165000000003'
version_date:
  kaz: 1998-07-15
  rus: 1998-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/1059/kaz/15.07.1998
  rus: https://zan.gov.kz/client/#!/doc/1059/rus/15.07.1998
