act_code: '61715'
requisite: Решение акима района имени Габита Мусрепова Северо-Казахстанской области от 22 ноября 2011 года № 31. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 2 декабря 2011 года № 13-5-136. Утратило силу решением акима района имени Габита Мусрепова Северо-Казахстанской области от 25 февраля 2015 года № 5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков по району имени Габита Мусрепова Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы аудан бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-22
approved_by:
- '165014000003'
version_date:
  kaz: 2014-01-21
  rus: 2014-01-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/61715/kaz/21.01.2014
  rus: https://zan.gov.kz/client/#!/doc/61715/rus/21.01.2014
caused_by:
  code: '77465'
  requisite: Решение акима района имени Габита Мусрепова Северо-Казахстанской области от 21 января 2014 года № 1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 февраля 2014 года № 2556. Утратило силу решением акима района имени Габита Мусрепова Северо-Казахстанской области от 25 февраля 2015 года № 5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима района имени Габита Мусрепова  Северо-Казахстанской области от 22 ноября 2011 года № 31 "Об образовании избирательных участков по району имени Габита Мусрепова Северо-Казахстанской области"
    kaz: '"Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы аудан бойынша сайлау  учаскелерін құру туралы" Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы аудан әкімінің 2011 жылғы 22 қарашадағы № 31 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/77465/rus
