act_code: '144107'
requisite: Решение акима Бидайыкского сельского округа Уалихановского района Северо-Казахстанской области от 24 июня 2020 года № 18. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 25 июня 2020 года № 6390. Утратило силу решением акима Бидайыкского сельского округа Уалихановского района Северо-Казахстанской области от 10 декабря 2020 года № 39 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-06-24
approved_by:
- '165013004002'
version_date:
  kaz: 2020-06-24
  rus: 2020-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/144107/kaz/24.06.2020
  rus: https://zan.gov.kz/client/#!/doc/144107/rus/24.06.2020
