act_code: '138249'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 8 января 2020 года № 56-10. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2020 года № 5896
title:
  rus: Об утверждении бюджета Новоишимского сельского округа района имени Габита Мусрепова на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Новоишим ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165014000002'
version_date:
  kaz: 2020-08-26
  rus: 2020-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/138249/kaz/26.08.2020
  rus: https://zan.gov.kz/client/#!/doc/138249/rus/26.08.2020
caused_by:
  code: '145869'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 26 августа 2020 года № 65-4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 августа 2020 года № 6515
  title:
    rus: О внесении изменений в решение маслихата района имени Габита Мусрепова от 8 января 2020 года № 56-10 «Об утверждении бюджета Новоишимского сельского округа района имени Габита Мусрепова на 2020-2022 годы»
    kaz: Ғабит Мүсірепов атындағы ауданы мәслихатының 2020 жылғы 8 қаңтардағы № 56-10 «2020-2022 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Новоишим ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/145869/rus
