act_code: '194147'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 29 февраля 2024 года № 14-14. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 6 марта 2024 года № 7705-15
title:
  rus: Об определении размера и правил оказания жилищной помощи в Аккайынском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-02-29
approved_by:
- '165005000002'
version_date:
  kaz: 2025-12-03
  rus: 2025-12-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/194147/kaz/03.12.2025
  rus: https://zan.gov.kz/client/#!/doc/194147/rus/03.12.2025
caused_by:
  code: '218518'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 3 декабря 2025 года № 30-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 8 декабря 2025 года № 37549
  title:
    rus: О внесении изменений и дополнения в решение маслихата Аккайынского района Северо-Казахстанской области от 29 февраля 2024 года № 14-14 «Об определении размера и порядка оказания жилищной помощи в Аккайынском районе Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2024 жылғы 29 ақпандағы № 14-14 «Солтүстік Қазақстан облысының Аққайың ауданында тұрғын үй көмегінің мөлшерін және оны көрсетудің тәртібін айқындау туралы» шешіміне өзгерістер мен толықтыру енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/218518/rus
