act_code: '189603'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 29 ноября 2023 года № 9/2
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей жителей села, сельского округа, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Жамбылском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, ауылдық округ, көшелер, көппәтерлі тұрғын үйлер тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-29
approved_by:
- '165007000002'
version_date:
  kaz: 2024-07-17
  rus: 2024-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/189603/kaz/17.07.2024
  rus: https://zan.gov.kz/client/#!/doc/189603/rus/17.07.2024
caused_by:
  code: '198896'
  requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 17 июля 2024 года № 20/5
  title:
    rus: О внесении изменений в решение маслихата Жамбылского района Северо-Казахстанской области от 29 ноября 2023 года № 9/2 «Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей жителей села, сельского округа, улицы, многоквартирного жилого дома для участия в сходе местного сообщества в Жамбылском районе Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Жамбыл ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, ауылдық округ, көшелер, көппәтерлі тұрғын үйлер тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы» Солтүстік Қазақстан облысы Жамбыл ауданы мәслихатының 2023 жылғы 29 қарашадағы № 9/2 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198896/rus
