act_code: '151745'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 6 января 2021 года № 72-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 января 2021 года № 6920
title:
  rus: Об утверждении бюджета Чистопольского сельского округа района имени Габита Мусрепова на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Чистопол ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-06
approved_by:
- '165014000002'
version_date:
  kaz: 2021-12-06
  rus: 2021-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/151745/kaz/06.12.2021
  rus: https://zan.gov.kz/client/#!/doc/151745/rus/06.12.2021
caused_by:
  code: '161504'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 6 декабря 2021 года № 12-15
  title:
    rus: О внесении изменений в решение маслихата района имени Габита Мусрепова от 6 января 2021 года № 72-1 «Об утверждении бюджета Чистопольского сельского округа района имени Габита Мусрепова на 2021-2023 годы
    kaz: Ғабит Мүсірепов атындағы ауданы мәслихатының 2021 жылғы 6 қаңтардағы № 72-1 «2021-2023 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Чистопол ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/161504/rus
