act_code: '158519'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 26 августа 2021 года № 8-19. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 сентября 2021 года № 24327
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в районе Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-08-26
approved_by:
- '165015000002'
version_date:
  kaz: 2022-10-07
  rus: 2022-10-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/158519/kaz/07.10.2022
  rus: https://zan.gov.kz/client/#!/doc/158519/rus/07.10.2022
caused_by:
  code: '172936'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 7 октября 2022 года № 19-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 17 октября 2022 года № 30189
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 26 августа 2021 года № 8-19 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в районе Магжана Жумабаева»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2021 жылғы 26 тамыздағы № 8-19 «Мағжан Жұмабаев ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172936/rus
