act_code: '127932'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 25 декабря 2018 года № 35-4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 декабря 2018 года № 5124
title:
  rus: Об утверждении бюджета Акжарского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ақжар аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-25
approved_by:
- '165004000002'
version_date:
  kaz: 2019-10-28
  rus: 2019-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/127932/kaz/28.10.2019
  rus: https://zan.gov.kz/client/#!/doc/127932/rus/28.10.2019
caused_by:
  code: '135685'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 28 октября 2019 года № 47-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 октября 2019 года № 5631
  title:
    rus: О внесении изменений в решение Акжарского районного маслихата от 25 декабря 2018 года № 35-4 «Об утверждении бюджета Акжарского района на 2019-2021 годы»
    kaz: Ақжар аудандық мәслихатының 2018 жылғы 25 желтоқсандағы № 35-4 «2019-2021 жылдарға арналған Ақжар аудандық бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/135685/rus
