act_code: '44724'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 1 февраля 2009 года № 14-2. Зарегистрировано Управлением юстиции района Магжана Жумабаева Северо-Казахстанской области 12 марта 2009 года № 13-9-87. Утратило силу - решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 27 июня 2013 года № 12-2
title:
  rus: Об установлении единых ставок фиксированного налога
  kaz: Бірыңғай тіркелген салық ставкаларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-02-01
approved_by:
- '165015000002'
version_date:
  kaz: 2009-02-01
  rus: 2009-02-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/44724/kaz/01.02.2009
  rus: https://zan.gov.kz/client/#!/doc/44724/rus/01.02.2009
