act_code: '49644'
requisite: Решение акима района имени Габита Мусрепова Северо-Казахстанской области от 28 декабря 2009 года № 19. Зарегистрировано Управлением юстиции района имени Габита Мусрепова Северо-Казахстанской области 6 января 2010 года № 13-5-105. Утратило силу - решением акима района имени Габита Мусрепова Северо-Казахстанской области от 26 ноября 2010 года № 24
title:
  rus: О проведении приписки граждан Республики Казахстан мужского пола 1993 года рождения к призывному участку отдела по делам обороны района имени Габита Мусрепова
  kaz: Қазақстан Республикасының 1993 жылы туылған ер азаматтарын Ғабит Мүсірепов атындағы ауданның Қорғаныс істері жөніндегі бөлімінің әскерге шақырушылар учаскесіне тіркеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-28
approved_by:
- '165014000003'
version_date:
  kaz: 2009-12-28
  rus: 2009-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/49644/kaz/28.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49644/rus/28.12.2009
