act_code: '210416'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 8 мая 2025 года № 27/423
title:
  rus: Об утверждении бюджета Корнеевского сельского округа Есильского района Северо-Казахстанской области на 2025-2027 годы
  kaz: Солтүстік Қазақстан облысы Есіл ауданы Корнеевка ауылдық округінің 2025-2027 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-08
approved_by:
- '165006000002'
version_date:
  kaz: 2025-09-04
  rus: 2025-09-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/210416/kaz/04.09.2025
  rus: https://zan.gov.kz/client/#!/doc/210416/rus/04.09.2025
caused_by:
  code: '214088'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 4 сентября 2025 года № 32/480
  title:
    rus: О внесении изменений в решение маслихата Есильского района от 8 мая 2025 года № 27/423 «Об утверждении бюджета Корнеевского сельского округа Есильского района Северо-Казахстанской области на 2025-2027 годы»
    kaz: «Солтүстік Қазақстан облысы Есіл ауданы Корнеевка ауылдық округінің 2025-2027 жылдарға арналған бюджетін бекіту туралы» Солтүстік Қазақстан облысы Есіл ауданы мәслихатының 2025 жылғы 8 мамырдағы № 27/423 шешіміне  өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214088/rus
