act_code: '51571'
requisite: Решение маслихата города Петропавловска Северо-Казахстанской области от 12 марта 2010 года № 2. Зарегистрировано Управлением юстиции города Петропавловска Северо-Казахстанской области 7 апреля 2010 года № 13-1-174. Утратило силу - решением маслихата города Петропавловска Северо-Казахстанской области от 3 августа 2012 года № 4
title:
  rus: Об оказании социальной помощи отдельным категориям нуждающихся граждан города Петропавловска
  kaz: Петропавл қаласы азаматтарының жекелеген санаттарына әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-12
approved_by:
- '165002000002'
version_date:
  kaz: 2011-04-20
  rus: 2011-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/51571/kaz/20.04.2011
  rus: https://zan.gov.kz/client/#!/doc/51571/rus/20.04.2011
caused_by:
  code: '58779'
  requisite: Решение маслихата города Петропавловска Северо-Казахстанской области от 20 апреля 2011 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 мая 2011 года № 13-1-196. Утратило силу решением маслихата города Петропавловска Северо-Казахстанской области от 17 октября 2013 года № 13
  title:
    rus: О внесении дополнения в решение внеочередной 25 сессии Петропавловского городского маслихата от 12 марта 2010 года № 2 "Об оказании социальной помощи отдельным категориям нуждающихся граждан города Петропавловска"
    kaz: '"Петропавл қаласы азаматтарының жекелеген санаттарына әлеуметтік көмек көрсету туралы" Петропавл қалалық мәслихатының 2010 жылғы 12 наурыздағы кезектен тыс 25 сессиясының № 2 шешіміне толықтыру енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/58779/rus
