act_code: '195441'
requisite: Решение Северо-Казахстанского областного маслихата от 29 марта 2024 года № 12/5. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 3 апреля 2024 года № 7740-15
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников по Северо-Казахстанской области на 2024 год
  kaz: Солтүстік Қазақстан облысы бойынша 2024 жылға арналған жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-29
approved_by:
- '165000000002'
version_date:
  kaz: 2024-03-29
  rus: 2024-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/195441/kaz/29.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195441/rus/29.03.2024
