act_code: '48912'
requisite: Решение маслихата района имени Магжана Жумабаева Северо-Казахстанской области от 20 октября 2009 года № 18-2. Зарегистрировано Управлением юстиции района имени Магжана Жумабаева Северо-Казахстанской области 1 декабря 2009 года № 13-9-107. Утратило силу (письмо маслихата района Магжана Жумабаева Северо-Казахстанской области от 09 января 2013 года № 01-15/5)
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры и спорта, проживающим и работающим в сельских населенных пунктах района Магжана Жумабаева
  kaz: Мағжан Жұмабаев ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін денсаулық сақтау, білім, әлеуметтік қамсыздандыру, мәдениет және спорт мемлекеттік ұйымдарының мамандарына отын алу үшін әлеуметтік көмек туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-10-20
approved_by:
- '165015000002'
version_date:
  kaz: 2009-10-20
  rus: 2009-10-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/48912/kaz/20.10.2009
  rus: https://zan.gov.kz/client/#!/doc/48912/rus/20.10.2009
