act_code: '154759'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 1 апреля 2021 года № 3-28. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 6 апреля 2021 года № 7242. Утратил силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 26 августа 2021 года № 8-19 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану
  kaz: Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібін және мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-01
approved_by:
- '165015000002'
version_date:
  kaz: 2021-04-01
  rus: 2021-04-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/154759/kaz/01.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154759/rus/01.04.2021
