act_code: '163326'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2021 года № 10-14
title:
  rus: Об утверждении бюджета Возвышенского сельского округа района Магжана Жумабаева на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Мағжан Жұмабаев ауданы Возвышен ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '165015000002'
version_date:
  kaz: 2022-10-10
  rus: 2022-10-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/163326/kaz/10.10.2022
  rus: https://zan.gov.kz/client/#!/doc/163326/rus/10.10.2022
caused_by:
  code: '172839'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 10 октября 2022 года № 19-6
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2021 года № 10-14 «Об утверждении бюджета Возвышенского сельского округа района Магжана Жумабаева на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2021 жылғы 30 желтоқсандағы № 10-14 «2022-2024 жылдарға арналған Мағжан Жұмабаев ауданы Возвышен ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/172839/rus
