act_code: '55205'
requisite: Решение акима Кривощековского сельского округа района Шал акына Северо-Казахстанской области от 14 октября 2010 года № 10. Зарегистрировано Управлением юстиции района Шал акына Северо-Казахстанской области 28 октября 2010 года № 13-14-117
title:
  rus: О присвоении наименований составным частям населенных пунктов Кривощековского сельского округа района Шал акына
  kaz: Шал ақын ауданы Кривощеков ауылдық округінің елді мекендерінің құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-10-14
approved_by:
- '165010005002'
version_date:
  kaz: 2010-10-14
  rus: 2010-10-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/55205/kaz/14.10.2010
  rus: https://zan.gov.kz/client/#!/doc/55205/rus/14.10.2010
