act_code: '177241'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2022 года № 21-28
title:
  rus: Об утверждении бюджета Тамановского сельского округа района Магжана Жумабаева на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Мағжан Жұмабаев ауданы Таман ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '165015000002'
version_date:
  kaz: 2023-07-25
  rus: 2023-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/177241/kaz/25.07.2023
  rus: https://zan.gov.kz/client/#!/doc/177241/rus/25.07.2023
caused_by:
  code: '184339'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 25 июля 2023 года № 5-19
  title:
    rus: О внесении изменений и дополнения в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2022 года № 21-28 «Об утверждении бюджета Тамановского сельского округа района Магжана Жумабаева на 2023-2025 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2022 жылғы 30 желтоқсандағы № 21-28 «2023-2025 жылдарға арналған Мағжан Жұмабаев ауданы Таман ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184339/rus
