act_code: '102487'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 25 апреля 2016 года № 4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 16 мая 2016 года № 3744. Утратило силу решением Петропавловского городского маслихата Северо-Казахстанской области от 14 сентября 2020 года № 1 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении дополнительного порядка проведения собраний, митингов, шествий, пикетов и демонстраций
  kaz: Бейбiт жиналыстар, митингiлер, шерулер, пикеттер және демонстрациялар өткізудің қосымша тәртібін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-04-25
approved_by:
- '165002000002'
version_date:
  kaz: 2016-04-25
  rus: 2016-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/102487/kaz/25.04.2016
  rus: https://zan.gov.kz/client/#!/doc/102487/rus/25.04.2016
