act_code: '78514'
requisite: Решение Жамбылского районного маслихата Северо-Казахстанской области от 28 февраля 2014 года № 25/8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 3 апреля 2014 года № 2644. Утратило силу решением маслихата Жамбылского района Северо-Казахстанской области от 18 февраля 2022 года № 12/2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Майбалыкского сельского округа Жамбылского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданының Майбалық ауылдық округінде бөлек жергілікті қоғамдастық жиындарын өткізудің қағидасын және жергілікті қоғамдастық жиындарына қатысатын ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-28
approved_by:
- '165007000002'
version_date:
  kaz: 2014-02-28
  rus: 2014-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/78514/kaz/28.02.2014
  rus: https://zan.gov.kz/client/#!/doc/78514/rus/28.02.2014
