act_code: '85338'
requisite: Решение акима города Петропавловска Северо-Казахстанской области от 8 декабря 2014 года № 36. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 декабря 2014 года № 3023. Утратило силу в связи с истечением срока действия (письмо руководителя аппарата акима города Петропавловска Северо-Казахстанской области от 4 марта 2015 года № 16.1.3-16/427)
title:
  rus: Об организации и обеспечении на территории города Петропавловска приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2015 года
  kaz: Қазақстан Республикасының ер азаматтарын 2015 жылғы қаңтардан бастап наурызға дейін Петропавл қаласы аумағында тіркеу және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-08
approved_by:
- '165002000001'
version_date:
  kaz: 2014-12-08
  rus: 2014-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/85338/kaz/08.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85338/rus/08.12.2014
