act_code: '79740'
requisite: Решение маслихата Айыртауского района Северо-Казахстанской области от 31 марта 2014 года № 5-23-12. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 6 мая 2014 года № 2765. Утратило силу решением Айыртауского районного маслихата Северо-Казахстанской области от 18 мая 2022 года № 7-18-19 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел и улиц для участия в сходе местного сообщества Имантауского сельского округа Айыртауского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданының Имантау ауылдық округінде бөлек жергілікті қоғамдастық жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиындарына қатысатын ауыл және көше тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-03-31
approved_by:
- '165003000002'
version_date:
  kaz: 2014-03-31
  rus: 2014-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/79740/kaz/31.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79740/rus/31.03.2014
