act_code: '49818'
requisite: Решение акима Аккайынского района Северо-Казахстанской области от 25 декабря 2009 года № 53. Зарегистрировано Управлением юстиции Аккайынского района Северо-Казахстанской области 5 января 2010 года № 13-2-111. Утратило силу - решением акима Аккайынского района Северо-Казахстанской области от 10 ноября 2011 года № 48
title:
  rus: Об организации и обеспечении на территории Аккайынского района приписки граждан Республики Казахстан мужского пола, которым в год приписки исполняется семнадцать лет и старших возрастов, не прошедших приписку к призывному участку ранее
  kaz: Аққайың ауданының аумағында шақыру жылы он жеті жасқа толатын және одан үлкен жастағы шақыру учаскесінде бұрын тіркелмеген Қазақстан Республикасының ер азаматтарының тіркеуін ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '165005000003'
version_date:
  kaz: 2009-12-25
  rus: 2009-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/49818/kaz/25.12.2009
  rus: https://zan.gov.kz/client/#!/doc/49818/rus/25.12.2009
