act_code: '45997'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 27 апреля 2009 года № 15/6. Зарегистрировано Управлением юстиции Кызылжарского района Северо-Казахстанской области 20 мая 2009 года № 13-8-105. Утратило силу решением маслихата Кызылжарского района Северо-Казахстанской области от 23 сентября 2014 года № 32/17
title:
  rus: О стоимости разовых талонов и о ставках фиксированного налога
  kaz: Бір жолғы талондардың кұны және бекітілген салықтың ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-27
approved_by:
- '165008000002'
version_date:
  kaz: 2009-04-27
  rus: 2009-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/45997/kaz/27.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45997/rus/27.04.2009
