act_code: '204415'
requisite: Решение Северо-Казахстанского областного маслихата от 12 декабря 2024 года № 20/1. Утратило силу решением Северо-Казахстанского областного маслихата от 25 апреля 2025 года № 24/1 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении областного бюджета Северо-Казахстанской области на 2025 – 2027 годы
  kaz: Солтүстік Қазақстан облысының 2025 – 2027 жылдарға арналған облыстық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-12
approved_by:
- '165000000002'
version_date:
  kaz: 2024-12-12
  rus: 2024-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/204415/kaz/12.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204415/rus/12.12.2024
