act_code: '188085'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 октября 2023 года № 7-3. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 8 ноября 2023 года № 7614-15. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 8 мая 2026 года № 39-2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления её размеров и определения перечня отдельных категорий нуждающихся граждан района Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-24
approved_by:
- '165015000002'
version_date:
  kaz: 2024-08-20
  rus: 2024-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/188085/kaz/20.08.2024
  rus: https://zan.gov.kz/client/#!/doc/188085/rus/20.08.2024
caused_by:
  code: '200008'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 20 августа 2024 года № 18-2. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 23 августа 2024 года № 7786-15. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 8 мая 2026 года № 39-2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 октября 2023 года № 7-3 «Об утверждении Правил оказания социальной помощи, установления её размеров и определения перечня отдельных категорий нуждающихся граждан района Магжана Жумабаева Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев аудандық мәслихатының 2023 жылғы 24 қазандағы № 7-3 «Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының әлеуметтік көмек көрсету, оның мөлшерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200008/rus
