act_code: '77656'
requisite: Решение акима Жамбылского района Северо-Казахстанской области от 19 февраля 2014 года № 4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 25 февраля 2014 года № 2569. Утратило силу решением акима Жамбылского района Северо-Казахстанской области от 26 февраля 2015 года № 7
title:
  rus: Об образовании избирательных участков на территории Жамбылского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-02-19
approved_by:
- '165007000003'
version_date:
  kaz: 2014-02-19
  rus: 2014-02-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/77656/kaz/19.02.2014
  rus: https://zan.gov.kz/client/#!/doc/77656/rus/19.02.2014
