act_code: '122554'
requisite: Решение акима Комсомольского сельского округа Тимирязевского района Северо-Казахстанской области от 30 мая 2018 года № 4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 июня 2018 года № 4761
title:
  rus: О переименовании улиц села Комсомольское Тимирязевского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тимирязев ауданы Комсомол ауылының көше атауларын өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-30
approved_by:
- '165012010002'
version_date:
  kaz: 2018-05-30
  rus: 2018-05-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/122554/kaz/30.05.2018
  rus: https://zan.gov.kz/client/#!/doc/122554/rus/30.05.2018
