act_code: '127754'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 24 декабря 2018 года № 27-5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 декабря 2018 года № 5109
title:
  rus: О предоставлении в 2019 году подъемного пособия и социальной поддержки для приобретения или строительства жилья специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Аккайынского района
  kaz: 2019 жылы Аққайың ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға көтерме жәрдемақы және тұрғын үй алу немесе салу үшін әлеуметтік қолдау көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '165005000002'
version_date:
  kaz: 2018-12-24
  rus: 2018-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/127754/kaz/24.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127754/rus/24.12.2018
