act_code: '156687'
requisite: Решение акима Алкатерекского сельского округа Акжарского района Северо-Казахстанской области от 21 июня 2021 года № 4.19.1-11/104. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 июля 2021 года № 23231. Утратил силу решением акима Алкатерекского сельского округа Акжарского района Северо-Казахстанской области от 10 сентября 2021 года № 4.19.1-11/106 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-06-21
approved_by:
- '165004003002'
version_date:
  kaz: 2021-06-21
  rus: 2021-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/156687/kaz/21.06.2021
  rus: https://zan.gov.kz/client/#!/doc/156687/rus/21.06.2021
