act_code: '87978'
requisite: Решение акима района Шал акына Северо-Казахстанской области от 3 марта 2015 года № 04. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 марта 2015 года № 3153
title:
  rus: 'Об образовании избирательных участков '
  kaz: 'Сайлау учаскелерін құру туралы  '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-03-03
approved_by:
- '165010000001'
version_date:
  kaz: 2025-05-06
  rus: 2025-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/87978/kaz/06.05.2025
  rus: https://zan.gov.kz/client/#!/doc/87978/rus/06.05.2025
caused_by:
  code: '209965'
  requisite: Решение акима района Шал акына Северо-Казахстанской области от 6 мая 2025 года № 7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 6 мая 2025 года № 7919-15
  title:
    rus: О внесении изменения в решение акима района Шал акына Северо-Казахстанской области от 3 марта 2015 года № 4 «Об образовании избирательных участков»
    kaz: Солтүстік Қазақстан облысы Шал ақын ауданы әкімінің 2015 жылғы 3 наурыздағы № 4 «Сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209965/rus
