act_code: '53935'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 24 июня 2010 года № 24-3. Зарегистрировано Управлением юстиции Акжарского района Северо-Казахстанской области 6 августа 2010 года № 13-4-107. Утратило силу - решением маслихата Акжарского района Северо-Казахстанской области от 14 июня 2012 года № 4-4
title:
  rus: О Правилах благоустройства и охраны зеленых насаждений в Акжарском районе
  kaz: Ақжар ауданындағы көркейту және жасыл желекті екпелерді қорғау ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2010-06-24
approved_by:
- '165004000002'
version_date:
  kaz: 2010-06-24
  rus: 2010-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/53935/kaz/24.06.2010
  rus: https://zan.gov.kz/client/#!/doc/53935/rus/24.06.2010
