act_code: '203547'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 25 ноября 2024 года № 22/342. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 ноября 2024 года № 7832-15
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Есильском районе Северо-Казахстанской области на 2025 год
  kaz: Солтүстік Қазақстан облысы Есіл ауданының 2025 жылға бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-25
approved_by:
- '165006000002'
version_date:
  kaz: 2024-11-25
  rus: 2024-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/203547/kaz/25.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203547/rus/25.11.2024
