act_code: '101653'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 31 марта 2016 года № 2-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 апреля 2016 года № 3729. Утратило силу решением Акжарского районного маслихата Северо-Казахстанской области от 25 декабря 2020 года № 66-2 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций по Акжарскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ақжар ауданы бойынша жиналыстар, митингiлер, шерулер, пикеттер және демонстрациялар өткiзу тәртiбiн қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-03-31
approved_by:
- '165004000002'
version_date:
  kaz: 2016-03-31
  rus: 2016-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/101653/kaz/31.03.2016
  rus: https://zan.gov.kz/client/#!/doc/101653/rus/31.03.2016
