act_code: '221251'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 26 декабря 2025 года № 5-37 с
title:
  rus: Об утверждении бюджета Бидайыкского сельского округа Уалихановского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Уәлиханов ауданы Бидайық ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '165013000002'
version_date:
  kaz: 2026-06-24
  rus: 2026-06-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/221251/kaz/24.06.2026
  rus: https://zan.gov.kz/client/#!/doc/221251/rus/24.06.2026
caused_by:
  code: '227445'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 24 июня 2026 года № 6-41 с
  title:
    rus: О внесении изменений в решение Уалихановского районного маслихата от 26 декабря 2025 года № 5-37 с «Об утверждении бюджета Бидайыкского сельского округа Уалихановского района на 2026-2028 годы»
    kaz: Уәлиханов аудандық мәслихатының 2025 жылғы 26 желтоқсандағы № 5-37 с «2026-2028 жылдарға арналған Уәлиханов ауданы Бидайық ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/227445/rus
