act_code: '90729'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 18 мая 2015 года № 42/265. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 июня 2015 года № 3269. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 24 апреля 2018 года № 27/145
title:
  rus: О повышении базовых ставок земельного налога и единого земельного налога по Есильскому району
  kaz: Есіл ауданы бойынша жер салығының және бірыңғай жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-18
approved_by:
- '165006000002'
version_date:
  kaz: 2016-08-12
  rus: 2016-08-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/90729/kaz/12.08.2016
  rus: https://zan.gov.kz/client/#!/doc/90729/rus/12.08.2016
caused_by:
  code: '106031'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 12 августа 2016 года № 5/32. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 сентября 2016 года № 3890. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 24 апреля 2018 года № 27/145
  title:
    rus: О внесении изменения в решение маслихата Есильского района Северо-Казахстанской области от 18 мая 2015 года№ 42/265 «О повышении базовых ставок земельного налога и единого земельного налога по Есильскому району»
    kaz: «Есіл ауданы бойынша жер салығының және бірыңғай жер салығының базалық мөлшерлемелерін жоғарылату туралы» Солтүстік Қазақстан облысы Есіл ауданы мәслихатының 2015 жылғы 18 мамырдағы № 42/265 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/106031/rus
