act_code: '90729'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 18 мая 2015 года № 42/265. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 июня 2015 года № 3269. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 24 апреля 2018 года № 27/145
title:
  rus: О повышении базовых ставок земельного налога и единого земельного налога по Есильскому району
  kaz: Есіл ауданы бойынша жер салығының және бірыңғай жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-05-18
approved_by:
- '165006000002'
version_date:
  kaz: 2015-05-18
  rus: 2015-05-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/90729/kaz/18.05.2015
  rus: https://zan.gov.kz/client/#!/doc/90729/rus/18.05.2015
