act_code: '172988'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 13 октября 2022 года № 7-21-16. Утратило силу решением Айыртауского районного маслихата Северо-Казахстанской области от 20 февраля 2024 года № 8-12-3 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы для участия в сходе местного сообщества в Айыртауском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-10-13
approved_by:
- '165003000002'
version_date:
  kaz: 2022-10-13
  rus: 2022-10-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/172988/kaz/13.10.2022
  rus: https://zan.gov.kz/client/#!/doc/172988/rus/13.10.2022
