act_code: '142105'
requisite: Решение акима района Магжана Жумабаева Северо-Казахстанской области от 21 апреля 2020 года № 7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 апреля 2020 года № 6256. Утратило силу решением акима района Магжана Жумабаева Северо-Казахстанской области от 20 октября 2020 года № 14 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об объявлении на территории района Магжана Жумабаева Северо-Казахстанской области чрезвычайной ситуации природного характера местного масштаба
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-04-21
approved_by:
- '165015000003'
version_date:
  kaz: 2020-04-21
  rus: 2020-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/142105/kaz/21.04.2020
  rus: https://zan.gov.kz/client/#!/doc/142105/rus/21.04.2020
