act_code: '55923'
requisite: Решение акима Пригородного сельского округа Мамлютского района Северо-Казахстанской области от 26 ноября 2010 года № 12. Зарегистрировано Управлением юстиции Мамлютского района Северо-Казахстанской области 13 декабря 2010 года № 13-10-124
title:
  rus: О присвоении наименований составных частей населенных пунктов Пригородного сельского округа Мамлютского района
  kaz: Мамлют ауданы Пригород ауылдық округінің елді мекендерінің құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-26
approved_by:
- '165009010002'
version_date:
  kaz: 2018-06-28
  rus: 2018-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/55923/kaz/28.06.2018
  rus: https://zan.gov.kz/client/#!/doc/55923/rus/28.06.2018
caused_by:
  code: '123277'
  requisite: Решение акима Пригородного сельского округа Мамлютского района Северо-Казахстанской области от 28 июня 2018 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июля 2018 года № 4807
  title:
    rus: О внесении изменений в решение акима Пригородного сельского округа Мамлютского района Северо-Казахстанской области от 26 ноября 2010 года № 12 «О присвоении наименований составных частей населенных пунктов Пригородного сельского округа Мамлютского района»
    kaz: «Мамлют ауданы Пригород селолық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы» Солтүстік Қазақстан облысы Мамлют ауданы Пригород ауылдық округі әкімінің 2010 жылғы 26 қарашадағы № 12 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123277/rus
