act_code: '177693'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2022 года № 25-6
title:
  rus: Об утверждении бюджета Киялинского сельского округа Аккайынского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Аққайың ауданының Қиялы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '165005000002'
version_date:
  kaz: 2023-04-28
  rus: 2023-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/177693/kaz/28.04.2023
  rus: https://zan.gov.kz/client/#!/doc/177693/rus/28.04.2023
caused_by:
  code: '180948'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 28 апреля 2023 года № 3-6
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2022 года № 25-6 «Об утверждении бюджета Киялинского сельского округа Аккайынского района на 2023 – 2025 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданыны мәслихатының 2022 жылғы 30 желтоқсандағы № 25-6 «2023-2025 жылдарға арналған Аққайың ауданының Қиялы ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180948/rus
