act_code: '3121'
requisite: Решение акима Северо-Казахстанской области от 22 февраля 1999 года № 31. Зарегистрировано Управлением юстиции Северо-Казахстанской области 15 марта 1999 года № 63
title:
  rus: О преобразовании государственного учреждения "Областная государственная инспекция по контролю за использованием и охраной земель Северо-Казахстанской области" в государственное предприятие
  kaz: '"Солтүстік Қазақстан облысы жерінің пайдаланылуы мен қорғалуын бақылау жөніндегі облыстық мемлекеттік инспекция" мемлекеттік мекемесін қайта құру туралы'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-02-22
approved_by:
- '165000000003'
version_date:
  kaz: 1999-02-22
  rus: 1999-02-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/3121/kaz/22.02.1999
  rus: https://zan.gov.kz/client/#!/doc/3121/rus/22.02.1999
