act_code: '134180'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 7 августа 2019 года № 36/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 августа 2019 года № 5543
title:
  rus: Об установлении повышенных на двадцать пять процентов должностных окладов и тарифных ставок специалистам в области социального обеспечения и культуры, являющимся гражданскими служащими и работающих в сельской местности Тимирязевского района Северо-Казахстанской области
  kaz: Азаматтық қызметшілер болып табылатын және Солтүстік Қазақстан облысы Тимирязев ауданының ауылдық жерінде жұмыс iстейтiн әлеуметтiк қамсыздандыру және мәдениет саласындағы мамандарға жиырма бес пайызға жоғарылатылған лауазымдық айлықақылар мен тарифтік мөлшерлемелер белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-08-07
approved_by:
- '165012000002'
version_date:
  kaz: 2019-08-07
  rus: 2019-08-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/134180/kaz/07.08.2019
  rus: https://zan.gov.kz/client/#!/doc/134180/rus/07.08.2019
