act_code: '138020'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 30 декабря 2019 года № 6-38-13. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 8 января 2020 года № 5796
title:
  rus: Об утверждении бюджета Антоновского сельского округа Айыртауского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Айыртау ауданы Антоновка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '165003000002'
version_date:
  kaz: 2020-11-25
  rus: 2020-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/138020/kaz/25.11.2020
  rus: https://zan.gov.kz/client/#!/doc/138020/rus/25.11.2020
caused_by:
  code: '149052'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 25 ноября 2020 года № 6-47-5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 ноября 2020 года № 6733
  title:
    rus: О внесении изменений и дополнения в решение Айыртауского районного маслихата от 30 декабря 2019 года № 6-38-13 «Об утверждении бюджета Антоновского сельского округа Айыртауского района на 2020-2022 годы»
    kaz: Айыртау аудандық мәслихатының 2019 жылғы 30 желтоқсандағы № 6-38-13 «2020-2022 жылдарға арналған Айыртау ауданы Антоновка ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149052/rus
