act_code: '140312'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 12 марта 2020 года № 46/290. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 17 марта 2020 года № 6096. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 17 октября 2023 года № 9/118 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Есильском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Есіл ауданында әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2020-03-12
approved_by:
- '165006000002'
version_date:
  kaz: 2022-03-17
  rus: 2022-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/140312/kaz/17.03.2022
  rus: https://zan.gov.kz/client/#!/doc/140312/rus/17.03.2022
caused_by:
  code: '166033'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 17 марта 2022 года № 17/185. Зарегистрировано в Министерстве юстиции Республики Казахстан 4 апреля 2022 года № 27375. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 17 октября 2023 года № 9/118 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата Есильского района Северо-Казахстанской области от 12 марта 2020 года № 46/290 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Есильском районе Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Есіл ауданы мәслихатының 2020 жылғы 12 наурыздағы № 46/290 «Солтүстік Қазақстан облысы Есіл ауданында әлеуметтік көмек көрсету, оның мөлшерлерін белгілеу және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындау қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166033/rus
