act_code: '127483'
requisite: Решение акима района имени Габита Мусрепова Северо-Казахстанской области от 24 декабря 2018 года № 46. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 декабря 2018 года № 5095. Утратило силу решением акима района имени Габита Мусрепова Северо-Казахстанской области от 12 марта 2026 года № 11 (вводится в действие после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков по району имени Габита Мусрепова Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы аудан бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '165014000003'
version_date:
  kaz: 2019-11-29
  rus: 2019-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/127483/kaz/29.11.2019
  rus: https://zan.gov.kz/client/#!/doc/127483/rus/29.11.2019
caused_by:
  code: '136637'
  requisite: Решение акима района имени Габита Мусрепова Северо-Казахстанской области от 29 ноября 2019 года № 21. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 декабря 2019 года № 5697. Утратило силу решением акима района имени Габита Мусрепова Северо-Казахстанской области от 12 марта 2026 года № 11 (вводится в действие после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение акима района имени Габита Мусрепова Северо-Казахстанской области от 24 декабря 2018 года № 46 «Об образовании избирательных участков по району имени Габита Мусрепова Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы аудан әкімінің 2018 жылғы 24 желтоқсандағы № 46 «Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы аудан бойынша сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136637/rus
