act_code: '105025'
requisite: Решение акима Акбулакского сельского округа Уалихановского района Северо-Казахстанской области от 8 июля 2016 года № 9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 июля 2016 года № 3837
title:
  rus: О снятии ограничительных мероприятий по бруцеллезу крупного рогатого скота на территории села Акбулак Акбулакского сельского округа Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Ақбұлақ ауылдық округінің Ақбұлақ ауылында ірі қара малға бруцеллез бойынша шектеу шараларын алып тастау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-07-08
approved_by:
- '165013012001'
version_date:
  kaz: 2016-07-08
  rus: 2016-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/105025/kaz/08.07.2016
  rus: https://zan.gov.kz/client/#!/doc/105025/rus/08.07.2016
