act_code: '228831'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 11 августа 2026 года № 43-5
title:
  rus: Об утверждении Положения о коммунальном государственном учреждении «Аппарат маслихата района имени Габита Мусрепова Северо-Казахстанской области»
  kaz: «Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданы мәслихатының аппараты» коммуналдық мемлекеттік мекемесі туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2026-08-11
approved_by:
- '165014000002'
version_date:
  kaz: 2026-08-11
  rus: 2026-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/228831/kaz/11.08.2026
  rus: https://zan.gov.kz/client/#!/doc/228831/rus/11.08.2026
