act_code: '212005'
requisite: Решение акима Сырымбетского сельского округа Айыртауского района Северо-Казахстанской области от 1 июля 2025 года № 7. Отменено решением акима Сырымбетского сельского округа Айыртауского района Северо-Казахстанской области от 29 августа 2025 года № 9 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын тағайындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-07-01
approved_by:
- '165003014002'
version_date:
  kaz: 2025-07-01
  rus: 2025-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/212005/kaz/01.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212005/rus/01.07.2025
