act_code: '121357'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 18 апреля 2018 года № 18-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 3 мая 2018 года № 4700. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 8 мая 2026 года № 39-3 (вводится в действие с 1 января 2026 года)
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-18
approved_by:
- '165015000002'
version_date:
  kaz: 2020-03-19
  rus: 2020-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/121357/kaz/19.03.2020
  rus: https://zan.gov.kz/client/#!/doc/121357/rus/19.03.2020
caused_by:
  code: '140688'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 19 марта 2020 года № 37-5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 марта 2020 года № 6121. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 8 мая 2026 года № 39-3 (вводится в действие с 1 января 2026 года)
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 18 апреля 2018 года № 18-3 «О ставках земельного налога»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының «Жер салығының мөлшерлемелері туралы» 2018 жылғы 18 сәуірдегі № 18-3 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140688/rus
