act_code: '116389'
requisite: Решение акима Кырымбетского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 13 ноября 2017 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 ноября 2017 года № 4380
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-11-13
approved_by:
- '165014008002'
version_date:
  kaz: 2017-11-13
  rus: 2017-11-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/116389/kaz/13.11.2017
  rus: https://zan.gov.kz/client/#!/doc/116389/rus/13.11.2017
