act_code: '76075'
requisite: Решение акима Кызылжарского района Северо-Казахстанской области от 12 декабря 2013 года № 39-р. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 декабря 2013 года № 2451. Утратило силу (письмо руководителя аппарата акима Кызылжарского района Северо-Казахстанской области от 7 ноября 2014 года № 9.1.4-4/1245)
title:
  rus: Об организации и обеспечении на территории Кызылжарского района Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2014 года
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданының аумағында 2014 жылғы қаңтар-наурыз аралығында Қазақстан Республикасы азаматтарын әскери есепке алу және медициналық куәландыру ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-12
approved_by:
- '165008000003'
version_date:
  kaz: 2013-12-12
  rus: 2013-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/76075/kaz/12.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76075/rus/12.12.2013
