act_code: '221242'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 6 января 2026 года № 8-37-5
title:
  rus: О ставках земельного налога по Айыртаускому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданы бойынша жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-06
approved_by:
- '165003000002'
version_date:
  kaz: 2026-01-06
  rus: 2026-01-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/221242/kaz/06.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221242/rus/06.01.2026
