act_code: '165943'
requisite: Решение акима Шоптыкольского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 25 марта 2022 года № 7. Зарегистрирован в Министерстве юстиции Республики Казахстан 1 апреля 2022 года № 27370
title:
  rus: О переименовании улиц в селе Шоптыколь Шоптыкольского сельского округа района имени Габита Мусрепова Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданның Шөптікөл ауылдық округінің Шөптікөл ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-25
approved_by:
- '165014018002'
version_date:
  kaz: 2022-03-25
  rus: 2022-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/165943/kaz/25.03.2022
  rus: https://zan.gov.kz/client/#!/doc/165943/rus/25.03.2022
