act_code: '209498'
requisite: Решение акима Нежинского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 23 апреля 2025 года № 21
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-23
approved_by:
- '165014010002'
version_date:
  kaz: 2025-04-23
  rus: 2025-04-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/209498/kaz/23.04.2025
  rus: https://zan.gov.kz/client/#!/doc/209498/rus/23.04.2025
