act_code: '4428'
requisite: Решение акима Северо-Казахстанской области от 2 июня 1998 года № 136. Зарегистрировано Управлением юстиции Северо-Казахстанской области 26 июня 1998 года за № 28. Утратило силу - решением акима Северо-Казахстанской области от 4 декабря 2000 года № 228
title:
  rus: О реализации Указа Президента Республики Казахстан от 18 мая 1998 г. № 3956 «О первоочередных мерах по улучшению состояния здоровья граждат Республики Казахстан»
  kaz: Қазақстан Республикасы Президентінің 1998 жылғы 18 мамырдағы «Қазақстан Республикасы азаматтарының денсаулық жағдайларын жақсарту жөніндегі біріншікезекті шаралар туралы» № 3956 Жарлығын жүзеге асыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-06-01
approved_by:
- '165000000003'
version_date:
  kaz: 1998-06-01
  rus: 1998-06-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/4428/kaz/01.06.1998
  rus: https://zan.gov.kz/client/#!/doc/4428/rus/01.06.1998
