act_code: '10145'
requisite: Решение акима Северо-Казахстанской области от 30 июля 1998 года № 171. Зарегистрировано Управлением юстиции Северо-Казахстанской области 7 октября 1998 года за № 34. Государственная регистрация отменена - заключение об отмене регистрации департамента юстиции СКО № 04-13-4708 от 30 ноября 2005 года. Утратило силу - решением акима Северо-Казахстанской области от 24 мая 2007 года № 16
title:
  rus: О комплексной программе развития единой системы безналичных расчетов в хозяйственном обороте Северо-Казахстанской области и вывода предприятий из зоны ближнего банкротства в конкурентоспособное состояние
  kaz: Солтүстік Қазақстан облысының шаруашылық айналымындағы қолма қол есеп айырысудың бірыңғай жүйесін кешенді дамыту бағдарламасы және кәсіпорындарды банкротқа жақын аймақтан шығарып, бәсекеге шыдайтын жағдайға көтеру туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 1998-07-29
approved_by:
- '165000000003'
version_date:
  kaz: 1998-07-29
  rus: 1998-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/10145/kaz/29.07.1998
  rus: https://zan.gov.kz/client/#!/doc/10145/rus/29.07.1998
