act_code: '36600'
requisite: Решение маслихата города Петропавловска Северо-Казахстанской области от 15 декабря 2007 года № 6. Зарегистрировано Управлением юстиции города Петропавловска Северо-Казахстанской области 3 января 2008 года № 13-1-89. Утратило силу - решением маслихата города Петропавловска Северо-Казахстанской области от 18 сентября 2012 года № 3
title:
  rus: О правилах благоустройства и охраны зеленых насаждений в городе Петропавловске
  kaz: Петропавл қаласындағы көркейту және жасыл желекті екпелерді қорғау ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2007-12-15
approved_by:
- '165002000002'
version_date:
  kaz: 2007-12-15
  rus: 2007-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/36600/kaz/15.12.2007
  rus: https://zan.gov.kz/client/#!/doc/36600/rus/15.12.2007
