act_code: '197835'
requisite: Решение акима Айыртауского района Северо-Казахстанской области от 11 июня 2024 года № 5. Зарегистрирован в Департаменте юстиции Северо-Казахстанской области 18 июня 2024 года № 7765-15
title:
  rus: Об образовании избирательных участков на территории Айыртауского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-11
approved_by:
- '165003000003'
version_date:
  kaz: 2026-05-08
  rus: 2026-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/197835/kaz/08.05.2026
  rus: https://zan.gov.kz/client/#!/doc/197835/rus/08.05.2026
caused_by:
  code: '225245'
  requisite: Решение акима Айыртауского района Северо-Казахстанской области от 8 мая 2026 года № 8
  title:
    rus: О внесении изменения в решение акима Айыртауского района Северо-Казахстанской области от 11 июня 2024 года № 5 «Об образовании избирательных участков по Айыртаускому району Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Айыртау ауданы әкімінің 2024 жылғы 11 маусымдағы № 5 «Солтүстік Қазақстан облысы Айыртау ауданы бойынша сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/225245/rus
