act_code: '117509'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 25 декабря 2017 года № 20/9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2018 года № 4479
title:
  rus: О бюджете города Сергеевки района Шал акына на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Шал ақын ауданы Сергеевка қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '165010000002'
version_date:
  kaz: 2017-12-25
  rus: 2017-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/117509/kaz/25.12.2017
  rus: https://zan.gov.kz/client/#!/doc/117509/rus/25.12.2017
