act_code: '192401'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 29 декабря 2023 года № 18/4
title:
  rus: Об утверждении бюджета Беловского сельского округа Мамлютского района Северо-Казахстанской области на 2024-2026 годы
  kaz: Солтүстік Қазақстан облысы Мамлют ауданы Белое ауылдық округінің 2024-2026 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '165009000002'
version_date:
  kaz: 2024-12-09
  rus: 2024-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/192401/kaz/09.12.2024
  rus: https://zan.gov.kz/client/#!/doc/192401/rus/09.12.2024
caused_by:
  code: '204233'
  requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 9 декабря 2024 года № 35/4
  title:
    rus: О внесении изменений в решение маслихата Мамлютского района Северо-Казахстанской области от 29 декабря 2023 года № 18/4 «Об утверждении бюджета Беловского сельского округа Мамлютского района Северо-Казахстанской области на 2024-2026 годы»
    kaz: Солтүстік Қазақстан облысы Мамлют ауданы мәслихатының 2023 жылғы 29 желтоқсандағы № 18/4 «Солтүстік Қазақстан облысы Мамлют ауданы Белое ауылдық округінің 2024-2026 жылдарға арналған бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204233/rus
