act_code: '6732'
requisite: Решение акима Северо-Казахстанской области от 28 июля 2000 года № 152. Зарегистрировано Управлением юстиции Северо-Казахстанской области 8 августа 2000 года № 143
title:
  rus: Об открытии осенне-зимнего охотничьего сезона в 2000-2001 года
  kaz: 2000-2001 жылдарғы күзгі-қысқы аңшылық маусымды ашу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-07-27
approved_by:
- '165000000003'
version_date:
  kaz: 2000-07-27
  rus: 2000-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/6732/kaz/27.07.2000
  rus: https://zan.gov.kz/client/#!/doc/6732/rus/27.07.2000
