act_code: '181290'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 12 мая 2023 года № 4/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 мая 2023 года № 7497-15. Утратило силу решением маслихата Мамлютского района Северо-Казахстанской области от 28 декабря 2023 года № 16/7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2023 год на территории Мамлютского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мамлют ауданының аумағында шетелдіктер үшін 2023 жылға арналған туристік жарнаның мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-12
approved_by:
- '165009000002'
version_date:
  kaz: 2023-05-12
  rus: 2023-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/181290/kaz/12.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181290/rus/12.05.2023
