act_code: '51086'
requisite: Решение маслихата Тайыншинского района Cеверо-Казахстанской области от 8 февраля 2010 года № 179. Зарегистрировано Управлением юстиции Тайыншинского района Cеверо-Казахстанской области 9 марта 2010 года № 13-11-169. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 11 июля 2013 года № 111
title:
  rus: О предоставлении социальной помощи на приобретение топлива специалистам государственных организаций здравоохранения, образования, социального обеспечения, культуры и спорта проживающим и работающим в сельских населенных пунктах
  kaz: Ауылды жерлерде тұратын және жұмыс істейтін денсаулық сақтау, білім, әлеуметтік қамсыздандыру, мәдениет және спорт мемлекеттік ұйымдарының мамандарына отын сатып алуға әлеуметтік көмек ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-08
approved_by:
- '165011000002'
version_date:
  kaz: 2010-02-08
  rus: 2010-02-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/51086/kaz/08.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51086/rus/08.02.2010
