act_code: '192238'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 29 декабря 2023 года № 10/5
title:
  rus: Об утверждении бюджета Дзержинского сельского округа Тимирязевского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Тимирязев ауданы Дзержинский ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '165012000002'
version_date:
  kaz: 2024-02-27
  rus: 2024-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/192238/kaz/27.02.2024
  rus: https://zan.gov.kz/client/#!/doc/192238/rus/27.02.2024
caused_by:
  code: '194243'
  requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 27 февраля 2024 года № 12/4
  title:
    rus: О внесении изменений и дополнений в решение Тимирязевского районного маслихата от 29 декабря 2023 года № 10/5 «Об утверждении бюджета Дзержинского сельского округа Тимирязевского района на 2024-2026 годы»
    kaz: «2024-2026 жылдарға арналған Тимирязев ауданы Дзержинский ауылдық округінің бюджетін бекіту туралы» Тимирязев аудандық мәслихатының 2023 жылғы 29 желтоқсандағы № 10/5 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/194243/rus
