act_code: '51326'
requisite: Решение акима Новомихайловского сельского округа Мамлютского района Северо-Казахстанской области от 15 февраля 2010 года № 6. Зарегистрировано Управлением юстиции Мамлютского района Северо-Казахстанской области 19 марта 2010 года № 13-10-105. Утратило силу решением акима Новомихайловского сельского округа Мамлютского района Северо-Казахстанской области от 1 апреля 2010 года № 7
title:
  rus: О присвоении наименований составных частей населенных пунктов Новомихайловского сельского округа
  kaz: Новомихайлов селолық округінің елді мекендердің кұрамдас бөлімдерге атауларын иемдеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-02-15
approved_by:
- '165009009002'
version_date:
  kaz: 2010-02-15
  rus: 2010-02-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/51326/kaz/15.02.2010
  rus: https://zan.gov.kz/client/#!/doc/51326/rus/15.02.2010
