act_code: '123526'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 4 июля 2018 года № 29-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 17 июля 2018 года № 4841. Утратило силу решением Акжарского районного маслихата Северо-Казахстанской области от 3 марта 2020 года № 53-1 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении единых ставок фиксированного налога по Акжарскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ақжар ауданының тіркелген салықтың бірыңғай мөлшерлемелерін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-07-04
approved_by:
- '165004000002'
version_date:
  kaz: 2018-07-04
  rus: 2018-07-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/123526/kaz/04.07.2018
  rus: https://zan.gov.kz/client/#!/doc/123526/rus/04.07.2018
