act_code: '189098'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 27 ноября 2023 года № 10/137
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села, улицы для участия в сходе местного сообщества Бескудукского сельского округа Есильского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Есіл ауданы Бесқұдық ауылдық округінің жергілікті қоғамдастығының бөлек жиындарын өткізу қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-27
approved_by:
- '165006000002'
version_date:
  kaz: 2025-03-04
  rus: 2025-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/189098/kaz/04.03.2025
  rus: https://zan.gov.kz/client/#!/doc/189098/rus/04.03.2025
caused_by:
  code: '207872'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 4 марта 2025 года № 24/397
  title:
    rus: О внесении изменения в решение маслихата Есильского района Северо-Казахстанской области от 27 ноября 2023 года № 10/137 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей села, улицы для участия в сходе местного сообщества Бескудукского сельского округа Есильского района Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Есіл ауданының Бесқұдық ауылдық округінің жергілікті қоғамдастығының бөлек жиындарын өткізу қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше тұрғындары өкілдерінің сандық құрамын бекіту туралы» Солтүстік Қазақстан облысы Есіл ауданы мәслихатының 2023 жылғы 27 қарашадағы № 10/137 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207872/rus
