act_code: '194374'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 5 марта 2024 года № 8-12-23
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов для населения на сбор, транспортировку, сортировку  и захоронение твердых бытовых отходов по Айыртаускому району Северо-Казахстанской области
  kaz: Айыртау ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын, халық үшін қатты тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2024-03-05
approved_by:
- '165003000002'
version_date:
  kaz: 2024-03-05
  rus: 2024-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/194374/kaz/05.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194374/rus/05.03.2024
