act_code: '168910'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 8 июня 2022 года № 16/18. Отменено решением маслихата Жамбылского района Северо-Казахстанской области от 14 апреля 2023 года № 2/3  (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» коммунального государственного учреждения «Аппарат маслихата Жамбылского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданы мәслихатының аппараты» коммуналдық мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2022-06-08
approved_by:
- '165007000002'
version_date:
  kaz: 2022-06-08
  rus: 2022-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/168910/kaz/08.06.2022
  rus: https://zan.gov.kz/client/#!/doc/168910/rus/08.06.2022
