act_code: '2550'
requisite: Решение Северо-Казахстанского областного маслихата от 19 июня 1998 года № 17/11. Зарегистрировано Управлением юстиции Северо-Казахстанской области 27 декабря 1998 года за № 51. Утратило силу решением Северо-Казахстанского областного маслихата от 21 декабря 2004 года № 12/7
title:
  rus: О коллективном обращении группы пенсионеров г. Петропавловска об ускорении Правительством Республики Казахстан проведения индексации пенсий
  kaz: Петропавл қаласының бір топ зейнеткерлерінің Қазақстан Республикасы Үкіметінің зейнетақыларға индекстеу жүргізуді жеделдету туралы ұжымдық өтініші туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-06-18
approved_by:
- '165000000002'
version_date:
  kaz: 1998-06-18
  rus: 1998-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/2550/kaz/18.06.1998
  rus: https://zan.gov.kz/client/#!/doc/2550/rus/18.06.1998
