act_code: '49288'
requisite: Решение акима района Шал акына Северо-Казахстанской области от 24 ноября 2009 года № 20. Зарегистрировано Управлением юстиции района Шал акына Северо-Казахстанской области 20 декабря 2009 года № 13-14-89. Утратило силу - решением акима района Шал акына Северо-Казахстанской области от 7 октября 2011 года № 22
title:
  rus: О проведении приписки к призывному участку граждан 1993 года рождения и старших призывных возрастов, ранее не прошедших приписку на территории района Шал акына в январе-марте 2010 года
  kaz: Шал ақын ауданының аумағында 2010 жылдың қаңтар-наурыз айларында 1993 жылғы және жастары үлкен, бұрын тіркеуден өткізілмеген азаматтарды әскерге шақыру учаскесінде тіркеуден өткізу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-11-24
approved_by:
- '165010000003'
version_date:
  kaz: 2009-11-24
  rus: 2009-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/49288/kaz/24.11.2009
  rus: https://zan.gov.kz/client/#!/doc/49288/rus/24.11.2009
