act_code: '163712'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 30 декабря 2021 года № 16/9
title:
  rus: Об утверждении бюджета Леденевского сельского округа Мамлютского района Северо-Казахстанской области на 2022-2024 годы
  kaz: Солтүстік Қазақстан облысы Мамлют ауданы Леденев ауылдық округінің 2022-2024 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '165009000002'
version_date:
  kaz: 2022-06-30
  rus: 2022-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/163712/kaz/30.06.2022
  rus: https://zan.gov.kz/client/#!/doc/163712/rus/30.06.2022
caused_by:
  code: '169627'
  requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 30 июня 2022 года № 23/20
  title:
    rus: О внесении изменений и дополнений в решение маслихата Мамлютского района Северо-Казахстанской области от 30 декабря 2021 года № 16/9 «Об утверждении бюджета Леденевского сельского округа Мамлютского района Северо-Казахстанской области на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облысы Мамлют ауданы мәслихатының 2021 жылғы 30 желтоқсандағы № 16/9 «Солтүстік Қазақстан облысы Мамлют ауданы Леденев ауылдық округінің 2022-2024 жылдарға арналған бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169627/rus
