act_code: '43660'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2008 жылғы 24 желтоқсандағы № 2-11с шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2009 жылғы 21 қаңтарда № 13-13-97 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2011 жылғы 3 қазандағы № 02-03-03/222 хаты)
title:
  rus: 2009 жылға арналған аудандық бюджет туралы
  kaz: 2009 жылға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-12-24
approved_by:
- '165013000002'
version_date:
  kaz: 2009-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/43660/kaz/27.04.2009
caused_by:
  code: '46075'
  requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2009 жылғы 27 сәуірдегі № 6-13с шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2009 жылғы 21 мамырда № 13-13-105 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2011 жылғы 3 қазандағы № 02-03-03/222 хаты)
  title:
    rus: '"2009 жылға арналған аудандық бюджет туралы" аудандық мәслихаттың 2008 жылғы 24 желтоқсандағы № 2-11с шешіміне өзгерістер мен толықтырулар енгізу туралы'
    kaz: '"2009 жылға арналған аудандық бюджет туралы" аудандық мәслихаттың 2008 жылғы 24 желтоқсандағы № 2-11с шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/46075/rus
