act_code: '116467'
requisite: Решение акима района имени Габита Мусрепова Северо-Казахстанской области от 14 ноября 2017 года № 21. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 ноября 2017 года № 4386
title:
  rus: Об организации и обеспечении на территории района имени Габита Мусрепова Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2018 года
  kaz: 2018 жылғы қаңтар-наурыз аралығында Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданының аумағында Қазақстан Республикасының жынысы ер азаматтарын тіркеуді және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-11-14
approved_by:
- '165014000003'
version_date:
  kaz: 2018-01-10
  rus: 2018-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/116467/kaz/10.01.2018
  rus: https://zan.gov.kz/client/#!/doc/116467/rus/10.01.2018
caused_by:
  code: '118064'
  requisite: Решение акима района имени Габита Мусрепова Северо-Казахстанской области от 10 января 2018 года № 01. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 18 января 2018 года № 4551
  title:
    rus: О внесении изменений в решение акима района имени Габита Мусрепова Северо-Казахстанской области от 14 ноября 2017 года № 21 «Об организации и обеспечении на территории района имени Габита Мусрепова Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2018 года»
    kaz: «2018 жылғы қаңтар-наурыз аралығында Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданының аумағында Қазақстан Республикасының жынысы ер азаматтарын әскерге шақыруды және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы» Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы аудан әкімінің 2017 жылғы 14 қарашадағы № 21 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/118064/rus
