act_code: '177428'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2022 года № 25-4
title:
  rus: Об утверждении бюджета Григорьевского сельского округа Аккайынского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Аққайың ауданының Григорьевка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '165005000002'
version_date:
  kaz: 2023-11-20
  rus: 2023-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/177428/kaz/20.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177428/rus/20.11.2023
caused_by:
  code: '188837'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 20 ноября 2023 года № 10-4
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2022 года № 25-4 «Об утверждении бюджета Григорьевского сельского округа Аккайынского района на 2023-2025 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2022 жылғы 30 желтоқсандағы № 25-4 «2023-2025 жылдарға арналған Аққайың ауданының Григорьевка ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188837/rus
