act_code: '155311'
requisite: Решение акима Амандыкского сельского округа Тайыншинского района Северо-Казахстанской области от 27 апреля 2021 года № 11. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 апреля 2021 года № 7357
title:
  rus: О присвоении наименования безымянной улице
  kaz: Атауы жоқ көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-27
approved_by:
- '165011004002'
version_date:
  kaz: 2021-04-27
  rus: 2021-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/155311/kaz/27.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155311/rus/27.04.2021
