act_code: '197377'
requisite: Решение акима Бирликского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 5 июня 2024 года № 9. Утратил силу решением акима Бирликского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 26 июля 2024 года № 9 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-05
approved_by:
- '165014003002'
version_date:
  kaz: 2024-06-05
  rus: 2024-06-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/197377/kaz/05.06.2024
  rus: https://zan.gov.kz/client/#!/doc/197377/rus/05.06.2024
