act_code: '58311'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 29 марта 2011 года № 30-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 апреля 2011 года № 13-4-118
title:
  rus: О предоставлении подъемного пособия и социальной поддержки для приобретения  жилья специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты Акжарского района на 2011 год
  kaz: 2011 жылы Ақжар ауданының ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамтамасыздандыру, мәдениет және спорт мамандарына көтерме жәрдемағы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-03-29
approved_by:
- '165004000002'
version_date:
  kaz: 2011-07-27
  rus: 2011-07-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/58311/kaz/27.07.2011
  rus: https://zan.gov.kz/client/#!/doc/58311/rus/27.07.2011
caused_by:
  code: '60157'
  requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 27 июля 2011 года № 33-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 августа 2011 года № 13-4-127
  title:
    rus: О внесении изменения в решение Акжарского районного маслихата от 29 марта 2011 года N 30-2 "О предоставлении подъемного пособия и социальной поддержки для приобретения жилья специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, прибывшим для работы и проживания в сельские населенные пункты Акжарского района на 2011 год"
    kaz: '"2011 жылы Ақжар ауданының ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамтамасыздандыру, мәдениет және спорт мамандарына көтерме жәрдемағы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы" 2011 жылғы 29 наурыздағы N 30-2 Ақжар аудандық мәслихат шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/60157/rus
