act_code: '99541'
requisite: Решение акима Жамбылского района Северо-Казахстанской области от 13 февраля 2016 года № 25. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 25 февраля 2016 года № 3632. Утратило силу решением акима Жамбылского района Северо-Казахстанской области от 13 апреля 2016 года № 33
title:
  rus: Об объявлении чрезвычайной ситуации местного масштаба на территории Жамбылского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданының аумағында жергілікті ауқымдағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-02-13
approved_by:
- '165007000001'
version_date:
  kaz: 2016-02-13
  rus: 2016-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/99541/kaz/13.02.2016
  rus: https://zan.gov.kz/client/#!/doc/99541/rus/13.02.2016
