act_code: '178142'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 27 декабря 2022 года № 3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 января 2023 года № 7437
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Петропавловск
  kaz: Петропавл қаласы бойынша коммуналдық қалдықтардың түзілуі және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2022-12-27
approved_by:
- '165002000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/178142/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/178142/rus/27.12.2022
