act_code: '111720'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 3 апреля 2017 года № 13-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 2 мая 2017 года № 4170. Утратило силу решением Акжарского районного маслихата Северо-Казахстанской области от 7 ноября 2023 года № 11-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан в Акжарском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысының Ақжар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-04-03
approved_by:
- '165004000002'
version_date:
  kaz: 2023-07-05
  rus: 2023-07-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/111720/kaz/05.07.2023
  rus: https://zan.gov.kz/client/#!/doc/111720/rus/05.07.2023
caused_by:
  code: '183774'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 5 июля 2023 года № 5-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 июля 2023 года № 7552-15. Утратило силу решением Акжарского районного маслихата Северо-Казахстанской области от 7 ноября 2023 года № 11-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Акжарского районного маслихата Северо-Казахстанской области от 03 апреля 2017 года № 13-3 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категории нуждающихся граждан в Акжарском районе Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Ақжар аудандық мәслихатының 2017 жылғы 03 сәуірдегі № 13-3 «Солтүстік Қазақстан облысының Ақжар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183774/rus
