act_code: '128487'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 29 декабря 2018 года № 34/195. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 января 2019 года № 5197
title:
  rus: Об утверждении бюджета Явленского сельского округа Есильского района Северо-Казахстанской области на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Солтүстік Қазақстан облысы Есіл ауданы Явленка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '165006000002'
version_date:
  kaz: 2019-09-18
  rus: 2019-09-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/128487/kaz/18.09.2019
  rus: https://zan.gov.kz/client/#!/doc/128487/rus/18.09.2019
caused_by:
  code: '134765'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 18 сентября 2019 года № 41/245. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 сентября 2019 года № 5572
  title:
    rus: О внесении изменений в решение маслихата Есильского района Северо-Казахстанской области от 29 декабря 2018 года № 34/195 «Об утверждении бюджета Явленского сельского округа Есильского района Северо-Казахстанской области на 2019-2021 годы»
    kaz: Солтүстік Қазақстан облысы Есіл ауданы мәслихатының 2018 жылғы 29 желтоқсандағы № 34/195 «2019-2021 жылдарға арналған Солтүстік Қазақстан облысы Есіл ауданы Явленка ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134765/rus
