act_code: '151457'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 15 декабря 2020 года № 80/14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 декабря 2020 года № 6839
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требования к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования по Мамлютскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мамлют ауданы бойынша бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-15
approved_by:
- '165009000002'
version_date:
  kaz: 2023-01-16
  rus: 2023-01-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/151457/kaz/16.01.2023
  rus: https://zan.gov.kz/client/#!/doc/151457/rus/16.01.2023
caused_by:
  code: '178066'
  requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 16 января 2023 года № 33/3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 января 2023 года № 7434
  title:
    rus: О внесении изменения в решение маслихата Мамлютского района Северо-Казахстанской области от 15 декабря 2020 года № 80/14 «Об определении специализированных мест для организации и проведения мирных собраний, порядка использования специализированных мест для организации и проведения мирных собраний, нормы их предельной заполняемости, а также требования к материально-техническому и организационному обеспечению специализированных мест для организации и проведения мирных собраний, границ прилегающих территорий, в которых запрещено проведение пикетирования по Мамлютскому району Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Мамлют ауданы бойынша бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды пайдалану тәртібін, олардың шекті толу нормаларын, сондай-ақ бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы» Солтүстік Қазақстан облысы Мамлют ауданы мәслихатының 2020  жылғы 15 желтоқсандағы № 80/14 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/178066/rus
