act_code: '229314'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 20 августа 2026 года № 6-43 с
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-08-20
approved_by:
- '165013000002'
version_date:
  kaz: 2026-08-20
  rus: 2026-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/229314/kaz/20.08.2026
  rus: https://zan.gov.kz/client/#!/doc/229314/rus/20.08.2026
