act_code: '46049'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 27 апреля 2009 года № 4-15-3. Зарегистрировано Управлением юстиции Айыртауского района Северо-Казахстанской области 21 мая 2009 года № 13-3-100. Утратило силу - решением Айыртауского районного маслихата Северо-Казахстанской области от 25 июля 2012 года № 5-6-6
title:
  rus: О Правилах благоустройства и охраны зеленых насаждений в Айыртауском районе
  kaz: Айыртау ауданындағы көріктендіру және жасыл желекті екпелерді қорғау Ережесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-27
approved_by:
- '165003000002'
version_date:
  kaz: 2009-04-27
  rus: 2009-04-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/46049/kaz/27.04.2009
  rus: https://zan.gov.kz/client/#!/doc/46049/rus/27.04.2009
