act_code: '61868'
requisite: Решение акима Тимирязевского района Северо-Казахстанской области от 21 ноября 2011 года № 23. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 декабря 2011 года № 13-12-138. Утратило силу - решением акима Тимирязевского района Северо-Казахстанской области от 25 мая 2012 года № 15
title:
  rus: Об организации и обеспечении на территории Тимирязевского района приписки граждан Республики Казахстан мужского пола 1995 года рождения к призывному участку
  kaz: Шақыру учаскесіне 1995 жылы туылған Қазақстан Республикасының ер жынысты азаматтарын тіркеуін Тимирязев ауданының аймағында ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-21
approved_by:
- '165012000003'
version_date:
  kaz: 2011-11-21
  rus: 2011-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/61868/kaz/21.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61868/rus/21.11.2011
