act_code: '203447'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 27 ноября 2024 года № 8-21-12. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 ноября 2024 года № 7833-15
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога на 2025 год в Айыртауском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Айыртау ауданының 2025 жылға арналған бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-27
approved_by:
- '165003000002'
version_date:
  kaz: 2024-11-27
  rus: 2024-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/203447/kaz/27.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203447/rus/27.11.2024
