act_code: '5547'
requisite: Решение акима Северо-Казахстанской области от 22 ноября 1999 года № 216. Зарегистрировано Управлением юстиции Северо-Казахстанской области 19 января 2000 года за № 101. Утратило силу решением акима Северо-Казахстанской области от 20 декабря 2017 года № 41
title:
  rus: О Северо-Казахстанском областном центре обучения государственному языку
  kaz: Солтүстік Қазақстан облыстық мемлекеттік тілді оқыту орталығы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-11-22
approved_by:
- '165000000003'
version_date:
  kaz: 1999-11-22
  rus: 1999-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/5547/kaz/22.11.1999
  rus: https://zan.gov.kz/client/#!/doc/5547/rus/22.11.1999
