act_code: '218485'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 1 декабря 2025 года № 33-1
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима на основе упрощенной декларации на 2026 год в районе Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының 2026 жылға арналған оңайлатылған декларация негізінде арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-01
approved_by:
- '165015000002'
version_date:
  kaz: 2025-12-01
  rus: 2025-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/218485/kaz/01.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218485/rus/01.12.2025
