act_code: '49970'
requisite: Решение маслихата Северо-Казахстанской области от 29 декабря 2009 года № 20/5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 января 2010 года № 1735. Утратило силу - решением маслихата Северо-Казахстанской области от 13 декабря 2010 года № 30/17
title:
  rus: О ставках платы за эмиссии в окружающую среду на 2010 год
  kaz: Қоршаған ортаға эмиссия үшін 2010 жылға арналған төлем мөлшерлері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-29
approved_by:
- '165000000002'
version_date:
  kaz: 2010-07-23
  rus: 2010-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/49970/kaz/23.07.2010
  rus: https://zan.gov.kz/client/#!/doc/49970/rus/23.07.2010
caused_by:
  code: '53773'
  requisite: Решение маслихата Северо-Казахстанской области от 23 июля 2010 года № 27/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской 4 августа 2010 года № 1751. Утратило силу - решением маслихата Северо-Казахстанской области от 13 декабря 2010 года № 30/17
  title:
    rus: О внесении изменений в решение областного маслихата от 29 декабря 2009 года № 20/5 "О ставках платы за эмиссию в окружающую среду на 2010 год"
    kaz: '"Қоршаған ортаға эмиссия үшін 2010 жылға арналған төлем мөлшерлері туралы" 2009 жылғы 29 желтоқсандағы № 20/5 шешіміне өзгертулер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/53773/rus
