act_code: '176171'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 27 декабря 2022 года № 7-23-1
title:
  rus: Об утверждении бюджета Айыртауского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Айыртау ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '165003000002'
version_date:
  kaz: 2023-01-17
  rus: 2023-01-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/176171/kaz/17.01.2023
  rus: https://zan.gov.kz/client/#!/doc/176171/rus/17.01.2023
caused_by:
  code: '178072'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 17 января 2023 года № 7-24-5
  title:
    rus: О внесении изменений и дополнений в решение Айыртауского районного маслихата от 27 декабря 2022 года № 7-23-1 «Об утверждении бюджета Айыртауского района на 2023-2025 годы»
    kaz: «2023-2025 жылдарға арналған Айыртау ауданының бюджетін бекіту туралы» Айыртау аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 7-23-1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/178072/rus
