act_code: '176171'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 27 декабря 2022 года № 7-23-1
title:
  rus: Об утверждении бюджета Айыртауского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Айыртау ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '165003000002'
version_date:
  kaz: 2023-10-06
  rus: 2023-10-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/176171/kaz/06.10.2023
  rus: https://zan.gov.kz/client/#!/doc/176171/rus/06.10.2023
caused_by:
  code: '186926'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 6 октября 2023 года № 8-8-1
  title:
    rus: О внесении изменений в решение Айыртауского районного маслихата от 27 декабря 2022 года № 7-23-1 «Об утверждении бюджета Айыртауского района на 2023-2025 годы»
    kaz: «2023-2025 жылдарға арналған Айыртау ауданының бюджетін бекіту туралы» Айыртау аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 7-23-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/186926/rus
