act_code: '213438'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 18 августа 2025 года № 30-21
title:
  rus: Об отмене решения маслихата района Магжана Жумабаева Северо-Казахстанской области от 10 июня 2025 года № 28-2 «О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 20 марта 2024 года № 13-2 «Об определении размера и порядка оказания жилищной помощи в районе Магжана Жумабаева Северо-Казахстанской области»
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев аудандық мәслихатының 2025 жылғы 10 маусымдағы № 28-2 «Солтүстік Қазақстан облысы Мағжан Жұмабаев аудандық мәслихатының 2024 жылғы 20 наурыздағы № 13-2 «Мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер  енгізу туралы Мағжан Жұмабаев ауданында тұрғын үй  көмегін көрсету шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-18
approved_by:
- '165015000002'
version_date:
  kaz: 2025-08-18
  rus: 2025-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/213438/kaz/18.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213438/rus/18.08.2025
