act_code: '167558'
requisite: Решение акима Мичуринского сельского округа Тимирязевского района Северо-Казахстанской области от 29 апреля 2022 года № 8. Зарегистрирован в Министерстве юстиции Республики Казахстан 7 мая 2022 года № 27956
title:
  rus: О переименовании улиц села Мичурино Мичуринского сельского округа Тимирязевского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тимирязев ауданы Мичурин ауылдық округінің Мичурино ауылындағы көшелерді қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-29
approved_by:
- '165012012002'
version_date:
  kaz: 2022-04-29
  rus: 2022-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/167558/kaz/29.04.2022
  rus: https://zan.gov.kz/client/#!/doc/167558/rus/29.04.2022
