act_code: '129736'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 7 марта 2019 года № 33/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 марта 2019 года № 5255
title:
  rus: О предоставлении подъёмного пособия и социальной поддержки для приобретения или строительства жилья специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Жамбылского района Северо-Казахстанской области в 2019 году
  kaz: 2019 жылы Солтүстік Қазақстан облысы Жамбыл ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдау ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-03-07
approved_by:
- '165007000002'
version_date:
  kaz: 2019-07-16
  rus: 2019-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/129736/kaz/16.07.2019
  rus: https://zan.gov.kz/client/#!/doc/129736/rus/16.07.2019
caused_by:
  code: '133345'
  requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 16 июля 2019 года № 36/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 июля 2019 года № 5483
  title:
    rus: О внесении изменения в решение маслихата Жамбылского района от 7 марта 2019 года № 33/4 «О предоставлении подъёмного пособия и социальной поддержки для приобретения или строительства жилья специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Жамбылского района Северо-Казахстанской области в 2019 году»
    kaz: Жамбыл ауданы мәслихатының 2019 жылғы 7 наурыздағы № 33/4 «2019 жылы Солтүстік Қазақстан облысы Жамбыл ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға көтерме жәрдемақы және тұрғын үй сатып алу немесе салу үшін әлеуметтік қолдау ұсыну туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/133345/rus
