act_code: '63601'
requisite: Решение акима Новоишимского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 3 февраля 2012 года № 4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 февраля 2012 года № 13-5-142
title:
  rus: О наименовании улиц села Новоишимское Новоишимского сельского округа
  kaz: Новоишим ауылдық округ, Новоишим ауыл көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-02-03
approved_by:
- '165014001001'
version_date:
  kaz: 2018-07-02
  rus: 2018-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/63601/kaz/02.07.2018
  rus: https://zan.gov.kz/client/#!/doc/63601/rus/02.07.2018
caused_by:
  code: '123902'
  requisite: Решение акима Новоишимского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 2 июля 2018 года № 73. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 23 июля 2018 года № 4848
  title:
    rus: О внесении изменений в решение акима Новоишимского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 3 февраля 2012 года № 4 «О наименовании улиц села Новоишимское Новоишимского сельского округа»
    kaz: «Новоишим селолық округ, Новоишим село көшелеріне атау беру туралы» Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданның Новоишим селолық округі әкімінің 2012 жылғы 3 ақпандағы № 4 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123902/rus
