act_code: '77264'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 25 декабря 2013 года № 154. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 февраля 2014 года № 2543. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 28 октября 2016 года № 31
title:
  rus: Об утверждении регламента маслихата Тайыншинского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2013-12-25
approved_by:
- '165011000002'
version_date:
  kaz: 2013-12-25
  rus: 2013-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/77264/kaz/25.12.2013
  rus: https://zan.gov.kz/client/#!/doc/77264/rus/25.12.2013
