act_code: '159356'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 1 октября 2021 года № 8/6. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 октября 2021 года № 24719
title:
  rus: Об утверждении правил и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Кызылжарском районе
  kaz: Қызылжар ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу қағидалары мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-10-01
approved_by:
- '165008000002'
version_date:
  kaz: 2021-10-01
  rus: 2021-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/159356/kaz/01.10.2021
  rus: https://zan.gov.kz/client/#!/doc/159356/rus/01.10.2021
