act_code: '3450'
requisite: Решение Северо-Казахстанского областного маслихата от 5 февраля 1999 года № 20/3. Зарегистрировано Управлением юстиции Северо-Казахстанской области 18 марта 1999 года за № 66. Утратило силу решением Северо-Казахстанского областного маслихата от 21 декабря 2004 года № 12/7
title:
  rus: О состоянии окружающей среды в области и задачах по её охране в свете стратегии "Казахстан - 2030"
  kaz: Облыстағы қоршаған ортаның жайы және "Қазақстан-2030" стратегиясына сәйкес оны қорғау жөніндегі міндеттер туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 1999-02-05
approved_by:
- '165000000002'
version_date:
  kaz: 1999-02-05
  rus: 1999-02-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/3450/kaz/05.02.1999
  rus: https://zan.gov.kz/client/#!/doc/3450/rus/05.02.1999
