act_code: '97524'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 25 декабря 2015 года № 5-44-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 января 2016 года № 3545
title:
  rus: 'О бюджете Айыртауского района на 2016-2018 годы '
  kaz: '2016-2018 жылдарға арналған Айыртау ауданының бюджеті туралы '
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-25
approved_by:
- '165003000002'
version_date:
  kaz: 2016-07-12
  rus: 2016-07-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/97524/kaz/12.07.2016
  rus: https://zan.gov.kz/client/#!/doc/97524/rus/12.07.2016
caused_by:
  code: '104946'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 12 июля 2016 года № 6-4-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 июля 2016 года № 3843
  title:
    rus: О внесении изменений в решение Айыртауского районного маслихата от 25 декабря 2015 года № 5-44-1 «О бюджете Айыртауского района на 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған Айыртау ауданының бюджеті туралы» Айыртау аудандық мәслихатының 2015 жылғы 25 желтоқсандағы № 5-44-1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/104946/rus
