act_code: '179477'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 30 марта 2023 года № 8-5
title:
  rus: Об утверждении Положения коммунального государственного учреждения «Аппарат Акжарского районного маслихата Северо-Казахстанской области»
  kaz: «Солтүстік Қазақстан облысы Ақжар аудандық мәслихат аппараты» коммуналдық мемлекеттік мекемесінің Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2023-03-30
approved_by:
- '165004000002'
version_date:
  kaz: 2023-03-30
  rus: 2023-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/179477/kaz/30.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179477/rus/30.03.2023
