act_code: '187565'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 17 октября 2023 года № 9/118. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 24 октября 2023 года № 7604-15
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Есильском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Есіл ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-17
approved_by:
- '165006000002'
version_date:
  kaz: 2025-04-18
  rus: 2025-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/187565/kaz/18.04.2025
  rus: https://zan.gov.kz/client/#!/doc/187565/rus/18.04.2025
caused_by:
  code: '209409'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 18 апреля 2025 года № 26/405. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 апреля 2025 года № 7892-15
  title:
    rus: О внесении изменений в решение маслихата Есильского района Северо-Казахстанской области от 17 октября 2023 года № 9/118 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Есильском районе Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Есіл ауданы мәслихатының 2023 жылғы 17 қазандағы № 9/118 «Солтүстік Қазақстан облысы Есіл ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209409/rus
