act_code: '227145'
requisite: Решение акима Чистопольского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 1 июля 2026 года № 8
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-07-01
approved_by:
- '165014017002'
version_date:
  kaz: 2026-07-01
  rus: 2026-07-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/227145/kaz/01.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227145/rus/01.07.2026
