act_code: '138064'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 8 января 2020 года № 35-12. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2020 года № 5820
title:
  rus: Об утверждении бюджета Власовского сельского округа Аккайынского района на 2020 -2022 годы
  kaz: 2020-2022 жылдарға арналған Аққайың ауданының Власовка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165005000002'
version_date:
  kaz: 2020-10-29
  rus: 2020-10-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/138064/kaz/29.10.2020
  rus: https://zan.gov.kz/client/#!/doc/138064/rus/29.10.2020
caused_by:
  code: '147990'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 29 октября 2020 года № 42-19. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 октября 2020 года № 6614
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 8 января 2020 года № 35-12 «Об утверждении бюджета Власовского сельского округа Аккайынского района на 2020-2022 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2020 жылғы 8 қаңтардағы № 35-12 «2020-2022 жылдарға арналған Аққайың ауданы Власовка ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/147990/rus
