act_code: '138236'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 8 января 2020 года № 43/9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2020 года № 5888
title:
  rus: Об утверждении бюджета Жанажолского сельского округа района Шал акына на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Шал ақын ауданы Жаңажол ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165010000002'
version_date:
  kaz: 2020-12-07
  rus: 2020-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/138236/kaz/07.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138236/rus/07.12.2020
caused_by:
  code: '149558'
  requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 7 декабря 2020 года № 55/8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 декабря 2020 года № 6776
  title:
    rus: О внесении изменений в решение маслихата района Шал акына Северо-Казахстанской области от 8 января 2020 года № 43/9 «Об утверждении бюджета Жанажолского сельского округа района Шал акына на 2020-2022 годы»
    kaz: Солтүстік Қазақстан облысы Шал ақын ауданы мәслихатының 2020 жылғы 8 қаңтардағы № 43/9 «2020-2022 жылдарға арналған Шал ақын ауданы Жаңажол  ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149558/rus
