act_code: '138236'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 8 января 2020 года № 43/9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2020 года № 5888
title:
  rus: Об утверждении бюджета Жанажолского сельского округа района Шал акына на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Шал ақын ауданы Жаңажол ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165010000002'
version_date:
  kaz: 2020-01-08
  rus: 2020-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/138236/kaz/08.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138236/rus/08.01.2020
