act_code: '126677'
requisite: Решение акима Рассветского сельского округа Кызылжарского района Северо-Казахстанской области от 5 декабря 2018 года № 29. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 декабря 2018 года № 5057
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-05
approved_by:
- '165008016002'
version_date:
  kaz: 2018-12-05
  rus: 2018-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/126677/kaz/05.12.2018
  rus: https://zan.gov.kz/client/#!/doc/126677/rus/05.12.2018
