act_code: '118193'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 26 декабря 2017 года № 6-15-11. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 17 января 2018 года № 4535
title:
  rus: О бюджете Володарского сельского округа Айыртауского района на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Айыртау ауданы Володар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-26
approved_by:
- '165003000002'
version_date:
  kaz: 2018-05-31
  rus: 2018-05-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/118193/kaz/31.05.2018
  rus: https://zan.gov.kz/client/#!/doc/118193/rus/31.05.2018
caused_by:
  code: '122391'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 31 мая 2018 года № 6-20-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 июня 2018 года № 4752
  title:
    rus: О внесении изменения и дополнения в решение Айыртауского районного маслихата от 26 декабря 2017 года № 6-15-11 «О бюджете Володарского сельского округа Айыртауского района на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Айыртау ауданы Володар ауылдық округінің бюджеті туралы» Айыртау аудандық мәслихатының 2017 жылғы 26 желтоқсандағы № 6-15-11 шешіміне өзгеріс пен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122391/rus
