act_code: '2852'
requisite: Решение XV сессии Северо-Казахстанского областного маслихата от 30 января 1998 года № 15/1. Зарегистрировано Управлением юстиции Северо-Казахстанской области 27 декабря 1998 года № 50. Утратило силу - решением маслихата Северо-Казахстанской области от 19 августа 2011 года № 37/4
title:
  rus: О ходе выполнения программы по углублению реформ в области на 1996-1998 годы в части развития промышленности
  kaz: '"Облыста реформаны тереңдету жөніндегі 1996-1998 жылдарға арналған бағдарламаның өнеркәсіпті дамыту бөлімінің орындалу барысы туралы"'
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-01-30
approved_by:
- '165000000002'
version_date:
  kaz: 1998-01-30
  rus: 1998-01-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/2852/kaz/30.01.1998
  rus: https://zan.gov.kz/client/#!/doc/2852/rus/30.01.1998
