act_code: '45324'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 14 марта 2009 года № 13/4. Зарегистрировано Управлением юстиции Мамлютского района Северо-Казахстанской области 17 апреля 2009 года № 13-10-80. Утратило силу решением маслихата Мамлютского района Северо-Казахстанской области от 26 марта 2018 года № 26/3
title:
  rus: О ставках земельного налога
  kaz: Жер салығының ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-03-14
approved_by:
- '165009000002'
version_date:
  kaz: 2009-03-14
  rus: 2009-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/45324/kaz/14.03.2009
  rus: https://zan.gov.kz/client/#!/doc/45324/rus/14.03.2009
