act_code: '192531'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 29 декабря 2023 года № 114/9
title:
  rus: Об утверждении бюджета Драгомировского сельского округа Тайыншинского района Северо-Казахстанской области на 2024-2026 годы
  kaz: Солтүстік Қазақстан облысы Тайынша ауданы Драгомиров ауылдық округінің 2024–2026 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '165011000002'
version_date:
  kaz: 2024-04-19
  rus: 2024-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/192531/kaz/19.04.2024
  rus: https://zan.gov.kz/client/#!/doc/192531/rus/19.04.2024
caused_by:
  code: '196003'
  requisite: Решение Тайыншинского районного маслихата Северо-Казахстанской области от 19 апреля 2024 года № 156/13
  title:
    rus: О внесении изменений и дополнений в решение маслихата Тайыншинского района Северо-Казахстанской области от 29 декабря 2023 года № 114/9 «Об утверждении бюджета Драгомировского сельского округа Тайыншинского района Северо-Казахстанской области на 2024-2026 годы»
    kaz: «Солтүстік Қазақстан облысы Тайынша ауданы Драгомиров ауылдық округінің 2024-2026 жылдарға арналған бюджетін бекіту туралы» Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2023 жылғы 29 желтоқсандағы № 114/9 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196003/rus
