act_code: '163419'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2021 года № 8-18
title:
  rus: Об утверждении бюджета Киялинского сельского округа Аккайынского района на 2022 -2024 годы
  kaz: 2022-2024 жылдарға арналған Аққайың ауданының Қиялы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '165005000002'
version_date:
  kaz: 2022-06-21
  rus: 2022-06-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/163419/kaz/21.06.2022
  rus: https://zan.gov.kz/client/#!/doc/163419/rus/21.06.2022
caused_by:
  code: '169337'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 21 июня 2022 года № 15-5
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2021 года № 8-18 «Об утверждении бюджета Киялинского сельского округа Аккайынского района на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2021 жылғы 30 желтоқсандағы № 8-18 «2022-2024 жылдарға арналған Аққайың ауданының Қиялы ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/169337/rus
