act_code: '131788'
requisite: Решение акима Березовского сельского округа Кызылжарского района Северо-Казахстанской области от 21 мая 2019 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 23 мая 2019 года № 5413. Утратило силу решением акима Березовского сельского округа Кызылжарского района Северо-Казахстанской области от 24 сентября 2019 года № 11 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-05-21
approved_by:
- '165008003002'
version_date:
  kaz: 2019-05-21
  rus: 2019-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/131788/kaz/21.05.2019
  rus: https://zan.gov.kz/client/#!/doc/131788/rus/21.05.2019
