act_code: '172450'
requisite: Решение Северо-Казахстанского областного маслихата от 28 сентября 2022 года № 21/3
title:
  rus: Об утверждении правил содержания и выгула домашних животных на территории населенных пунктов Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы елді мекендерінің аумағында үй жануарларын ұстау және серуендету қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2022-09-28
approved_by:
- '165000000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/172450/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/172450/rus/15.12.2023
caused_by:
  code: '190646'
  requisite: Решение Северо-Казахстанского областного маслихата от 15 декабря 2023 года № 9/3
  title:
    rus: О внесении изменения в решение Северо-Казахстанского областного маслихата от 28 сентября 2022 года № 21/3 «Об утверждении правил содержания и выгула домашних животных на территории населенных пунктов Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы елді мекендерінің аумағында үй жануарларын ұстау және серуендету қағидаларын бекіту туралы» Солтүстік Қазақстан облыстық мәслихатының 2022 жылғы 28 қыркүйектегі № 21/3 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190646/rus
