act_code: '163407'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2021 года № 8-15
title:
  rus: Об утверждении бюджета Власовского сельского округа Аккайынского района на 2022 -2024 годы
  kaz: 2022-2024  жылдарға арналған Аққайың ауданының Власовка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-30
approved_by:
- '165005000002'
version_date:
  kaz: 2022-03-25
  rus: 2022-03-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/163407/kaz/25.03.2022
  rus: https://zan.gov.kz/client/#!/doc/163407/rus/25.03.2022
caused_by:
  code: '166037'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 25 марта 2022 года № 9-25
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 30 декабря 2021 года № 8-15 «Об утверждении бюджета Власовского сельского округа Аккайынского района на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданыны мәслихатының 2021 жылғы 30 желтоқсандағы № 8-15 «2022-2024 жылдарға арналған Аққайың ауданының Власовка ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/166037/rus
