act_code: '204976'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 25 декабря 2024 года № 22/1. Утратило силу решением Тимирязевского районного маслихата Северо-Казахстанской области от 6 мая 2025 года № 24/1 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении районного бюджета Тимирязевского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Тимирязев ауданының аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '165012000002'
version_date:
  kaz: 2025-03-05
  rus: 2025-03-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/204976/kaz/05.03.2025
  rus: https://zan.gov.kz/client/#!/doc/204976/rus/05.03.2025
caused_by:
  code: '207997'
  requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 5 марта 2025 года № 23/5. Утратило силу решением Тимирязевского районного маслихата Северо-Казахстанской области от 6 мая 2025 года № 24/1 (вводится в действие с 1 января 2025 года)
  title:
    rus: О внесении изменений и дополнений в решение Тимирязевского районного маслихата от 25 декабря 2024 года № 22/1 «Об утверждении районного бюджета Тимирязевского района на 2025-2027 годы»
    kaz: «2025-2027 жылдарға арналған Тимирязев ауданының аудандық бюджетін бекіту туралы» Тимирязев аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 22/1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207997/rus
