act_code: '127480'
requisite: Решение акима Тайыншинского района Северо-Казахстанской области от 24 декабря 2018 года № 44. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 декабря 2018 года № 5098
title:
  rus: Об образовании избирательных участков на территории Тайыншинского района
  kaz: Тайынша ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '165011000003'
version_date:
  kaz: 2022-08-27
  rus: 2022-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/127480/kaz/27.08.2022
  rus: https://zan.gov.kz/client/#!/doc/127480/rus/27.08.2022
caused_by:
  code: '171203'
  requisite: Решение акима Тайыншинского района Северо-Казахстанской области от 27 августа 2022 года № 25. Зарегистрировано в Министерстве юстиции Республики Казахстан 5 сентября 2022 года № 29402
  title:
    rus: О внесении изменения в решение акима Тайыншинского района Северо-Казахстанской области от 24 декабря 2018 года № 44 «Об образовании избирательных участков на территории Тайыншинского района»
    kaz: «Тайынша ауданының аумағында сайлау учаскелерін құру туралы» Солтүстік Қазақстан облысы Тайынша ауданы әкімінің 2018 жылғы 24 желтоқсандағы № 44 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/171203/rus
