act_code: '162669'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 24 декабря 2021 года № 110. Отменен решением маслихата Тайыншинского района Северо-Казахстанской области от 13 мая 2022 года № 190 (вводится в действие по истечении десяти календарных дней после дня первого официального опубликования)
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума по Тайыншинскому району Северо-Казахстанской области на 2022 год
  kaz: 2022 жылға арналған Солтүстік Қазақстан облысы Тайынша ауданы бойынша кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '165011000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162669/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162669/rus/24.12.2021
