act_code: '53384'
requisite: Решение акима Кировского сельского округа Тайыншинского района Северо-Казахстанской области от 25 июня 2010 года № 7. Зарегистрировано Управлением юстиции Тайыншинского района Северо-Казахстанской области 3 июля 2010 года № 13-11-183
title:
  rus: О присвоении наименований составных частей населенных пунктов Кировского сельского округа Тайыншинского района
  kaz: Тайынша ауданы Киров ауылдық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-06-25
approved_by:
- '165011011002'
version_date:
  kaz: 2018-06-26
  rus: 2018-06-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/53384/kaz/26.06.2018
  rus: https://zan.gov.kz/client/#!/doc/53384/rus/26.06.2018
caused_by:
  code: '123326'
  requisite: Решение акима Кировского сельского округа Тайыншинского района Северо-Казахстанской области от 26 июня 2018 года № 03. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июля 2018 года № 4811
  title:
    rus: О внесении изменений в решение акима Кировского сельского округа Тайыншинского района Северо-Казахстанской области от 25 июня 2010 года № 07 «О присвоении наименований составных частей населенных пунктов Кировского сельского округа Тайыншинского района»
    kaz: «Тайынша ауданы Киров селолық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы» Солтүстік Қазақстан облысы Тайынша ауданы Киров ауылдық округі әкімінің 2010 жылғы 25 маусымдағы № 07 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123326/rus
