act_code: '192495'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 29 декабря 2023 года № 11-1
title:
  rus: Об утверждении бюджета Авангардского сельского округа района Магжана Жумабаева на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Мағжан Жұмабаев ауданы Авангард ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '165015000002'
version_date:
  kaz: 2024-12-12
  rus: 2024-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/192495/kaz/12.12.2024
  rus: https://zan.gov.kz/client/#!/doc/192495/rus/12.12.2024
caused_by:
  code: '204265'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 12 декабря 2024 года № 21-5
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 29 декабря 2023 года № 11-1 «Об утверждении бюджета Авангардского сельского округа района Магжана Жумабаева на 2024-2026 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2023 жылғы 29 желтоқсандағы № 11-1 «2024-2026 жылдарға арналған Мағжан Жұмабаев ауданы Авангард ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204265/rus
