act_code: '194644'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 19 марта 2024 года № 4-16 с. Зарегистрирован в Департаменте юстиции Северо-Казахстанской области 20 марта 2024 года № 7721-15
title:
  rus: Об определении размера и правил оказания жилищной помощи в Уалихановском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданында тұрғын үй көмегін көрсетудің мөлшері мен қағидасын айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-03-19
approved_by:
- '165013000002'
version_date:
  kaz: 2024-03-19
  rus: 2024-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/194644/kaz/19.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194644/rus/19.03.2024
