act_code: '152153'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 8 января 2021 года № 56/6. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 января 2021 года № 7024
title:
  rus: Об утверждении бюджета Афанасьевского сельского округа района Шал акына на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Шал ақын ауданы Афанасьев ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '165010000002'
version_date:
  kaz: 2021-01-08
  rus: 2021-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/152153/kaz/08.01.2021
  rus: https://zan.gov.kz/client/#!/doc/152153/rus/08.01.2021
