act_code: '76881'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 23 декабря 2013 года № 21-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 января 2014 года № 2497
title:
  rus: О бюджете района Магжана Жумабаева Северо-Казахстанской области на 2014-2016 годы
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының 2014-2016 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-23
approved_by:
- '165015000002'
version_date:
  kaz: 2014-04-14
  rus: 2014-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/76881/kaz/14.04.2014
  rus: https://zan.gov.kz/client/#!/doc/76881/rus/14.04.2014
caused_by:
  code: '79441'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 14 апреля 2014 года № 27-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 апреля 2014 года № 2694
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 23 декабря 2013 года № 21-1 "О бюджете района Магжана Жумабаева Северо-Казахстанской области на 2014-2016 годы"
    kaz: '"Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының 2014-2016 жылдарға арналған бюджеті туралы" Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2013 жылғы 23 желтоқсандағы № 21-1 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/79441/rus
