act_code: '128209'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 28 декабря 2018 года № 30/2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2019 года № 5163
title:
  rus: Об утверждении бюджета Благовещенского сельского округа Жамбылского района Северо-Казахстанской области на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Солтүстік Қазақстан облысы Жамбыл ауданы Благовещенка ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-28
approved_by:
- '165007000002'
version_date:
  kaz: 2019-12-26
  rus: 2019-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/128209/kaz/26.12.2019
  rus: https://zan.gov.kz/client/#!/doc/128209/rus/26.12.2019
caused_by:
  code: '137678'
  requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 26 декабря 2019 года № 43/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 декабря 2019 года № 5767
  title:
    rus: О внесении изменений в решение маслихата Жамбылского района от 28 декабря 2018 года № 30/2 «Об утверждении бюджета Благовещенского сельского округа Жамбылского района Северо-Казахстанской области на 2019-2021 годы»
    kaz: Жамбыл ауданы маслихатының 2018 жылғы 28 желтоқсандағы № 30/2 «2019-2021 жылдарға арналған Солтүстік Қазақстан облысы Жамбыл ауданы Благовещенка ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/137678/rus
