act_code: '51488'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 1 марта 2010 года № 22/3. Зарегистрировано Управлением юстиции Кызылжарского района Северо-Казахстанской области 31 марта 2010 года № 13-8-120. Утратило силу - решением маслихата Кызылжарского района Северо-Казахстанской области от 30 июля 2012 года № 7/5
title:
  rus: Об оказании социальной помощи на санаторно-курортное лечение гражданам Кызылжарского района
  kaz: Қызылжар ауданының санаторлық-курорттық емделуге мұқтаж жеке санаттағы азаматтарына әлеуметтік көмек беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-01
approved_by:
- '165008000002'
version_date:
  kaz: 2010-06-09
  rus: 2010-06-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/51488/kaz/09.06.2010
  rus: https://zan.gov.kz/client/#!/doc/51488/rus/09.06.2010
caused_by:
  code: '53487'
  requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 9 июня 2010 года № 25/5. Зарегистрировано Управлением юстиции Кызылжарского района Северо-Казахстанской области 14 июля 2010 года № 13-8-130. Утратило силу - решением маслихата Кызылжарского района Северо-Казахстанской области от 30 июля 2012 года № 7/5
  title:
    rus: О внесении дополнений в решение районного маслихата от 1 марта 2010 года № 22/3 "Об оказании социальной помощи на санаторно-курортное лечение гражданам Кызылжарского района"
    kaz: 2010 жылғы 1 наурыздағы № 22/3 "Қызылжар ауданының санаторлық-курорттық емделуге мұқтаж жеке санаттағы азаматтарына әлеуметтік көмек беру туралы" аудандық мәслихаттың шешіміне толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/53487/rus
