act_code: '56957'
requisite: Решение маслихата города Петропавловска Северо-Казахстанской области от 27 декабря 2010 года № 1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 января 2011 года № 13-1-188
title:
  rus: О бюджете города Петропавловска на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған Петропавл қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-27
approved_by:
- '165002000002'
version_date:
  kaz: 2011-05-12
  rus: 2011-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/56957/kaz/12.05.2011
  rus: https://zan.gov.kz/client/#!/doc/56957/rus/12.05.2011
caused_by:
  code: '59037'
  requisite: Решение маслихата города Петропавловска Северо-Казахстанской области от 12 мая 2011 года № 1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 мая 2011 года № 13-1-197
  title:
    rus: О внесении изменений в решение 33 сессии Петропавловского городского маслихата от 27 декабря 2010 года № 1 "О бюджете города Петропавловска на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған Петропавл қаласының бюджеті туралы" Петропавл қалалық мәслихаты 33 сессиясының 2010 жылғы 27 желтоқсандағы № 1 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/59037/rus
