act_code: '207920'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 27 февраля 2025 года № 4/21
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума в городе Петропавловск на 2025 год
  kaz: 2025 жылға арналған Петропавл қаласындағы кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-02-27
approved_by:
- '165002000002'
version_date:
  kaz: 2025-02-27
  rus: 2025-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/207920/kaz/27.02.2025
  rus: https://zan.gov.kz/client/#!/doc/207920/rus/27.02.2025
