act_code: '95337'
requisite: Решение акима Кызылжарского района Северо-Казахстанской области от 23 октября 2015 года № 19. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 18 ноября 2015 года № 3463
title:
  rus: Об организации и обеспечении на территории Кызылжарского района Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2016 года
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданының аумағында 2016 жылғы қаңтар - наурыз аралығында Қазақстан Республикасы ер азаматтарын әскери есепке алу және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-10-23
approved_by:
- '165008000001'
version_date:
  kaz: 2015-10-23
  rus: 2015-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/95337/kaz/23.10.2015
  rus: https://zan.gov.kz/client/#!/doc/95337/rus/23.10.2015
