act_code: '188587'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 13 ноября 2023 года № 86. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 20 ноября 2023 года № 7626-15
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Тайыншинского района
  kaz: Тайынша ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария мемлекеттік ұйымдарының мамандарына бюджет қаражаты есебінен коммуналдық қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсетудің тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-13
approved_by:
- '165011000002'
version_date:
  kaz: 2023-11-13
  rus: 2023-11-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/188587/kaz/13.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188587/rus/13.11.2023
