act_code: '152437'
requisite: Решение акима Аралагашского сельского округа Аккайынского района Северо-Казахстанской области от 20 января 2021 года № 1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 января 2021 года № 7099
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-20
approved_by:
- '165005001002'
version_date:
  kaz: 2021-01-20
  rus: 2021-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/152437/kaz/20.01.2021
  rus: https://zan.gov.kz/client/#!/doc/152437/rus/20.01.2021
