act_code: '47698'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 29 июля 2009 года № 15-3. Зарегистрировано Управлением юстиции Аккайынского района Северо-Казахстанской области 9 сентября 2009 года № 13-2-108. Утратило силу - решением маслихата Аккайынского района Северо-Казахстанской области от 18 июля 2012 года № 5-11
title:
  rus: О правилах благоустройства и санитарной очистки населенных пунктов, содержания и защиты зеленых насаждений и объектов инфраструктуры Аккайынского района
  kaz: Аққайың ауданының елді мекендерін көркейту және санитарлық тазалау, жасыл көшеттер мен инфрақұрылым объектілерін ұстау және қорғау ережелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-07-29
approved_by:
- '165005000002'
version_date:
  kaz: 2009-07-29
  rus: 2009-07-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/47698/kaz/29.07.2009
  rus: https://zan.gov.kz/client/#!/doc/47698/rus/29.07.2009
