act_code: '184076'
requisite: Решение акима Аккайынского района Северо-Казахстанской области от 14 июля 2023 года № 142. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 июля 2023 года № 7559-15
title:
  rus: Об образовании избирательных участков на территории Аккайынского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-14
approved_by:
- '165005000003'
version_date:
  kaz: 2025-04-02
  rus: 2025-04-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/184076/kaz/02.04.2025
  rus: https://zan.gov.kz/client/#!/doc/184076/rus/02.04.2025
caused_by:
  code: '208969'
  requisite: Решение акима Аккайынского района Северо-Казахстанской области от 2 апреля 2025 года № 3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 8 апреля 2025 года № 7884-15
  title:
    rus: О внесении изменений в решение акима Аккайынского района Северо-Казахстанской области от 14 июля 2023 года № 142 «Об образовании избирательных участков на территории Аккайынского района Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Аққайың ауданының аумағында сайлау учаскелерін құру туралы» Солтүстік Қазақстан облысы Аққайың ауданы әкімінің 2023 жылғы 14 шілдедегі № 142 шешіміне өзгертулер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208969/rus
