act_code: '9022'
requisite: Решение акима Северо-Казахстанской области от 6 апреля 2001 года № 41. Зарегистрировано Управлением юстиции Северо-Казахстанской области 12 апреля 2001 года за № 287
title:
  rus: Об открытии весенней охоты по области в 2001 году
  kaz: 2001 жылы облыс бойынша көктемгі аңшылыкты ашу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-04-05
approved_by:
- '165000000003'
version_date:
  kaz: 2001-04-05
  rus: 2001-04-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/9022/kaz/05.04.2001
  rus: https://zan.gov.kz/client/#!/doc/9022/rus/05.04.2001
