act_code: '140405'
requisite: Решение Северо-Казахстанского областного маслихата от 11 марта 2020 года № 40/5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 марта 2020 года № 6102. Утратило силу решением Северо-Казахстанского областного маслихата от 7 октября 2020 года № 48/13 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно
  kaz: Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-11
approved_by:
- '165000000002'
version_date:
  kaz: 2020-05-28
  rus: 2020-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/140405/kaz/28.05.2020
  rus: https://zan.gov.kz/client/#!/doc/140405/rus/28.05.2020
caused_by:
  code: '143541'
  requisite: Решение Северо-Казахстанского областного маслихата от 28 мая 2020 года № 43/7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июня 2020 года № 6329. Утратило силу решением Северо-Казахстанского областного маслихата от 7 октября 2020 года № 48/13 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Северо-Казахстанского областного маслихата от 11 марта 2020 года № 40/5 «О дополнительном предоставлении лекарственных средств отдельным категориям граждан при амбулаторном лечении бесплатно»
    kaz: Солтүстік Қазақстан облыстық мәслихатының 2020 жылғы 11 наурыздағы № 40/5 «Азаматтардың жекелеген санаттарына амбулаториялық емдеу кезінде тегін дәрілік заттарды қосымша беру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/143541/rus
