act_code: '62569'
requisite: Решение маслихата Тимирязевского района Северо-Казахстанской области от 5 декабря 2011 года № 39/2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2012 года № 13-12-140. Утратило силу решением Тимирязевского районного маслихата Северо-Казахстанской области от 12 марта 2018 года № 21/7
title:
  rus: О единых ставках фиксированного налога
  kaz: Тіркелген салықтың бірыңғай ставкалары туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-05
approved_by:
- '165012000002'
version_date:
  kaz: 2011-12-05
  rus: 2011-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/62569/kaz/05.12.2011
  rus: https://zan.gov.kz/client/#!/doc/62569/rus/05.12.2011
