act_code: '56825'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 22 декабря 2010 года № 36/208. Зарегистрировано Управлением юстиции Есильского района Северо-Казахстанской области 19 января 2011 года № 13-6-159. Утратило силу в связи с истечением срока действия (письмо маслихата Есильского района Северо-Казахстанской области от 11 января 2013 года № 01-21/9)
title:
  rus: О районном бюджете на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-22
approved_by:
- '165006000002'
version_date:
  kaz: 2011-11-21
  rus: 2011-11-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/56825/kaz/21.11.2011
  rus: https://zan.gov.kz/client/#!/doc/56825/rus/21.11.2011
caused_by:
  code: '61888'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 21 ноября 2011 года № 49/269. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 декабря 2011 года № 13-6-180. Утратило силу в связи с истечением срока действия (письмо маслихата Есильского района Северо-Казахстанской области от 11 января 2013 года № 01-21/9)
  title:
    rus: О внесении изменений и дополнений в решение районного маслихата от 22 декабря 2010 года № 36/208 "О районном бюджете на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған аудандық бюджет туралы" аудандық мәслихаттың 2010 жылғы 22 желтоқсандағы № 36/208 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/61888/rus
