act_code: '176677'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 26 декабря 2022 года № 21-1
title:
  rus: Об утверждении бюджета района Магжана Жумабаева Северо-Казахстанской области на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-26
approved_by:
- '165015000002'
version_date:
  kaz: 2023-07-11
  rus: 2023-07-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/176677/kaz/11.07.2023
  rus: https://zan.gov.kz/client/#!/doc/176677/rus/11.07.2023
caused_by:
  code: '184024'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 11 июля 2023 года № 5-1
  title:
    rus: О внесении изменений и дополнений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 26 декабря 2022 года № 21-1 «Об утверждении бюджета района Магжана Жумабаева Северо-Казахстанской области на 2023-2025 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2022 жылғы 26 желтоқсандағы № 21-1 «2023-2025 жылдарға арналған Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/184024/rus
