act_code: '1038'
requisite: Решение акима Северо-Казахстанской области от 25 ноября 1997 года № 239. Зарегистрировано Управлением юстиции Северо-Казахстанской области 19 июня 1998 года за № 23. Утратило силу - решением акима Северо-Казахстанской области от 27 декабря 2007 года № 38
title:
  rus: О дисциплинарном совете при акиме Северо-Казахстанской области
  kaz: Солтүстік Қазақстан әкімі жанындағы тәртіп кеңесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1997-11-25
approved_by:
- '165000000003'
version_date:
  kaz: 1997-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/1038/kaz/25.11.1997
