act_code: '75653'
requisite: Решение акима Есильского района Северо-Казахстанской области от 13 ноября 2013 года № 12. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 декабря 2013 года № 2415. Утратило силу (письмо заместителя акима Есильского района Северо-Казахстанской области от 4 мая 2014 года № 7.1.8.-12/184)
title:
  rus: Об организации и обеспечении на территории Есильского района Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2014 года.
  kaz: Қазақстан Республикасының ер азаматтарын 2014 жылдың қаңтарынан наурызына дейін Солтүстік Қазақстан облысы Есіл ауданының аумағында тіркеуді және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-11-13
approved_by:
- '165006000003'
version_date:
  kaz: 2013-11-13
  rus: 2013-11-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/75653/kaz/13.11.2013
  rus: https://zan.gov.kz/client/#!/doc/75653/rus/13.11.2013
