act_code: '176934'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 29 декабря 2022 года № 25-5
title:
  rus: Об утверждении бюджета Кокалажарского сельского округа района имени Габита Мусрепова на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Көкалажар ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '165014000002'
version_date:
  kaz: 2023-11-14
  rus: 2023-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/176934/kaz/14.11.2023
  rus: https://zan.gov.kz/client/#!/doc/176934/rus/14.11.2023
caused_by:
  code: '188687'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 14 ноября 2023 года № 10-20
  title:
    rus: О внесении изменений в решение маслихата района имени Габита Мусрепова от 29 декабря 2022 года № 25-5 «Об утверждении бюджета Кокалажарского сельского округа района имени Габита Мусрепова на 2023-2025 годы»
    kaz: Ғабит Мүсірепов атындағы ауданы мәслихатының 2022 жылғы 29 желтоқсандағы № 25-5 «2023-2025 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Көкалажар ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/188687/rus
