act_code: '118136'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 25 декабря 2017 года № 22/14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 17 января 2018 года № 4520
title:
  rus: О бюджете Куйбышевского сельского округа Кызылжарского района на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Қызылжар ауданының Куйбышев ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '165008000002'
version_date:
  kaz: 2018-06-22
  rus: 2018-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/118136/kaz/22.06.2018
  rus: https://zan.gov.kz/client/#!/doc/118136/rus/22.06.2018
caused_by:
  code: '123120'
  requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 22 июня 2018 года № 28/8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июля 2018 года № 4802
  title:
    rus: О внесении изменений в решение Кызылжарского районного маслихата Северо-Казахстанской области от 25 декабря 2017 года №22/14 «О бюджете Куйбышевского сельского округа Кызылжарского района на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Қызылжар ауданының Куйбышев ауылдық округінің бюджеті туралы» Солтүстік Қазақстан облысы Қызылжар аудандық мәслихатының 2017 жылғы 25 желтоқсандағы № 22/14 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123120/rus
