act_code: '146380'
requisite: Решение акима Кырымбетского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 10 сентября 2020 года № 7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 сентября 2020 года № 6530
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-09-10
approved_by:
- '165014008002'
version_date:
  kaz: 2020-09-10
  rus: 2020-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/146380/kaz/10.09.2020
  rus: https://zan.gov.kz/client/#!/doc/146380/rus/10.09.2020
