act_code: '57097'
requisite: Решение маслихата Тимирязевского района Северо-Казахстанской области от 24 декабря 2010 года № 28/2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 января 2011 года № 13-12-121. Утратило силу - решением маслихата Тимирязевского района Северо-Казахстанской области от 16 апреля 2012 года № 3/3
title:
  rus: О районном бюджете Тимирязевского района на 2011-2013 годы
  kaz: 2011-2013 жылдарға арналған Тимирязев ауданының аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-12-24
approved_by:
- '165012000002'
version_date:
  kaz: 2011-05-11
  rus: 2011-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/57097/kaz/11.05.2011
  rus: https://zan.gov.kz/client/#!/doc/57097/rus/11.05.2011
caused_by:
  code: '59070'
  requisite: Решение маслихата Тимирязевского района Северо-Казахстанской области от 11 мая 2011 года № 32/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 1 июня 2011 года № 13-12-127. Утратило силу - решением маслихата Тимирязевского района Северо-Казахстанской области от 16 апреля 2012 года № 3/3
  title:
    rus: О внесении изменений в решение Тимирязевского районного маслихата от 24 декабря 2010 года № 28/2 "О районном бюджете Тимирязевского района на 2011-2013 годы"
    kaz: '"2011-2013 жылдарға арналған Тимирязев ауданының бюджеті туралы" Тимирязев аудандық мәслихатының 2010 жылғы 24 желтоқсандағы № 28/2 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/59070/rus
