act_code: '165252'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 4 марта 2022 года № 12/10. Утратило силу решением Кызылжарского районного маслихата Северо-Казахстанской области от 27 сентября 2023 года № 5/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей жителей села, улицы для участия в сходе местного сообщества в Кызылжарском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауыл, көше тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-04
approved_by:
- '165008000002'
version_date:
  kaz: 2022-03-04
  rus: 2022-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/165252/kaz/04.03.2022
  rus: https://zan.gov.kz/client/#!/doc/165252/rus/04.03.2022
