act_code: '152018'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 8 января 2021 года № 9-66 с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 января 2021 года № 7002
title:
  rus: Об утверждении бюджета Карасуского сельского округа Уалихановского района на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Уәлиханов ауданы Қарасу ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '165013000002'
version_date:
  kaz: 2021-11-12
  rus: 2021-11-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/152018/kaz/12.11.2021
  rus: https://zan.gov.kz/client/#!/doc/152018/rus/12.11.2021
caused_by:
  code: '160908'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 12 ноября 2021 года № 9-11 с
  title:
    rus: О внесении изменений в решение Уалихановского районного маслихата от 8 января 2021 года № 9-66 с «Об утверждении бюджета Карасуского сельского округа Уалихановского района на 2021-2023 годы»
    kaz: Уәлиханов аудандық мәслихатының 2021 жылғы 8 қаңтардағы № 9-66 с «2021-2023 жылдарға арналған Уәлиханов ауданы Қарасу ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160908/rus
