act_code: '151253'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 25 декабря 2020 года № 71-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 декабря 2020 года № 6870
title:
  rus: Об утверждении бюджета района имени Габита Мусрепова на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Ғабит Мүсірепов атындағы ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '165014000002'
version_date:
  kaz: 2021-06-18
  rus: 2021-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/151253/kaz/18.06.2021
  rus: https://zan.gov.kz/client/#!/doc/151253/rus/18.06.2021
caused_by:
  code: '156763'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 18 июня 2021 года № 6-1. Зарегистрировано в Министерстве юстиции Республики Казахстан 7 июля 2021 года № 23310
  title:
    rus: О внесении изменений в решение маслихата района имени Габита Мусрепова от 25 декабря 2020 года № 71-2 «Об утверждении бюджета района имени Габита Мусрепова на 2021-2023 годы»
    kaz: Ғабит Мүсірепов атындағы ауданы мәслихатының 2020 жылғы 25 желтоқсандағы № 71-2 «2021-2023 жылдарға арналған Ғабит Мүсірепов атындағы ауданының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/156763/rus
