act_code: '195628'
requisite: Решение акима Докучаевского сельского округа Тимирязевского района Северо-Казахстанской области от 9 апреля 2024 года № 4. Утратило силу решением и.о. акима Докучаевского сельского округа Тимирязевского района Северо-Казахстанской области от 12 июня 2024 года № 6 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-09
approved_by:
- '165012007002'
version_date:
  kaz: 2024-04-09
  rus: 2024-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/195628/kaz/09.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195628/rus/09.04.2024
