act_code: '162011'
requisite: Решение Северо-Казахстанского областного маслихата от 10 декабря 2021 года № 12/1. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 декабря 2021 года № 25929
title:
  rus: Об утверждении областного бюджета Северо-Казахстанской области на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Солтүстік Қазақстан облысының облыстық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-10
approved_by:
- '165000000002'
version_date:
  kaz: 2022-11-09
  rus: 2022-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/162011/kaz/09.11.2022
  rus: https://zan.gov.kz/client/#!/doc/162011/rus/09.11.2022
caused_by:
  code: '173726'
  requisite: Решение Северо-Казахстанского областного маслихата от 9 ноября 2022 года № 22/3. Зарегистрировано в Министерстве юстиции Республики Казахстан 15 ноября 2022 года № 30544
  title:
    rus: О внесении изменений и дополнения в решение Северо-Казахстанского областного маслихата от 10 декабря 2021 года № 12/1 «Об утверждении областного бюджета Северо-Казахстанской области на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облыстық мәслихатының 2021 жылғы 10 желтоқсандағы № 12/1 «2022-2024 жылдарға арналған Солтүстік Қазақстан облысының облыстық бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173726/rus
