act_code: '149465'
requisite: Решение акима Соколовского сельского округа Кызылжарского района Северо-Казахстанской области от 7 декабря 2020 года № 41. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 8 декабря 2020 года № 6769
title:
  rus: О снятии карантина
  kaz: Карантинді тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-07
approved_by:
- '165008019002'
version_date:
  kaz: 2020-12-07
  rus: 2020-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/149465/kaz/07.12.2020
  rus: https://zan.gov.kz/client/#!/doc/149465/rus/07.12.2020
