act_code: '61430'
requisite: Решение акима Аккайынского района Северо-Казахстанской области от 16 ноября 2011 года № 51. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 ноября 2011 года № 13-2-140. Утратило силу - решением акима Аккайынского района Северо-Казахстанской области от 31 января 2014 года № 3
title:
  rus: Об образовании избирательных участков по Аккайынскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданы бойынша сайлау учаскелерін құру жөнінде
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-16
approved_by:
- '165005000001'
version_date:
  kaz: 2011-11-16
  rus: 2011-11-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/61430/kaz/16.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61430/rus/16.11.2011
