act_code: '119888'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 12 марта 2018 года № 21/6. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 марта 2018 года № 4619. Утратило силу решением Тимирязевского районного маслихата Северо-Казахстанской области от 22 декабря 2025 года № 31/19 (вводится в действие с 1 января 2026 года)
title:
  rus: О ставках земельного налога по Тимирязевскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тимирязев ауданы бойынша жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-12
approved_by:
- '165012000002'
version_date:
  kaz: 2021-04-06
  rus: 2021-04-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/119888/kaz/06.04.2021
  rus: https://zan.gov.kz/client/#!/doc/119888/rus/06.04.2021
caused_by:
  code: '154662'
  requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 6 апреля 2021 года № 3/3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 апреля 2021 года № 7290. Утратило силу решением Тимирязевского районного маслихата Северо-Казахстанской области от 22 декабря 2025 года № 31/19 (вводится в действие с 1 января 2026 года)
  title:
    rus: О внесении изменения в решение Тимирязевского районного маслихата от 12 марта 2018 года № 21/6 «О ставках земельного налога по Тимирязевскому району Северо-Казахстанской области»
    kaz: Тимирязев аудандық мәслихатының 2018 жылғы 12 наурыздағы № 21/6 «Солтүстік Қазақстан облысы Тимирязев ауданы бойынша жер салығының мөлшерлемелері туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154662/rus
