act_code: '55479'
requisite: Решение акима Тихоокеанского сельского округа Тайыншинского района Северо-Казахстанской области от 4 ноября 2010 года № 14. Зарегистрировано Управлением юстиции Тайыншинского района Северо-Казахстанской области 17 ноября 2010 года № 13-11-194
title:
  rus: О присвоении наименований составных частей населенных пунктов Тихоокеанского сельского округа Тайыншинского района
  kaz: Тайынша ауданы Тихоокеан ауылдық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-04
approved_by:
- '165011018002'
version_date:
  kaz: 2018-06-22
  rus: 2018-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/55479/kaz/22.06.2018
  rus: https://zan.gov.kz/client/#!/doc/55479/rus/22.06.2018
caused_by:
  code: '123329'
  requisite: Решение акима Тихоокеанского сельского округа Тайыншинского района Северо-Казахстанской области от 22 июня 2018 года № 6. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июля 2018 года № 4824
  title:
    rus: О внесении изменений в решение акима Тихоокеанского сельского округа Тайыншинского района Северо-Казахстанской области от 4 ноября 2010 года № 14 «О присвоении наименований составных частей населенных пунктов Тихоокеанского сельского округа Тайыншинского района»
    kaz: «Тайынша ауданы Тихоокеан селолық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы» Солтүстік Қазақстан облысы Тайынша ауданы Тихоокеан ауылдық округі әкімінің 2010 жылғы 4 қарашадағы № 14 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123329/rus
