act_code: '81719'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 3 июля 2014 года № 33/206. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 июля 2014 года № 2890
title:
  rus: О предоставлении в 2014 году подъемного пособия и социальной поддержки для  приобретения или строительства жилья специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты Есильского района
  kaz: Есіл ауданының ауылдық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға тұрғын үй алу немесе салу үшін 2014 жылы көтерме жәрдемақы мен әлеуметтік қолдау ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-07-03
approved_by:
- '165006000002'
version_date:
  kaz: 2014-07-03
  rus: 2014-07-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/81719/kaz/03.07.2014
  rus: https://zan.gov.kz/client/#!/doc/81719/rus/03.07.2014
