act_code: '188256'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 7 ноября 2023 года № 11-4. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 13 ноября 2023 года № 7617-15
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Акжарском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысының Ақжар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-07
approved_by:
- '165004000002'
version_date:
  kaz: 2025-04-24
  rus: 2025-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/188256/kaz/24.04.2025
  rus: https://zan.gov.kz/client/#!/doc/188256/rus/24.04.2025
caused_by:
  code: '209573'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 24 апреля 2025 года № 28-1. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 25 апреля 2025 года № 7900-15
  title:
    rus: О внесении изменения в решение Акжарского районного маслихата Северо-Казахстанской области от 07 ноября 2023 года № 11-4 «Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категории нуждающихся граждан в Акжарском районе Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Ақжар аудандық мәслихатының 2023 жылғы 07 қарашадағы № 11-4 «Солтүстік Қазақстан облысының Ақжар ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс еңгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209573/rus
