act_code: '68368'
requisite: Решение акима Григорьевского сельского округа Аккайынского района Северо-Казахстанской области от 26 сентября 2012 года № 8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 2 ноября 2012 года за № 1924
title:
  rus: О присвоении наименований улицам в селе Трудовое Григорьевского сельского округа Аккайынского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайын ауданы Григорьевка ауылдық округі Трудовое ауылының көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-26
approved_by:
- '165005004001'
version_date:
  kaz: 2018-08-20
  rus: 2018-08-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/68368/kaz/20.08.2018
  rus: https://zan.gov.kz/client/#!/doc/68368/rus/20.08.2018
caused_by:
  code: '124348'
  requisite: Решение акима Григорьевского сельского округа Аккайынского района Северо-Казахстанской области от 20 августа 2018 года № 25. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 августа 2018 года № 4892
  title:
    rus: О внесении изменений в решение акима Григорьевского сельского округа Аккайынского района Северо-Казахстанской области от 26 сентября 2012 года № 8 «О присвоении наименований улицам в селе Трудовое Григорьевского сельского округа Аккайынского района Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Аққайың ауданы Григорьевка селолық округі Трудовое селосының көшелеріне атау беру туралы» Солтүстік Қазақстан облысы Аққайың ауданы Григорьевка селолық округі әкімінің 2012 жылғы 26 қыркүйектегі № 8 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/124348/rus
