act_code: '151998'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 6 января 2021 года № 66-14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 января 2021 года № 6983
title:
  rus: Об утверждении бюджета Майского сельского округа Акжарского района на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Ақжар ауданы Май ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-06
approved_by:
- '165004000002'
version_date:
  kaz: 2021-11-22
  rus: 2021-11-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/151998/kaz/22.11.2021
  rus: https://zan.gov.kz/client/#!/doc/151998/rus/22.11.2021
caused_by:
  code: '160557'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 22 ноября 2021 года № 11-7
  title:
    rus: О внесении изменений в решение Акжарского районного маслихата от 6 января 2021 года № 66-14 «Об утверждении бюджета Майского сельского округа Акжарского района на 2021-2023 годы»
    kaz: Ақжар аудандық мәслихатының 2021 жылғы 6 қаңтардағы № 66-14 «2021-2023 жылдарға арналған Ақжар ауданы Май ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/160557/rus
