act_code: '142774'
requisite: Решение акима Ломоносовского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 6 мая 2020 года № 7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 мая 2020 года № 6297
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-05-06
approved_by:
- '165014009002'
version_date:
  kaz: 2020-05-06
  rus: 2020-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/142774/kaz/06.05.2020
  rus: https://zan.gov.kz/client/#!/doc/142774/rus/06.05.2020
