act_code: '162444'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 24 декабря 2021 года № 13-1. Зарегистрировано в Министерстве юстиции Республики Казахстан 28 декабря 2021 года № 26160
title:
  rus: Об утверждении бюджета района имени Габита Мусрепова на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Ғабит Мүсірепов атындағы ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '165014000002'
version_date:
  kaz: 2022-10-18
  rus: 2022-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/162444/kaz/18.10.2022
  rus: https://zan.gov.kz/client/#!/doc/162444/rus/18.10.2022
caused_by:
  code: '173223'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 18 октября 2022 года № 22-2
  title:
    rus: О внесении изменений в решение маслихата района имени Габита Мусрепова от 24 декабря 2021 года № 13-1 «Об утверждении бюджета района имени Габита Мусрепова на 2022-2024 годы»
    kaz: Ғабит Мүсірепов атындағы ауданы мәслихатының 2021 жылғы 24 желтоқсандағы № 13-1 «2022-2024 жылдарға арналған Ғабит Мүсірепов атындағы ауданының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173223/rus
