act_code: '61953'
requisite: Решение акима Тайыншинского района Северо-Казахстанской области от 17 ноября 2011 года № 34. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 декабря 2011 года № 13-11-220. Утратило силу в связи с истечением срока действия (письмо аппарата акима Тайыншинского района Северо-Казахстанской области от 03 января 2013 года № 02.10-07-02-02)
title:
  rus: Об организации и обеспечении на территории Тайыншинского района приписки граждан Республики Казахстан мужского пола, 1995 года рождения к призывному участку
  kaz: 1995 жылы туған Қазақстан Республикасының ер азаматтарын әскерге шақыру учаскесіне тіркеуді Тайынша ауданы аумағында ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-17
approved_by:
- '165011000003'
version_date:
  kaz: 2011-11-17
  rus: 2011-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/61953/kaz/17.11.2011
  rus: https://zan.gov.kz/client/#!/doc/61953/rus/17.11.2011
