act_code: '167033'
requisite: Решение Северо-Казахстанского областного маслихата от 20 апреля 2022 года № 16/2. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 апреля 2022 года № 27774
title:
  rus: О ставках платы за пользование водными ресурсами из поверхностных источников по Северо-Казахстанской области на 2022 год
  kaz: Солтүстік Қазақстан облысы бойынша 2022 жылға арналған жер үсті көздеріндегі су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-20
approved_by:
- '165000000002'
version_date:
  kaz: 2022-04-20
  rus: 2022-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/167033/kaz/20.04.2022
  rus: https://zan.gov.kz/client/#!/doc/167033/rus/20.04.2022
