act_code: '137680'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 25 декабря 2019 года № 42/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 декабря 2019 года № 5769
title:
  rus: Об утверждении районного бюджета Жамбылского района Северо-Казахстанской области на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Солтүстік Қазақстан облысы Жамбыл ауданының аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-25
approved_by:
- '165007000002'
version_date:
  kaz: 2020-06-30
  rus: 2020-06-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/137680/kaz/30.06.2020
  rus: https://zan.gov.kz/client/#!/doc/137680/rus/30.06.2020
caused_by:
  code: '144529'
  requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 30 июня 2020 года № 50/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 7 июля 2020 года № 6439
  title:
    rus: О внесении изменений и дополнений в решение маслихата Жамбылского района от 25 декабря 2019 года № 42/1 «Об утверждении районного бюджета Жамбылского района Северо-Казахстанской области на 2020-2022 годы»
    kaz: Жамбыл ауданы мәслихатының 2019 жылғы 25 желтоқсандағы № 42/1 «2020-2022 жылдарға арналған Солтүстік Қазақстан облысы Жамбыл ауданының аудандық бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144529/rus
