act_code: '192466'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 29 декабря 2023 года № 117/9
title:
  rus: Об утверждении бюджета Келлеровского сельского округа Тайыншинского района Северо-Казахстанской области на 2024-2026 годы
  kaz: Солтүстік Қазақстан облысы Тайынша ауданы Келлер ауылдық округінің 2024–2026 жылдарға арналған бюджетінбекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '165011000002'
version_date:
  kaz: 2024-11-08
  rus: 2024-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/192466/kaz/08.11.2024
  rus: https://zan.gov.kz/client/#!/doc/192466/rus/08.11.2024
caused_by:
  code: '202469'
  requisite: Решение Тайыншинского районного маслихата Северо-Казахстанской области от 8 ноября 2024 года № 221/18
  title:
    rus: О внесении изменений в решение маслихата Тайыншинского района Северо-Казахстанской области от 29 декабря 2023 года № 117/9 «Об утверждении бюджета Келлеровского сельского округа Тайыншинского района Северо-Казахстанской области на 2024-2026 годы»
    kaz: Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2023 жылғы 29 желтоқсандағы № 117/9 «Солтүстік Қазақстан облысы Тайынша ауданы Келлер ауылдық округінің 2024-2026 жылдарға арналған бюджетін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202469/rus
