act_code: '220672'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 декабря 2025 года № 34-16
title:
  rus: Об утверждении бюджета сельского округа Магжан района Магжана Жумабаева на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Мағжан Жұмабаев ауданы Мағжан ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-24
approved_by:
- '165015000002'
version_date:
  kaz: 2026-08-31
  rus: 2026-08-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/220672/kaz/31.08.2026
  rus: https://zan.gov.kz/client/#!/doc/220672/rus/31.08.2026
caused_by:
  code: '229665'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 31 августа 2026 года № 44-11
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 24 декабря 2025 года № 34-16 «Об утверждении бюджета сельского округа Магжан района Магжана Жумабаева на 2026-2028 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2025 жылғы 24 желтоқсандағы № 34-16 «2026-2028 жылдарға арналған Мағжан Жұмабаев ауданы Мағжан ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229665/rus
