act_code: '181267'
requisite: Решение акима Кишикаройского сельского округа Акжарского района Северо-Казахстанской области от 11 мая 2023 года № 18. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 мая 2023 года № 7502-15
title:
  rus: О переименовании некоторых улиц в селе Кіші Қараой Кишикаройского сельского округа Акжарского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ақжар ауданы Кіші-Қарой ауылдық округінің Кіші Қараой ауылындағы кейбір көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-11
approved_by:
- '165004006002'
version_date:
  kaz: 2023-05-11
  rus: 2023-05-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/181267/kaz/11.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181267/rus/11.05.2023
