act_code: '151650'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 8 января 2021 года № 443. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 8 января 2021 года № 6918
title:
  rus: Об утверждении бюджета Чкаловского сельского округа Тайыншинского района Северо-Казахстанской области на 2021 - 2023 годы
  kaz: Солтүстік Қазақстан облысы Тайынша ауданы Чкалов ауылдық округінің 2021 – 2023 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '165011000002'
version_date:
  kaz: 2021-08-17
  rus: 2021-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/151650/kaz/17.08.2021
  rus: https://zan.gov.kz/client/#!/doc/151650/rus/17.08.2021
caused_by:
  code: '158091'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 17 августа 2021 года № 77
  title:
    rus: О внесении изменений и дополнений в решение маслихата Тайыншинского района Северо-Казахстанской области от 8 января 2021 года № 443 «Об утверждении бюджета Чкаловского сельского округа Тайыншинского района Северо-Казахстанской области на 2021 - 2023 годы»
    kaz: «Солтүстік Қазақстан облысы Тайынша ауданы Чкалов ауылдық округінің 2021 – 2023 жылдарға арналған бюджетін бекіту туралы» Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2021 жылғы 8 қантардағы № 443 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158091/rus
