act_code: '171013'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 18 августа 2022 года № 22-1. Зарегистрирован в Министерстве юстиции Республики Казахстан 25 августа 2022 года № 29262. Утратило силу решением Акжарского районного маслихата Северо-Казахстанской области от 29 февраля 2024 года № 16-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Акжарском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ақжар ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2022-08-18
approved_by:
- '165004000002'
version_date:
  kaz: 2022-08-18
  rus: 2022-08-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/171013/kaz/18.08.2022
  rus: https://zan.gov.kz/client/#!/doc/171013/rus/18.08.2022
