act_code: '128233'
requisite: Решение акима города Петропавловска Северо-Казахстанской области от 9 января 2019 года № 01. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2019 года № 5190. Утратило силу решением акима города Петропавловска Северо-Казахстанской области от 20 мая 2026 года № 09 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории города Петропавловска
  kaz: Петропавл қаласының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-01-09
approved_by:
- '165002000003'
version_date:
  kaz: 2019-09-24
  rus: 2019-09-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/128233/kaz/24.09.2019
  rus: https://zan.gov.kz/client/#!/doc/128233/rus/24.09.2019
caused_by:
  code: '134878'
  requisite: Решение акима города Петропавловска Северо-Казахстанской области от 24 сентября 2019 года № 30. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 25 сентября 2019 года № 5579
  title:
    rus: О внесении изменений в решение акима города Петропавловска Северо-Казахстанской области от 9 января 2019 года № 01 «Об образовании избирательных участков на территории города Петропавловска»
    kaz: Солтүстік Қазақстан облысы Петропавл қаласы әкімінің 2019 жылғы 9 қаңтардағы № 01 «Петропавл қаласының аумағында сайлау учаскелерін құру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/134878/rus
