act_code: '138155'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 8 января 2020 года № 43/5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2020 года № 5843
title:
  rus: Об утверждении бюджета города Сергеевки района Шал акына на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Шал ақын ауданы Сергеевка қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165010000002'
version_date:
  kaz: 2020-01-08
  rus: 2020-01-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/138155/kaz/08.01.2020
  rus: https://zan.gov.kz/client/#!/doc/138155/rus/08.01.2020
