act_code: '206304'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 30 декабря 2024 года № 23-6. Утратило силу решением маслихата района Магжана Жумабаева Северо-Казахстанской области от 12 мая 2025 года № 27-7 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета города Булаево района Магжана Жумабаева на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Мағжан Жұмабаев ауданы Булаев қаласының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '165015000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/206304/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206304/rus/30.12.2024
