act_code: '55497'
requisite: Решение акима Зеленогайского сельского округа Тайыншинского района Северо-Казахстанской области от 15 ноября 2010 года № 6. Зарегистрировано Управлением юстиции Тайыншинского района Северо-Казахстанской области 23 ноября 2010 года № 13-11-195
title:
  rus: О присвоении наименований составных частей населенных пунктов Зеленогайского сельского округа Тайыншинского района
  kaz: Тайынша ауданы Зеленогай ауылдық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-15
approved_by:
- '165011008002'
version_date:
  kaz: 2018-06-22
  rus: 2018-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/55497/kaz/22.06.2018
  rus: https://zan.gov.kz/client/#!/doc/55497/rus/22.06.2018
caused_by:
  code: '123280'
  requisite: Решение акима Зеленогайского сельского округа Тайыншинского района Северо-Казахстанской области от 22 июня 2018 года № 4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июля 2018 года № 4810
  title:
    rus: О внесении изменений в решение акима Зеленогайского сельского округа Тайыншинского района Северо-Казахстанской области от 15 ноября 2010 года №6 «О присвоении наименований составных частей населенных пунктов Зеленогайского сельского округа Тайыншинского района»
    kaz: «Тайынша ауданы Зеленогай селолық округі елді мекендерінің құрамдық бөліктеріне атау беру туралы» Солтүстік Қазақстан облысы Тайынша ауданы Зеленогай ауылдық округі әкімінің 2010 жылғы 15 қарашасындағы №6 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123280/rus
