act_code: '195999'
requisite: Решение Тайыншинского районного маслихата Северо-Казахстанской области от 19 апреля 2024 года № 152/13
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Тайыншинскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тайынша ауданы бойынша коммуналдық қалдықтардың түзету және жинақталу нормаларын, халық үшін қатты тұрмыстық қатты қалдықтарды жинақтау, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2024-04-19
approved_by:
- '165011000002'
version_date:
  kaz: 2024-04-19
  rus: 2024-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/195999/kaz/19.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195999/rus/19.04.2024
