act_code: '176638'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 28 декабря 2022 года № 7-23-27
title:
  rus: Об утверждении бюджета Нижнебурлукского сельского округа Айыртауского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Айыртау ауданы Нижнебурлук ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-28
approved_by:
- '165003000002'
version_date:
  kaz: 2023-04-11
  rus: 2023-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/176638/kaz/11.04.2023
  rus: https://zan.gov.kz/client/#!/doc/176638/rus/11.04.2023
caused_by:
  code: '179685'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 11 апреля 2023 года № 8-2-14
  title:
    rus: О внесении изменений и дополнений в решение Айыртауского районного маслихата от 28 декабря 2022 года № 7-23-27 «Об утверждении бюджета Нижнебурлукского сельского округа Айыртауского района на 2023-2025 годы»
    kaz: «2023-2025 жылдарға арналған Айыртау ауданы Нижнебурлук ауылдық округінің бюджетін бекіту туралы» Айыртау аудандық мәслихатының 2022 жылғы 28 желтоқсандағы № 7-23-27 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/179685/rus
