act_code: '123059'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 15 июня 2018 года № 179. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 2 июля 2018 года № 4792. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 11 сентября 2020 года № 379 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога и ставок единого земельного налога на не используемые земли сельскохозяйственного назначения по Тайыншинскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысының Тайынша ауданы бойынша ауыл шаруашылығы мақсатындағы пайдаланылмайтын жерге жер салығының базалық мөлшерлемелерін және бірыңғай жер салығының мөлшерлемелерін арттыру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-06-15
approved_by:
- '165011000002'
version_date:
  kaz: 2018-06-15
  rus: 2018-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/123059/kaz/15.06.2018
  rus: https://zan.gov.kz/client/#!/doc/123059/rus/15.06.2018
