act_code: '9024'
requisite: Решение Северо-Казахстанского областного маслихата от 19 марта 2001 года № 9/1. Зарегистрировано Управлением юстиции Северо-Казахстанской области 25 апреля 2001 года за № 305. Утратило силу - решением Северо-Казахстанского областного маслихата от 23 июля 2010 года № 27/10
title:
  rus: Об уточнении областного бюджета на 2001 год
  kaz: 2001 жылғы облыстық бюджетті нақтылау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2001-03-19
approved_by:
- '165000000002'
version_date:
  kaz: 2001-03-19
  rus: 2001-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/9024/kaz/19.03.2001
  rus: https://zan.gov.kz/client/#!/doc/9024/rus/19.03.2001
