act_code: '818'
requisite: Решение акима Северо-Казахстанской области от 27 марта 1998 года № 73. Зарегистрировано Управлением юстиции Северо-Казахстанской области 20 мая 1998 года за № 9. Утратило силу - решением акима Северо-Казахстанской области от 4 декабря 2000 года № 228
title:
  rus: О проведении тендеров по государственным закупкам товаров, работ и услуг
  kaz: Тауарларды мемлекеттiк сатып алу, жұмыстар және қызметтер жөнiндегi тендерлер өткiзу туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 1998-03-27
approved_by:
- '165000000003'
version_date:
  kaz: 1998-03-27
  rus: 1998-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/818/kaz/27.03.1998
  rus: https://zan.gov.kz/client/#!/doc/818/rus/27.03.1998
