act_code: '192455'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 29 декабря 2023 года № 8/23
title:
  rus: Об утверждении бюджета Рощинского сельского округа Кызылжарского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Қызылжар ауданының Рощин ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '165008000002'
version_date:
  kaz: 2024-08-09
  rus: 2024-08-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/192455/kaz/09.08.2024
  rus: https://zan.gov.kz/client/#!/doc/192455/rus/09.08.2024
caused_by:
  code: '199730'
  requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 9 августа 2024 года № 14/15
  title:
    rus: О внесении изменений в решение Кызылжарского районного маслихата Северо-Казахстанской области от 29 декабря 2023 года № 8/23 «Об утверждении бюджета Рощинского сельского округа Кызылжарского района на 2024-2026 годы»
    kaz: Солтүстік Қазақстан облысы Қызылжар аудандық мәслихатының 2023 жылғы 29 желтоқсандағы № 8/23 «2024-2026 жылдарға арналған Қызылжар ауданының Рощин ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/199730/rus
