act_code: '91981'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 19 июня 2015 года № 36-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 июля 2015 года № 3326. Утратило силу решением маслихата района имени Габита Мусрепова Северо-Казахстанской области от 5 февраля 2018 года № 19-3
title:
  rus: О повышении ставок единого земельного налога
  kaz: Бірыңғай жер салығының мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-06-19
approved_by:
- '165014000002'
version_date:
  kaz: 2015-06-19
  rus: 2015-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/91981/kaz/19.06.2015
  rus: https://zan.gov.kz/client/#!/doc/91981/rus/19.06.2015
