act_code: '111476'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 4 апреля 2017 года № 70. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 18 апреля 2017 года № 4145. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 15 января 2021 года № 7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Тайыншинского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тайынша ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтарының жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-04-04
approved_by:
- '165011000002'
version_date:
  kaz: 2020-05-04
  rus: 2020-05-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/111476/kaz/04.05.2020
  rus: https://zan.gov.kz/client/#!/doc/111476/rus/04.05.2020
caused_by:
  code: '142561'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 4 мая 2020 года № 357. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 5 мая 2020 года № 6289. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 15 января 2021 года № 7 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата Тайыншинского района Северо-Казахстанской области от 4 апреля 2017 года № 70 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Тайыншинского района Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы Тайынша ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтары жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2017 жылғы 4 сәуірдегі № 70 шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/142561/rus
