act_code: '189522'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 28 ноября 2023 года № 8/8. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 4 декабря 2023 года № 7640-15
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Тимирязевского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тимирязев ауданындағы әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-28
approved_by:
- '165012000002'
version_date:
  kaz: 2025-05-06
  rus: 2025-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/189522/kaz/06.05.2025
  rus: https://zan.gov.kz/client/#!/doc/189522/rus/06.05.2025
caused_by:
  code: '210045'
  requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 6 мая 2025 года № 24/2. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 12 мая 2025 года № 7921-15
  title:
    rus: О внесении изменений в решение Тимирязевского районного маслихата от 28 ноября 2023 года № 8/8 «Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан Тимирязевского района Северо-Казахстанской области»
    kaz: Тимирязев аудандық мәслихатының 2023 жылғы 28 қарашадағы № 8/8 «Солтүстік Қазақстан облысы Тимирязев ауданы әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210045/rus
