act_code: '155104'
requisite: Решение акима Власовского сельского округа Аккайынского района Северо-Казахстанской области от 20 апреля 2021 года № 7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 апреля 2021 года за № 7310
title:
  rus: О переименовании улицы села Безлесное Власовского сельского округа Аккайынского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданы Власовка ауылдық округі Безлесное ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-20
approved_by:
- '165005003002'
version_date:
  kaz: 2021-04-20
  rus: 2021-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/155104/kaz/20.04.2021
  rus: https://zan.gov.kz/client/#!/doc/155104/rus/20.04.2021
