act_code: '169988'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 20 июля 2022 года № 7-19-13. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 июля 2022 года № 28861
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Айыртауском районе
  kaz: Айыртау ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-20
approved_by:
- '165003000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/169988/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/169988/rus/27.12.2022
caused_by:
  code: '177108'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 27 декабря 2022 года № 7-23-2. Зарегистрировано в Министерстве юстиции Республики Казахстан 6 января 2023 года № 31592
  title:
    rus: О внесений изменений в решение Айыртауского районного маслихата от 20 июля 2022 года № 7-19-13 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану в Айыртауском районе»
    kaz: Айыртау аудандық мәслихатының 2022 жылғы 20 шілдедегі № 7-19-13 «Айыртау ауданында мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/177108/rus
