act_code: '169988'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 20 июля 2022 года № 7-19-13. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 июля 2022 года № 28861
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Айыртауском районе
  kaz: Айыртау ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-07-20
approved_by:
- '165003000002'
version_date:
  kaz: 2022-07-20
  rus: 2022-07-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/169988/kaz/20.07.2022
  rus: https://zan.gov.kz/client/#!/doc/169988/rus/20.07.2022
