act_code: '82760'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 25 июля 2014 года № 26-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 августа 2014 года № 2921. Утратило силу решением маслихата Аккайынского района Северо-Казахстанской области от 22 сентября 2023 года № 8-4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей сел для участия в сходе местного сообщества Полтавского сельского округа Аккайынского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданының Полтавка ауылдық округінде жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидасын және жергілікті қоғамдастық жиындарына қатысатын ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-07-25
approved_by:
- '165005000002'
version_date:
  kaz: 2014-07-25
  rus: 2014-07-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/82760/kaz/25.07.2014
  rus: https://zan.gov.kz/client/#!/doc/82760/rus/25.07.2014
