act_code: '85246'
requisite: Решение акима Кызылжарского района Северо-Казахстанской области от 27 ноября 2014 года № 25. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 22 декабря 2014 года № 3018
title:
  rus: Об организации и обеспечении на территории Кызылжарского района Северо-Казахстанской области приписки и медицинского овидетельствования граждан мужского пола Республики Казахстан с января по март 2015 года
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданының аумағында 2015 жылғы қаңтар- наурыз аралығында Қазақстан Республикасының ер азаматтарын тіркеуді және медициналық куәландыру ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-11-27
approved_by:
- '165008000001'
version_date:
  kaz: 2014-11-27
  rus: 2014-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/85246/kaz/27.11.2014
  rus: https://zan.gov.kz/client/#!/doc/85246/rus/27.11.2014
