act_code: '86327'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 23 декабря 2014 года № 39/238. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 21 января 2015 года № 3073. Утратил силу решением маслихата Есильского района Северо-Казахстанской области от 7 октября 2021 года № 11/102 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О возмещении затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану
  kaz: Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарды өтеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-23
approved_by:
- '165006000002'
version_date:
  kaz: 2014-12-23
  rus: 2014-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/86327/kaz/23.12.2014
  rus: https://zan.gov.kz/client/#!/doc/86327/rus/23.12.2014
