act_code: '127772'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 24 декабря 2018 года № 27-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 декабря 2018 года № 5119
title:
  rus: Об утверждении бюджета Аккайынского района на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Аққайың ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '165005000002'
version_date:
  kaz: 2019-11-26
  rus: 2019-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/127772/kaz/26.11.2019
  rus: https://zan.gov.kz/client/#!/doc/127772/rus/26.11.2019
caused_by:
  code: '136471'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 26 ноября 2019 года № 34-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 ноября 2019 года № 5687
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 24 декабря 2018 года № 27-1 «Об утверждении бюджета Аккайынского района на 2019-2021 годы»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2018 жылғы 24 желтоқсандағы № 27-1 «2019-2021 жылдарға арналған Аққайың ауданының бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/136471/rus
