act_code: '127772'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 24 декабря 2018 года № 27-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 декабря 2018 года № 5119
title:
  rus: Об утверждении бюджета Аккайынского района на 2019 - 2021 годы
  kaz: 2019 - 2021 жылдарға арналған Аққайың ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-24
approved_by:
- '165005000002'
version_date:
  kaz: 2018-12-24
  rus: 2018-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/127772/kaz/24.12.2018
  rus: https://zan.gov.kz/client/#!/doc/127772/rus/24.12.2018
