act_code: '195389'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 28 марта 2024 года № 10/6. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 2 апреля 2024 года № 7736-15
title:
  rus: Об утверждении правил и определении размера оказания жилищной помощи в Кызылжарском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданында тұрғын үй көмегін көрсетудің қағидаларын бекіту мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '165008000002'
version_date:
  kaz: 2024-03-28
  rus: 2024-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/195389/kaz/28.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195389/rus/28.03.2024
