act_code: '217987'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 27 ноября 2025 года № 33-1
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима на основе упрощенной декларации на 2026 год в Акжарском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ақжар ауданының 2026 жылға арналған оңайлатылған декларация негізінде арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-27
approved_by:
- '165004000002'
version_date:
  kaz: 2025-11-27
  rus: 2025-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/217987/kaz/27.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217987/rus/27.11.2025
