act_code: '122458'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 31 мая 2018 года № 20-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 июня 2018 года № 4757
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-31
approved_by:
- '165005000002'
version_date:
  kaz: 2021-04-08
  rus: 2021-04-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/122458/kaz/08.04.2021
  rus: https://zan.gov.kz/client/#!/doc/122458/rus/08.04.2021
caused_by:
  code: '154661'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 8 апреля 2021 года № 2-14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 апреля 2021 года № 7289
  title:
    rus: О внесении изменения в решение маслихата Аккайынского района Северо-Казахстанской области от 31 мая 2018 года № 20-1 «О ставках на земельный налог»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2018 жылғы 31 мамырдағы № 20-1 «Жер салығының мөлшерлемелері туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/154661/rus
