act_code: '122458'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 31 мая 2018 года № 20-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 июня 2018 года № 4757
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-05-31
approved_by:
- '165005000002'
version_date:
  kaz: 2022-03-11
  rus: 2022-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/122458/kaz/11.03.2022
  rus: https://zan.gov.kz/client/#!/doc/122458/rus/11.03.2022
caused_by:
  code: '165487'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 11 марта 2022 года № 9-8. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 марта 2022 года № 27169
  title:
    rus: О внесении изменений в решение маслихата Аккайынского района Северо-Казахстанской области от 31 мая 2018 года № 20-1 «О ставках на земельный налог»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2018 жылғы 31 мамырдағы № 20-1 «Жер салығының мөлшерлемелері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165487/rus
