act_code: '128109'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 27 декабря 2018 года № 218. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 января 2019 года № 5142
title:
  rus: Об утверждении бюджета Тайыншинского района Северо-Казахстанской области на 2019 - 2021 годы
  kaz: Солтүстік Қазақстан облысы Тайынша ауданының 2019 - 2021 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '165011000002'
version_date:
  kaz: 2019-05-23
  rus: 2019-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/128109/kaz/23.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128109/rus/23.05.2019
caused_by:
  code: '132009'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 23 мая 2019 года № 263. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 мая 2019 года № 5419
  title:
    rus: О внесении изменений и дополнений в решение маслихата Тайыншинского района Северо-Казахстанской области от 27 декабря 2018 года № 218 «Об утверждении бюджета Тайыншинского района Северо-Казахстанской области на 2019 - 2021 годы»
    kaz: Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2018 жылғы 27 желтоқсандағы № 218 «Солтүстік Қазақстан облысы Тайынша ауданының 2019 - 2021 жылдарға арналған бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132009/rus
