act_code: '36968'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2007 жылғы 24 желтоқсандағы № 2-4 с шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2008 жылғы 22 қаңтарда № 13-13-60 болып тіркелді
title:
  rus: 2008 жылға арналған аудан бюджеті туралы
  kaz: 2008 жылға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2007-12-24
approved_by:
- '165013000002'
version_date:
  kaz: 2007-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/36968/kaz/24.12.2007
