act_code: '201399'
requisite: Решение акима Леденевского сельского округа Мамлютского района Северо-Казахстанской области от 4 октября 2024 года № 13
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитутты белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-10-04
approved_by:
- '165009007002'
version_date:
  kaz: 2024-10-04
  rus: 2024-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/201399/kaz/04.10.2024
  rus: https://zan.gov.kz/client/#!/doc/201399/rus/04.10.2024
