act_code: '125045'
requisite: Решение акима Елецкого сельского округа Айыртауского района Северо-Казахстанской области от 4 октября 2018 года № 8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 октября 2018 года № 4912
title:
  rus: О снятии карантина
  kaz: Карантинді тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-10-04
approved_by:
- '165003005002'
version_date:
  kaz: 2018-10-04
  rus: 2018-10-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/125045/kaz/04.10.2018
  rus: https://zan.gov.kz/client/#!/doc/125045/rus/04.10.2018
