act_code: '112050'
requisite: Решение Северо-Казахстанского областного маслихата от 11 апреля 2017 года № 13/21. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 мая 2017 года № 4177
title:
  rus: Об утверждении Правил благоустройства территорий городов и населенных пунктов Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысындағы қалалар мен елді мекендердің аумақтарын абаттандырудың Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2017-04-11
approved_by:
- '165000000002'
version_date:
  kaz: 2018-06-27
  rus: 2018-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/112050/kaz/27.06.2018
  rus: https://zan.gov.kz/client/#!/doc/112050/rus/27.06.2018
caused_by:
  code: '123351'
  requisite: Решение Северо-Казахстанского областного маслихата от 27 июня 2018 года № 22/5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 июля 2018 года № 4830
  title:
    rus: О внесении изменений и дополнений в решение Северо-Казахстанского областного маслихата от 11 апреля 2017 года № 13/21 «Об утверждении Правил благоустройства территорий городов и населенных пунктов Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысындағы қалалар мен елді мекендердің аумақтарын абаттандырудың Қағидаларын бекіту туралы» Солтүстік Қазақстан облыстық мәслихаттың 2017 жылғы 11 сәуірдегі № 13/21 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123351/rus
