act_code: '221270'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 26 декабря 2025 года № 11-37 с
title:
  rus: Об утверждении бюджета Кулыкольского сельского округа Уалихановского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Уәлиханов ауданы Қулыкөл ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-26
approved_by:
- '165013000002'
version_date:
  kaz: 2026-03-31
  rus: 2026-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/221270/kaz/31.03.2026
  rus: https://zan.gov.kz/client/#!/doc/221270/rus/31.03.2026
caused_by:
  code: '224027'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 31 марта 2026 года № 12-38 с
  title:
    rus: О внесении изменений и дополнения в решение Уалихановского районного маслихата от 26 декабрь 2025 года № 11-37 с «Об утверждении бюджета Кулыкольского сельского округа Уалихановского района на 2026-2028 годы»
    kaz: Уәлиханов аудандық мәслихатының 2025 жылғы 26 желтоқсандағы № 11-37 с «2026-2028 жылдарға арналған Уәлиханов ауданы Қулыкөл ауылдық округінің бюджетін бекіту туралы» шешіміне  өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224027/rus
