act_code: '151993'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 6 января 2021 года № 66-9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 января 2021 года № 6978
title:
  rus: Об утверждении бюджета Айсаринского сельского округаАкжарского района на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Ақжар ауданы Айсары ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-06
approved_by:
- '165004000002'
version_date:
  kaz: 2021-12-15
  rus: 2021-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/151993/kaz/15.12.2021
  rus: https://zan.gov.kz/client/#!/doc/151993/rus/15.12.2021
caused_by:
  code: '162305'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 15 декабря 2021 года № 12-5
  title:
    rus: О внесении изменений в решение Акжарского районного маслихата от 6 января 2021 года № 66-9 «Об утверждении бюджета Айсаринского сельского округа Акжарского района на 2021-2023 годы»
    kaz: Ақжар аудандық мәслихатының 2021 жылғы 6 қаңтардағы № 66-9 «2021-2023 жылдарға арналған Ақжар ауданы Айсары ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/162305/rus
