act_code: '39473'
requisite: Решение акима Северо-Казахстанской области от 2 апреля 2008 года № 8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 апреля 2008 года № 1673. Утратило силу в связи с истечением срока действия (письмо аппарата акима Северо-Казахстанской области от 1 июля 2015 года № 1.14-7/1840)
title:
  rus: Об утверждении объемов субсидий на повышение урожайности и качества продукции растениеводства, удешевление стоимости горюче-смазочных материалов и других товарно-материальных ценностей, необходимых для проведения весенне-полевых и уборочных работ на 2008 год
  kaz: Өсімдік шаруашылығы өнімінің шығымдылығы мен сапасын арттыруға, 2008 жылғы көктемгі егіс және егін жинау жұмыстарын жүргізу үшін қажетті жанар-жағармай материалдары мен басқа да тауар-материалдық құндылықтардың құнын арзандатуға субсидиялар көлемін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-04-02
approved_by:
- '165000000003'
version_date:
  kaz: 2008-12-04
  rus: 2008-12-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/39473/kaz/04.12.2008
  rus: https://zan.gov.kz/client/#!/doc/39473/rus/04.12.2008
caused_by:
  code: '42859'
  requisite: Решение акима Северо-Казахстанской области от 4 декабря 2008 года № 32. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 18 декабря 2008 года № 1697. Утратило силу в связи с истечением срока действия (письмо аппарата акима Северо-Казахстанской области от 17 октября 2011 года № 01.04-08/2964)
  title:
    rus: О внесении изменения в решение акима области от 2 апреля 2008 года № 8 "Об утверждении объемов субсидий на повышение урожайности и качества продукции растениеводства, удешевление стоимости горюче-смазочных материалов и других товарно-материальных ценностей, необходимых для проведения весенне-полевых и уборочных работ на 2008 год"
    kaz: '"Өсімдік шаруашылығы өнімінің шығымдылығы мен сапасын арттыруға, 2008 жылғы көктемгі егіс және егін жинау жұмыстарын жүргізу үшін қажетті жанар-жағармай материалдары мен басқа да тауар-материалдық құндылықтардың құнын арзандатуға субсидиялар көлемін бекіту туралы" облыс әкімінің 2008 жылғы 2 сәуірдегі № 8 шешіміне өзгеріс енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/42859/rus
