act_code: '139096'
requisite: Решение акима Петровского сельского округа Есильского района Северо-Казахстанской области от 22 января 2020 года № 04. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 27 января 2020 года № 5985
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-22
approved_by:
- '165006008002'
version_date:
  kaz: 2020-01-22
  rus: 2020-01-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/139096/kaz/22.01.2020
  rus: https://zan.gov.kz/client/#!/doc/139096/rus/22.01.2020
