act_code: '143351'
requisite: Решение акима Сухорабовского сельского округа района Шал акына Северо-Казахстанской области от 27 мая 2020 года № 3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 мая 2020 года № 6322. Утратило силу решением акима Сухорабовского сельского округа района Шал акына Северо-Казахстанской области от 22 октября 2020 года № 10 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-05-27
approved_by:
- '165010011002'
version_date:
  kaz: 2020-05-27
  rus: 2020-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/143351/kaz/27.05.2020
  rus: https://zan.gov.kz/client/#!/doc/143351/rus/27.05.2020
