act_code: '86807'
requisite: Решение акима Северо-Казахстанской области от 29 января 2015 года № 03. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 января 2015 года № 3090. Утратило силу решением акима Северо-Казахстанской области от 10 апреля 2015 года № 13
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба
  kaz: Жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-01-29
approved_by:
- '165000000001'
version_date:
  kaz: 2015-01-29
  rus: 2015-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/86807/kaz/29.01.2015
  rus: https://zan.gov.kz/client/#!/doc/86807/rus/29.01.2015
repealed_on: 2016-04-10
repealed_by:
  code: '102417'
  requisite: Решение акима Северо-Казахстанской области от 10 апреля 2015 года № 13
  title:
    rus: О признании утратившим силу решения акима Северо-Казахстанской области от 29 января 2015 года № 03 «Об объявлении чрезвычайной ситуации природного характера местного масштаба
    kaz: «Жергiлiктi ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы» Солтүстік Қазақстан облысы әкімінің 2015 жылғы  29 қаңтардағы № 03 шешiмiнің күші жойылды деп тану туралы
  link: https://zan.gov.kz/client/#!/doc/102417/rus
