act_code: '21081'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 14 июля 2004 года № 6. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 17 августа 2004 года за № 1327. Утратило силу решением Петропавловского городского маслихата Северо-Казахстанской области от 18 января 2016 года № 6
title:
  rus: О Правилах предоставления семьям (гражданам) жилищной помощи на содержание жилья и оплату коммунальных услуг
  kaz: Отбасыларға (азаматтарға) пәтер үйді ұстауға және коммуналдық қызметтерді төлеуге тұрғын үй көмегін ұсыну ережелері туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-07-13
approved_by:
- '165002000002'
version_date:
  kaz: 2011-05-12
  rus: 2011-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/21081/kaz/12.05.2011
  rus: https://zan.gov.kz/client/#!/doc/21081/rus/12.05.2011
caused_by:
  code: '59123'
  requisite: Решение маслихата города Петропавловска Северо-Казахстанской области от 12 мая 2011 года № 2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 06 июня 2011 года № 13-1-198. Утратило силу решением Петропавловского городского маслихата Северо-Казахстанской области от 18 января 2016 года № 6
  title:
    rus: О внесении изменений и дополнений в решение внеочередной седьмой сессии Петропавловского городского маслихата от 14 июля 2004 года № 6 "О Правилах предоставления семьям (гражданам) жилищной помощи на содержания жилья и оплату коммунальных услуг"
    kaz: '"Отбасыларға (азаматтарға) пәтер үйді ұстауға және коммуналдық қызметтерді төлеуге тұрғын үй көмегін ұсыну ережелері туралы" Петропавл қалалық мәслихатының 2011 жылғы 14 шілдедегі кезектен тыс жетінші сессиясының № 6 шешіміне өзгерістер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/59123/rus
