act_code: '210128'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 6 мая 2025 года № 3-30 с
title:
  rus: Об утверждении бюджета Актуесайского сельского округа Уалихановского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Уәлиханов ауданы Ақтүйесай ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-06
approved_by:
- '165013000002'
version_date:
  kaz: 2025-05-06
  rus: 2025-05-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/210128/kaz/06.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210128/rus/06.05.2025
