act_code: '210128'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 6 мая 2025 года № 3-30 с
title:
  rus: Об утверждении бюджета Актуесайского сельского округа Уалихановского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Уәлиханов ауданы Ақтүйесай ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-06
approved_by:
- '165013000002'
version_date:
  kaz: 2025-08-27
  rus: 2025-08-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/210128/kaz/27.08.2025
  rus: https://zan.gov.kz/client/#!/doc/210128/rus/27.08.2025
caused_by:
  code: '214014'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 27 августа 2025 года № 7-33 с
  title:
    rus: О внесении изменений и дополнений в решение Уалихановского районного маслихата от 6 мая 2025 года № 3-30 с «Об утверждении бюджета Актуесайского сельского округа Уалихановского района на 2025-2027 годы
    kaz: Уәлиханов аудандық мәслихатының 2025 жылғы 6 мамырдағы №3-30 с «2025-2027 жылдарға арналған Уәлиханов ауданы Ақтүйесай ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214014/rus
