act_code: '179433'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 30 марта 2023 года № 8-6. Утратило силу решением Акжарского районного маслихата Северо-Казахстанской области от 26 августа 2025 года № 31-18 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» коммунального государственного учреждения «Аппарат Акжарского районного маслихата Северо-Казахстанской области»
  kaz: «Солтүстік Қазақстан облысы Ақжар аудандық мәслихатының аппараты» коммуналдық мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-03-30
approved_by:
- '165004000002'
version_date:
  kaz: 2023-03-30
  rus: 2023-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/179433/kaz/30.03.2023
  rus: https://zan.gov.kz/client/#!/doc/179433/rus/30.03.2023
