act_code: '31293'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 25 декабря 2006 года № 36-2. Зарегистрировано Управлением юстиции района Магжана Жумабаева Северо-Казахстанской области 29 декабря 2006 года № 13-9-40
title:
  rus: «О бюджете района на 2007 год»
  kaz: «2007 жылға арналған аудан бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2006-12-29
approved_by:
- '165015000002'
version_date:
  kaz: 2006-12-29
  rus: 2006-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/31293/kaz/29.12.2006
  rus: https://zan.gov.kz/client/#!/doc/31293/rus/29.12.2006
