act_code: '102366'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 3 мая 2016 года  № 3/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 16 мая 2016 года № 3746. Утратило силу решением Кызылжарского районного маслихата Северо-Казахстанской области от 30 июня 2020 года № 54/15 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О дополнительном регламентировании порядка проведения собраний, митингов, шествий, пикетов и демонстраций по Кызылжарскому району Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданы бойынша жиналыстар, митингiлер, шерулер, пикеттер және демонстрациялар өткiзу тәртiбiн қосымша реттеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2016-05-03
approved_by:
- '165008000002'
version_date:
  kaz: 2016-05-03
  rus: 2016-05-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/102366/kaz/03.05.2016
  rus: https://zan.gov.kz/client/#!/doc/102366/rus/03.05.2016
