act_code: '199459'
requisite: Решение акима Тимирязевского сельского округа Тимирязевского района Северо-Казахстанской области от 6 августа 2024 года № 23
title:
  rus: О предоставлении права ограниченного целевого пользования (публичный сервитут) на земельный участок
  kaz: Жер учаскесіне шектеулі пайдалану құқық (қауымдық сервитут) беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-06
approved_by:
- '165012001002'
version_date:
  kaz: 2024-08-06
  rus: 2024-08-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/199459/kaz/06.08.2024
  rus: https://zan.gov.kz/client/#!/doc/199459/rus/06.08.2024
