act_code: '77466'
requisite: Решение акима Тимирязевского района Северо-Казахстанской области от 15 января 2014 года № 2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 февраля 2014 года № 2557. Утратило силу решением акима Тимирязевского района Северо-Казахстанской области от 19 февраля 2015 года № 10
title:
  rus: Об образовании избирательных участков на территории Тимирязевского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тимирязев ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-01-15
approved_by:
- '165012000001'
version_date:
  kaz: 2014-01-15
  rus: 2014-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/77466/kaz/15.01.2014
  rus: https://zan.gov.kz/client/#!/doc/77466/rus/15.01.2014
