act_code: '152274'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 8 января 2021 года № 46-11. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 января 2021 года № 7071
title:
  rus: Об утверждении бюджета сельского округа Магжан района Магжана Жумабаева на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Мағжан Жұмабаев ауданы Мағжан ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '165015000002'
version_date:
  kaz: 2021-08-26
  rus: 2021-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/152274/kaz/26.08.2021
  rus: https://zan.gov.kz/client/#!/doc/152274/rus/26.08.2021
caused_by:
  code: '158427'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 26 августа 2021 года № 8-12
  title:
    rus: О внесении изменений в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 8 января 2021 года № 46-11 «Об утверждении бюджета сельского округа Магжан района Магжана Жумабаева на 2021-2023 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2021 жылғы 8 қаңтардағы № 46-11 «2021-2023 жылдарға арналған Мағжан Жұмабаев ауданы Мағжан ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158427/rus
