act_code: '49930'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 25 декабря 2009 года № 21-1. Зарегистрировано Управлением юстиции Акжарского района Северо-Казахстанской области 15 января 2010 года № 13-4-95
title:
  rus: О районном бюджете на 2010-2012 годы
  kaz: 2010-2012 жылдарға арналған аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-12-25
approved_by:
- '165004000002'
version_date:
  kaz: 2010-08-05
  rus: 2010-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/49930/kaz/05.08.2010
  rus: https://zan.gov.kz/client/#!/doc/49930/rus/05.08.2010
caused_by:
  code: '54352'
  requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 5 августа 2010 года № 25-2. Зарегистрировано Управлением юстиции Акжарского района Северо-Казахстанской области 6 сентября 2010 года № 13-4-110
  title:
    rus: О внесении изменений и дополнений в решение Акжарского районного маслихата от 25 декабря 2009 года № 21-1 "О районном бюджете на 2010-2012 годы"
    kaz: '"2010-2012 жылдарға арналған аудандық бюджет туралы" Ақжар аудандық мәслихатының 2009 жылғы 25 желтоқсандағы № 21-1 шешіміне өзгертулер мен толықтырулар енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/54352/rus
