act_code: '126340'
requisite: Решение акима Тимирязевского района Северо-Казахстанской области от 19 ноября 2018 года № 15. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 ноября 2018 года № 4998. Утратило силу решением акима Тимирязевского района Северо-Казахстанской области от 3 марта 2021 года № 9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Тимирязевского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тимирязев ауданы аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-11-19
approved_by:
- '165012000003'
version_date:
  kaz: 2020-07-08
  rus: 2020-07-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/126340/kaz/08.07.2020
  rus: https://zan.gov.kz/client/#!/doc/126340/rus/08.07.2020
caused_by:
  code: '144857'
  requisite: Решение акима Тимирязевского района Северо-Казахстанской области от 8 июля 2020 года № 8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 16 июля 2020 года № 6449. Утратило силу решением акима Тимирязевского района Северо-Казахстанской области от 3 марта 2021 года № 9 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение акима Тимирязевского района Северо-Казахстанской области от 19 ноября 2018 года № 15 «Об образовании избирательных участков на территории Тимирязевского района Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Тимирязев ауданы әкімінің 2018 жылғы 19 қарашадағы № 15 «Солтүстік Қазақстан облысы Тимирязев ауданы аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/144857/rus
