act_code: '7850'
requisite: Решение акима Северо-Казахстанской области от 7 ноября 2000 года № 211. Зарегистрировано Управлением юстиции Северо-Казахстанской области 11 декабря 2000 года № 186
title:
  rus: О подготовке военно-технических специалистов для Вооружённых Сил Республики Казахстан на 2000 – 2001 учебный год
  kaz: 2000-2001 оқу жылдарына арналған Қазақстан Республикасының Қарулы күштері үшін әскери-техникалық мамандар даярлау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-11-07
approved_by:
- '165000000003'
version_date:
  kaz: 2000-11-07
  rus: 2000-11-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/7850/kaz/07.11.2000
  rus: https://zan.gov.kz/client/#!/doc/7850/rus/07.11.2000
