act_code: '128420'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 29 декабря 2018 года № 39-5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 января 2019 года № 5193
title:
  rus: Об утверждении бюджета Новоишимского сельского округа района имени Габита Мусрепова на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Новоишим ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '165014000002'
version_date:
  kaz: 2019-05-27
  rus: 2019-05-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/128420/kaz/27.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128420/rus/27.05.2019
caused_by:
  code: '132087'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 27 мая 2019 года № 48-33. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июня 2019 года № 5427
  title:
    rus: О внесении изменений в решение маслихата района имени Габита Мусрепова от 29 декабря 2018 года № 39-5 «Об утверждении бюджета Новоишимского сельского округа района имени Габита Мусрепова на 2019-2021 годы»
    kaz: Ғабит Мүсірепов атындағы ауданы мәслихатының 2018 жылғы 29 желтоқсандағы № 39-5 «2019-2021 жылдарға арналған Ғабит Мүсірепов атындағы ауданы Новоишим ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132087/rus
