act_code: '162292'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 24 декабря 2021 года 7-13-1. Зарегистрировано в Министерстве юстиции Республики Казахстан 27 декабря 2021 года № 26099
title:
  rus: Об утверждении бюджета Айыртауского района на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Айыртау ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-24
approved_by:
- '165003000002'
version_date:
  kaz: 2021-12-24
  rus: 2021-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/162292/kaz/24.12.2021
  rus: https://zan.gov.kz/client/#!/doc/162292/rus/24.12.2021
