act_code: '70154'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 20 декабря 2012 года № 68. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 января 2013 года № 2062. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 25.12.2013 № 152
title:
  rus: О бюджете Тайыншинского района Северо-Казахстанской области на 2013-2015 годы
  kaz: 2013-2015 жылдарға арналған Солтүстік Қазақстан облысы Тайынша ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-12-20
approved_by:
- '165011000002'
version_date:
  kaz: 2013-09-06
  rus: 2013-09-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/70154/kaz/06.09.2013
  rus: https://zan.gov.kz/client/#!/doc/70154/rus/06.09.2013
caused_by:
  code: '74396'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 6 сентября 2013 года № 128. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 16 сентября 2013 года № 2358
  title:
    rus: О внесении изменений в решение маслихата Тайыншинского района Северо-Казахстанской области от 20 декабря 2012 года № 68 "О бюджете Тайыншинского района Северо-Казахстанской области на 2013-2015 годы"
    kaz: '"2013-2015 жылдарға арналған Солтүстік Қазақстан облысы Тайынша ауданының бюджеті туралы" Солтүстік Қазақстан облысы Тайынша аудандық мәслихатының 2012 жылғы 20 желтоқсандағы № 68 шешіміне өзгерістер енгізу туралы'
  link: https://zan.gov.kz/client/#!/doc/74396/rus
