act_code: '76077'
requisite: Решение акима Тимирязевского района Северо-Казахстанской области от 11 декабря 2013 года № 32. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 декабря 2013 года № 2453. Утратило силу (письмо аппарата акима Тимирязевского района Северо-Казахстанской области от 3 апреля 2014 года № 13.1.1-30/130)
title:
  rus: Об организации и обеспечении на территории Тимирязевского района Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2014 года
  kaz: Қазақстан Республикасының ер азаматтарын 2014 жылдың қаңтарынан наурызына дейін Солтүстік Қазақстан облысы Тимирязев ауданының аумағында тіркеуді және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-11
approved_by:
- '165012000003'
version_date:
  kaz: 2013-12-11
  rus: 2013-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/76077/kaz/11.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76077/rus/11.12.2013
