act_code: '210505'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 12 мая 2025 года № 29-14
title:
  rus: Об утверждении бюджета Уялинского сельского округа Акжарского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақжар ауданы Ұялы ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-12
approved_by:
- '165004000002'
version_date:
  kaz: 2025-11-17
  rus: 2025-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/210505/kaz/17.11.2025
  rus: https://zan.gov.kz/client/#!/doc/210505/rus/17.11.2025
caused_by:
  code: '217323'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 17 ноября 2025 года № 32-17
  title:
    rus: О внесении изменений в решение Акжарского районного маслихата от 12 мая 2025 года № 29-14 «Об утверждении бюджета Уялинского сельского округа Акжарского района на 2025-2027 годы»
    kaz: Ақжар аудандық мәслихатының 2025 жылғы 12 мамырдағы № 29-14 «2025-2027 жылдарға арналған Ақжар ауданы Ұялы ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217323/rus
