act_code: '117727'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 27 декабря 2017 года № 24/124. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2018 года № 4492
title:
  rus: О бюджете Покровского сельского округа Есильского района Северо-Казахстанской области на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Солтүстік Қазақстан облысы Есіл ауданы Покровка ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-27
approved_by:
- '165006000002'
version_date:
  kaz: 2018-12-07
  rus: 2018-12-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/117727/kaz/07.12.2018
  rus: https://zan.gov.kz/client/#!/doc/117727/rus/07.12.2018
caused_by:
  code: '127155'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 7 декабря 2018 года № 33/184. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 декабря 2018 года № 5079
  title:
    rus: О внесении изменения в решение маслихата Есильского района Северо-Казахстанской области от 27 декабря 2017 года № 24/124 «О бюджете Покровского сельского округа Есильского района Северо-Казахстанской области на 2018-2020 годы»
    kaz: Солтүстік Қазақстан облысы Есіл ауданы мәслихатының 2017 жылғы 27 желтоқсандағы № 24/124 «2018-2020 жылдарға арналған Солтүстік Қазақстан облысы Есіл ауданының Покровка ауылдық округінің бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/127155/rus
