act_code: '117595'
requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 25 декабря 2017 года № 18/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 января 2018 года № 4485
title:
  rus: О районном бюджете Тимирязевского района на 2018-2020 годы
  kaz: 2018-2020 жылдарға арналған Тимирязев ауданының аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-12-25
approved_by:
- '165012000002'
version_date:
  kaz: 2018-06-15
  rus: 2018-06-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/117595/kaz/15.06.2018
  rus: https://zan.gov.kz/client/#!/doc/117595/rus/15.06.2018
caused_by:
  code: '122936'
  requisite: Решение Тимирязевского районного маслихата Северо-Казахстанской области от 15 июня 2018 года № 24/2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 июня 2018 года № 4782
  title:
    rus: О внесении изменений в решение Тимирязевского районного маслихата от 25 декабря 2017 года № 18/1 «О районном бюджете Тимирязевского района на 2018-2020 годы»
    kaz: «2018-2020 жылдарға арналған Тимирязев ауданының аудандық бюджеті туралы» Тимирязев аудандық мәслихатының 2017 жылғы 25 желтоқсандағы № 18/1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/122936/rus
