act_code: '119783'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 7 марта 2018 года № 24/18. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 марта 2018 года № 4611. Утратило силу решением маслихата Кызылжарского района Северо-Казахстанской области от 12 августа 2022 года № 15/5 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: О повышении базовых ставок земельного налога по Кызылжарскому району
  kaz: Қызылжар ауданы бойынша жер салығының базалық мөлшерлемелерін жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-03-07
approved_by:
- '165008000002'
version_date:
  kaz: 2018-03-07
  rus: 2018-03-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/119783/kaz/07.03.2018
  rus: https://zan.gov.kz/client/#!/doc/119783/rus/07.03.2018
