act_code: '217610'
requisite: Решение акима Прибрежного сельского округа Кызылжарского района Северо-Казахстанской области от 24 ноября 2025 года № 86
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-24
approved_by:
- '165008015002'
version_date:
  kaz: 2025-11-24
  rus: 2025-11-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/217610/kaz/24.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217610/rus/24.11.2025
