act_code: '167457'
requisite: Решение акима Салкынкольского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 28 апреля 2022 года № 9. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 мая 2022 года № 27925
title:
  rus: О переименовании улицы Ленина в улицу Конституции в селе Салкынколь Салкынкольского сельского округа района имени Габита Мусрепова Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданының Салқынкөл ауылдық округінің Салқынкөл ауылындағы Ленин көшесін Конституция көшесі деп қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-04-28
approved_by:
- '165014014002'
version_date:
  kaz: 2022-04-28
  rus: 2022-04-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/167457/kaz/28.04.2022
  rus: https://zan.gov.kz/client/#!/doc/167457/rus/28.04.2022
