act_code: '66762'
requisite: Решение маслихата Северо-Казахстанской области от 21 июня 2012 года № 5/15. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 20 июля 2012 года № 1807. Утратило силу решением Северо-Казахстанского областного маслихата от 21 января 2015 года № 32/1
title:
  rus: О Правилах содержания собак и кошек
  kaz: Иттер мен мысықтарды ұстау ережесі туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2012-06-21
approved_by:
- '165000000002'
version_date:
  kaz: 2013-03-19
  rus: 2013-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/66762/kaz/19.03.2013
  rus: https://zan.gov.kz/client/#!/doc/66762/rus/19.03.2013
caused_by:
  code: '72244'
  requisite: Решение маслихата Северо-Казахстанской области от 19 марта 2013 года № 13/28. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 апреля 2013 года № 2257
  title:
    rus: О внесении изменений в некоторые решения Северо-Казахстанского областного маслихата
    kaz: Солтүстік Қазақстан облыстық мәслихатының кейбір шешімдеріне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/72244/rus
