act_code: '229910'
requisite: Решение акима Нежинского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 10 сентября 2026 года № 38
title:
  rus: Об установлении публичного сервитута
  kaz: Қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-09-10
approved_by:
- '165014010002'
version_date:
  kaz: 2026-09-10
  rus: 2026-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/229910/kaz/10.09.2026
  rus: https://zan.gov.kz/client/#!/doc/229910/rus/10.09.2026
