act_code: '76078'
requisite: Решение акима Жамбылского района Северо-Казахстанской области от 9 декабря 2013 года № 64. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 декабря 2013 года № 2454. Утратило силу (письмо аппарата акима Жамбылского района Северо-Казахстанской области от 30 июня 2014 года № 8.1.5-2/486)
title:
  rus: Об организации и обеспечении на территории Жамбылского района Северо-Казахстанской области приписки и медицинского освидетельствования граждан мужского пола Республики Казахстан с января по март 2014 года
  kaz: Қазақстан Республикасының ер азаматтарын 2014 жылдың қаңтарынан наурызына дейін Солтүстік Қазақстан облысы Жамбыл ауданының аумағында тіркеуді және медициналық куәландыруды ұйымдастыру және қамтамасыз ету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-12-09
approved_by:
- '165007004002'
version_date:
  kaz: 2013-12-09
  rus: 2013-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/76078/kaz/09.12.2013
  rus: https://zan.gov.kz/client/#!/doc/76078/rus/09.12.2013
