act_code: '205800'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 25 декабря 2024 года № 1/19. Утратило силу решением Петропавловского городского маслихата Северо-Казахстанской области от 20 мая 2025 года № 1/23 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета города Петропавловск на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Петропавл қаласының бюджетің бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '165002000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205800/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205800/rus/25.12.2024
