act_code: '205800'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 25 декабря 2024 года № 1/19. Утратило силу решением Петропавловского городского маслихата Северо-Казахстанской области от 20 мая 2025 года № 1/23 (вводится в действие с 1 января 2025 года)
title:
  rus: Об утверждении бюджета города Петропавловск на 2025 - 2027 годы
  kaz: 2025 - 2027 жылдарға арналған Петропавл қаласының бюджетің бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '165002000002'
version_date:
  kaz: 2025-02-27
  rus: 2025-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205800/kaz/27.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205800/rus/27.02.2025
caused_by:
  code: '207748'
  requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 27 февраля 2025 года № 3/21. Утратило силу решением Петропавловского городского маслихата Северо-Казахстанской области от 20 мая 2025 года № 1/23 (вводится в действие с 1 января 2025 года)
  title:
    rus: О внесении изменений в решение Петропавловского городского маслихата от 25 декабря 2024 года № 1/19 «Об утверждении бюджета города Петропавловск на 2025 - 2027 годы»
    kaz: Петропавл қалалық мәслихатының 2024 жылғы 25 желтоқсандағы № 1/19 «Петропавл қаласының 2025 - 2027 жылдарға арналған бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207748/rus
