act_code: '65802'
requisite: Решение акима Тимирязевского сельского округа Тимирязевского района Северо-Казахстанской области от 7 мая 2012 года № 31. Зарегистрировано Управлением юстиции Тимирязевского района Северо-Казахстанской области 4 июня 2012 года № 13-12-152
title:
  rus: О наименовании новой улицы села Тимирязево Тимирязевского сельского округа Тимирязевского района
  kaz: Тимирязев ауданы Тимирязев ауылдық округі Тимирязев ауылының жаңа көшесінің атауы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-07
approved_by:
- '165012001001'
version_date:
  kaz: 2012-05-07
  rus: 2012-05-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/65802/kaz/07.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65802/rus/07.05.2012
