act_code: '65802'
requisite: Решение акима Тимирязевского сельского округа Тимирязевского района Северо-Казахстанской области от 7 мая 2012 года № 31. Зарегистрировано Управлением юстиции Тимирязевского района Северо-Казахстанской области 4 июня 2012 года № 13-12-152
title:
  rus: О наименовании новой улицы села Тимирязево Тимирязевского сельского округа Тимирязевского района
  kaz: Тимирязев ауданы Тимирязев ауылдық округі Тимирязев ауылының жаңа көшесінің атауы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-07
approved_by:
- '165012001001'
version_date:
  kaz: 2018-07-02
  rus: 2018-07-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/65802/kaz/02.07.2018
  rus: https://zan.gov.kz/client/#!/doc/65802/rus/02.07.2018
caused_by:
  code: '123681'
  requisite: Решение акима Тимирязевского сельского округа Тимирязевского района Северо-Казахстанской области от 2 июля 2018 года № 30. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 16 июля 2018 года № 4838
  title:
    rus: О внесении изменений в решение акима Тимирязевского сельского округа Тимирязевского района Северо-Казахстанской области от 4 июня 2012 года № 31 «О наименовании новой улицы села Тимирязево Тимирязевского сельского округа Тимирязевского района»
    kaz: «Тимирязев ауданы Тимирязев селолық округі Тимирязев селосының жаңа көшесінің атауы туралы» Солтүстік Қазақстан облысы Тимирязев ауданы Тимирязев ауылдық округі әкімінің 2012 жылғы 4 маусымдағы № 31 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123681/rus
