act_code: '55925'
requisite: Решение акима Воскресеновского сельского округа Мамлютского района Северо-Казахстанской области от 29 ноября 2010 года № 17. Зарегистрировано Управлением юстиции Мамлютского района Северо-Казахстанской области 13 декабря 2010 года № 13-10-126
title:
  rus: О присвоении наименований составных частей населенных пунктов Воскресеновского сельского округа Мамлютского района
  kaz: Мамлют ауданы Воскресенов ауылдық округінің елді мекендерінің құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-29
approved_by:
- '165009003000'
version_date:
  kaz: 2010-11-29
  rus: 2010-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/55925/kaz/29.11.2010
  rus: https://zan.gov.kz/client/#!/doc/55925/rus/29.11.2010
