act_code: '68106'
requisite: Решение акима Ивановского сельского округа Аккайынского района Северо-Казахстанской области от 6 сентября 2012 года № 6. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 октября 2012 года № 1903
title:
  rus: О присвоении наименований улицам села Ульго Аккайынского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданының Үлгі ауылы көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-09-06
approved_by:
- '165005005001'
version_date:
  kaz: 2018-09-12
  rus: 2018-09-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/68106/kaz/12.09.2018
  rus: https://zan.gov.kz/client/#!/doc/68106/rus/12.09.2018
caused_by:
  code: '125024'
  requisite: Решение акима Ивановского сельского округа Аккайынского района Северо-Казахстанской области от 12 сентября 2018 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 5 октября 2018 года № 4908
  title:
    rus: О внесении изменений в решение акима Ивановского сельского округа Аккайынского района Северо-Казахстанской области от 6 сентября 2012 года № 6 «О присвоении наименований улицам села Ульго Аккайынского района Северо - Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы Ивановка селолық округі әкімінің 2012 жылғы 6 қыркүйектегі № 6 «Солтүстік Қазақстан облысы Аққайың ауданының Үлгі селосы көшелеріне атау беру туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/125024/rus
