act_code: '209389'
requisite: Решение акима города Мамлютка Мамлютского района Северо-Казахстанской области от 21 апреля 2025 года № 33
title:
  rus: Об установлении публичного сервитута (право ограниченного целевого пользования чужим земельным участком)
  kaz: Мекеме туралы қоғамдық сервитут (шектеулі мақсатты пайдалану құқығы біреудің жері)
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-04-21
approved_by:
- '165009012001'
version_date:
  kaz: 2025-04-21
  rus: 2025-04-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/209389/kaz/21.04.2025
  rus: https://zan.gov.kz/client/#!/doc/209389/rus/21.04.2025
