act_code: '153882'
requisite: Решение акима Бидайыкского сельского округа Уалихановского района Северо-Казахстанской области от 19 марта 2021 года № 13. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 марта  2021 года № 7190
title:
  rus: О присвоении наименования безымянной улице села Ондирис Бидайыкского сельского округа Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Бидайық ауылдық округі Өндіріс ауылының атауы жоқ көшесіне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-19
approved_by:
- '165013004002'
version_date:
  kaz: 2021-03-19
  rus: 2021-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/153882/kaz/19.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153882/rus/19.03.2021
