act_code: '118636'
requisite: Решение акима Амангельдинского сельского округа Уалихановского района Северо-Казахстанской области от 16 января 2018 года № 2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 января 2018 года № 4561
title:
  rus: О снятии ограничительных мероприятий по бруцеллезу крупного рогатого скота на стадо в трех километрах юго-восточнее от села Тлеусай Амангельдинского сельского округа Уалихановского района Северо–Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы Амангелді ауылдық округі Тлеусай ауылының оңтүстік-шығысынан үш шақырым қашықтықта тұрған ірі қара мал табынында бруцеллез ауруы бойынша шектеу шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-01-16
approved_by:
- '165013003002'
version_date:
  kaz: 2018-01-16
  rus: 2018-01-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/118636/kaz/16.01.2018
  rus: https://zan.gov.kz/client/#!/doc/118636/rus/16.01.2018
