act_code: '7846'
requisite: Решение акима Северо-Казахстанской области от 11 сентября 2000 года № 175. Зарегистрировано Управлением юстиции Северо-Казахстанской области 20 сентября 2000 года за № 153
title:
  rus: О месячнике по оказанию социальной помощи малообеспеченным пенсионерам и инвалидам
  kaz: Аз қамтамасыз етілген зейнеткерлер мен мүгедектерге әлеуметтік көмек көрсету жөніндегі айлық туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2000-09-10
approved_by:
- '165000000003'
version_date:
  kaz: 2000-09-10
  rus: 2000-09-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/7846/kaz/10.09.2000
  rus: https://zan.gov.kz/client/#!/doc/7846/rus/10.09.2000
