act_code: '140229'
requisite: Решение акима Акбулакского сельского округа Уалихановского района Северо-Казахстанской области от 11 марта 2020 года № 9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 марта 2020 года № 6087
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-03-11
approved_by:
- '165013012002'
version_date:
  kaz: 2020-03-11
  rus: 2020-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/140229/kaz/11.03.2020
  rus: https://zan.gov.kz/client/#!/doc/140229/rus/11.03.2020
