act_code: '210033'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 5 мая 2025 года № 29-1
title:
  rus: Об утверждении бюджета Акжарского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақжар аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-05
approved_by:
- '165004000002'
version_date:
  kaz: 2025-05-05
  rus: 2025-05-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/210033/kaz/05.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210033/rus/05.05.2025
