act_code: '210033'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 5 мая 2025 года № 29-1
title:
  rus: Об утверждении бюджета Акжарского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ақжар аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-05
approved_by:
- '165004000002'
version_date:
  kaz: 2025-08-26
  rus: 2025-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/210033/kaz/26.08.2025
  rus: https://zan.gov.kz/client/#!/doc/210033/rus/26.08.2025
caused_by:
  code: '213694'
  requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 26 августа 2025 года № 31-5
  title:
    rus: О внесении изменений в решение Акжарского районного маслихата от 5 мая 2025 года № 29-1 «Об утверждении бюджета Акжарского района на 2025-2027 годы»
    kaz: Ақжар аудандық мәслихатының «2025-2027 жылдарға арналған Ақжар аудандық бюджетін бекіту туралы» 2025 жылғы 5 мамырдағы № 29-1 шешіміне өзгерістер еңгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213694/rus
