act_code: '79869'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 31 марта 2014 года № 23-8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 6 мая 2014 года № 2750. Утратило силу решением маслихата района имени Габита Мусрепова Северо-Казахстанской области от 4 сентября 2023 года № 7-6 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей улиц и сел для участия в сходе местного сообщества Дружбинского сельского округа района имени Габита Мусрепова Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ғабит Мүсірепов атындағы ауданының Дружба ауылдық округінде жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиындарына қатысу үшін көшелер мен және ауылдар тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-31
approved_by:
- '165014000002'
version_date:
  kaz: 2014-03-31
  rus: 2014-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/79869/kaz/31.03.2014
  rus: https://zan.gov.kz/client/#!/doc/79869/rus/31.03.2014
