act_code: '2482'
requisite: Решение акима Северо-Казахстанской области от 10 января 1999 года № 8. Зарегистрировано Управлением юстиции Северо-Казахстанской области 22 февраля 1999 года № 57
title:
  rus: О переименовании села Комсомольское Жамбылского района в село Узынколь
  kaz: Жамбыл ауданы Комсомольское селосының атауын Ұзынкөл селосы деп өзгерту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1999-01-10
approved_by:
- '165000000003'
version_date:
  kaz: 1999-01-10
  rus: 1999-01-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/2482/kaz/10.01.1999
  rus: https://zan.gov.kz/client/#!/doc/2482/rus/10.01.1999
