act_code: '205911'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 27 декабря 2024 года № 8-22-21
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Айыртаускому району Северо-Казахстанской области на 2025 - 2029 годы
  kaz: 2025 – 2029 жылдарға арналған Солтүстік Қазақстан облысы Айыртау ауданы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2024-12-27
approved_by:
- '165003000002'
version_date:
  kaz: 2025-07-31
  rus: 2025-07-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/205911/kaz/31.07.2025
  rus: https://zan.gov.kz/client/#!/doc/205911/rus/31.07.2025
caused_by:
  code: '213014'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 31 июля 2025 года № 8-29-2
  title:
    rus: О внесении изменений в решение Айыртауского районного маслихата Северо-Казахстанской области от 27 декабря 2024 года № 8-22-21 «Об утверждении Плана по управлению пастбищами и их использованию по Айыртаускому району Северо-Казахстанской области на 2025-2029 годы»
    kaz: «2025 – 2029 жылдарға арналған Солтүстік Қазақстан облысы Айыртау ауданы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі жоспарды бекіту туралы» Айыртау аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 8-22-21 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213014/rus
