act_code: '137360'
requisite: Решение акима Жамбылского района Северо-Казахстанской области от 23 декабря 2019 года № 45. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 декабря 2019 года № 5748
title:
  rus: Об образовании избирательных участков на территории Жамбылского района Северо - Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-23
approved_by:
- '165007000003'
version_date:
  kaz: 2019-12-23
  rus: 2019-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/137360/kaz/23.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137360/rus/23.12.2019
