act_code: '128412'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 29 декабря 2018 года № 36/14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2019 года № 5158
title:
  rus: Об утверждении бюджета Соколовского сельского округа Кызылжарского района на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Қызылжар ауданының Соколов ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '165008000002'
version_date:
  kaz: 2019-06-03
  rus: 2019-06-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/128412/kaz/03.06.2019
  rus: https://zan.gov.kz/client/#!/doc/128412/rus/03.06.2019
caused_by:
  code: '132262'
  requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 3 июня 2019 года № 42/9. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 7 июня 2019 года № 5438
  title:
    rus: О внесении изменений в решение Кызылжарского районного маслихата Северо-Казахстанской области от 29 декабря 2018 года № 36/14 «Об утверждении бюджета Соколовского сельского округа Кызылжарского района на 2019-2021 годы»
    kaz: Солтүстік Қазақстан облысы Қызылжар аудандық мәслихатының 2018 жылғы 29 желтоқсандағы № 36/14 «2019-2021 жылдарға арналған Қызылжар ауданының Соколов ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/132262/rus
