act_code: '52874'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 29 апреля 2010 года № 25/4. Зарегистрировано Управлением юстиции района Шал акына Северо-Казахстанской области 1 июня 2010 года № 13-14-102. Утратило силу решением маслихата района Шал акына Северо-Казахстанской области от 30 марта 2018 года № 23/5
title:
  rus: Об установлении единой ставки фиксированного налога для всех налогоплательщиков, осуществляющих деятельность на территории района Шал акына
  kaz: Шал ақын ауданының аумағында қызметін жүзеге асыратын барлық салық төлеушілерге тіркелген салықтың бірыңғай төлемақыларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-04-29
approved_by:
- '165010000002'
version_date:
  kaz: 2010-04-29
  rus: 2010-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/52874/kaz/29.04.2010
  rus: https://zan.gov.kz/client/#!/doc/52874/rus/29.04.2010
