act_code: '227953'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 15 июля 2026 года № 44/2
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан Жамбылского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2026-07-15
approved_by:
- '165007000002'
version_date:
  kaz: 2026-07-15
  rus: 2026-07-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/227953/kaz/15.07.2026
  rus: https://zan.gov.kz/client/#!/doc/227953/rus/15.07.2026
