act_code: '45995'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 10 апреля 2009 года № 4-14-4. Зарегистрировано Управлением юстиции Айыртауского района Северо-Казахстанской области 15 мая 2009 года № 13-3-98. Утратило силу решением Айыртауского районного маслихата Северо-Казахстанской области от 13 апреля 2018 года № 6-18-4
title:
  rus: О повышении ставок земельного налога
  kaz: Жер салығының ставкаларын жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-04-10
approved_by:
- '165003000002'
version_date:
  kaz: 2009-04-10
  rus: 2009-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/45995/kaz/10.04.2009
  rus: https://zan.gov.kz/client/#!/doc/45995/rus/10.04.2009
