act_code: '85715'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 24 декабря 2014 года № 244. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 8 января 2015 года № 3047
title:
  rus: О бюджете Тайыншинского района Северо-Казахстанской области на 2015-2017 годы
  kaz: Солтүстік Қазақстан облысы Тайынша ауданының 2015 - 2017 жылдарға арналған бюджеті тұралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-24
approved_by:
- '165011000002'
version_date:
  kaz: 2015-01-19
  rus: 2015-01-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/85715/kaz/19.01.2015
  rus: https://zan.gov.kz/client/#!/doc/85715/rus/19.01.2015
caused_by:
  code: '86734'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 19 января 2015 года № 254. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 февраля 2015 года № 3101
  title:
    rus: О внесении изменений в решение маслихата Тайыншинского района Северо-Казахстанской области от 24 декабря 2014 года № 244 "О бюджете Тайыншинского района Северо-Казахстанской области на 2015 - 2017 годы"
    kaz: «Солтүстік Қазақстан облысы Тайынша ауданының 2015 - 2017 жылдарға арналған бюджеті туралы» Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2014 жылғы 24 желтоқсандағы № 244 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/86734/rus
