act_code: '192579'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 29 декабря 2023 года № 13/19
title:
  rus: Об утверждении бюджета Сухорабовского сельского округа района Шал акына на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Шал ақын ауданы Сухорабов ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-29
approved_by:
- '165010000002'
version_date:
  kaz: 2023-12-29
  rus: 2023-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/192579/kaz/29.12.2023
  rus: https://zan.gov.kz/client/#!/doc/192579/rus/29.12.2023
