act_code: '200227'
requisite: Решение акима Есильского сельского округа Тимирязевского района Северо-Казахстанской области от 23 августа 2024 года № 7
title:
  rus: О предоставлении права ограниченного целевого пользования (публичный сервитут) на земельный участок
  kaz: Жер учаскесіне шектеулі пайдалану құқық (қауымдық сервитут) беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-23
approved_by:
- '165012009002'
version_date:
  kaz: 2024-08-23
  rus: 2024-08-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/200227/kaz/23.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200227/rus/23.08.2024
