act_code: '135075'
requisite: Решение акима Карасуского сельского округа Уалихановского района Северо-Казахстанской области от 3 октября 2019 года № 6. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 октября 2019 года № 5597
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-10-03
approved_by:
- '165013006002'
version_date:
  kaz: 2019-10-03
  rus: 2019-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/135075/kaz/03.10.2019
  rus: https://zan.gov.kz/client/#!/doc/135075/rus/03.10.2019
