act_code: '46816'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2009 жылғы 22 маусымдағы № 7-14с шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2009 жылғы 10 шілдеде № 13-13-108 тіркелді. Күші жойылды - Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2013 жылғы 29 наурыздағы № 19-10с шешімімен
title:
  rus: Уәлиханов ауданы бойынша төлемдердің жеке түрдегі мөлшерлемесі туралы
  kaz: Уәлиханов ауданы бойынша төлемдердің жеке түрдегі мөлшерлемесі туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-06-22
approved_by:
- '165013000002'
version_date:
  kaz: 2009-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/46816/kaz/22.06.2009
