act_code: '159907'
requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 19 октября 2021 года № 6-4. Зарегистрировано в Министерстве юстиции Республики Казахстан 1 ноября 2021 года № 24984
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Аккайынском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Аққайың ауданында мүгедек бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-10-19
approved_by:
- '165005000002'
version_date:
  kaz: 2023-04-20
  rus: 2023-04-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/159907/kaz/20.04.2023
  rus: https://zan.gov.kz/client/#!/doc/159907/rus/20.04.2023
caused_by:
  code: '180476'
  requisite: Решение маслихата Аккайынского района Северо-Казахстанской области от 20 апреля 2023 года № 2-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 апреля 2023 года № 7491-15
  title:
    rus: О внесении изменения в решение маслихата Аккайынского района Северо-Казахстанской области от 19 октября 2021 года № 6-4 «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в Аккайынском районе Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Аққайың ауданы мәслихатының 2021 жылғы 19 қазандағы № 6-4 «Солтүстік Қазақстан облысы Аққайың ауданында мүгедек бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/180476/rus
