act_code: '79750'
requisite: Решение маслихата Есильского района Северо-Казахстанской области от 27 марта 2014 года № 29/186. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 5 мая 2014 года № 2730. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 19 сентября 2023 года № 8-94 (вводится в действие по истечению десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей улиц для участия в сходе местного сообщества Явленского сельского округа Есильского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Есіл ауданы Явленка ауылдық округінің жергілікті қоғамдастығының бөлек жиындарын өткізу қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін көшелер тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2014-03-27
approved_by:
- '165006000002'
version_date:
  kaz: 2022-03-17
  rus: 2022-03-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/79750/kaz/17.03.2022
  rus: https://zan.gov.kz/client/#!/doc/79750/rus/17.03.2022
caused_by:
  code: '165626'
  requisite: Решение маслихата Есильского района Северо-Казахстанской области от 17 марта 2022 года № 17/201. Утратило силу решением маслихата Есильского района Северо-Казахстанской области от 19 сентября 2023 года № 8-94 (вводится в действие по истечению десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение маслихата Есильского района Северо-Казахстанской области от 27 марта 2014 года № 29/186 «Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей улиц и многоквартирных жилых домов для участия в сходе местного сообщества села Явленка»
    kaz: «Явленка ауылының жергілікті қоғамдастығының бөлек жиындарын өткізу қағидаларын және жергілікті қоғамдастық жиынына қатысу үшін көшелер мен көппәтерлі тұрғын үй тұрғындары өкілдерінің сандық құрамын бекіту туралы» Есіл ауданы мәслихатының 2014 жылғы 27 наурыздағы № 29/186 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/165626/rus
