act_code: '208003'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 6 марта 2025 года № 26/7. Действовало по 31 декабря 2025 года в соответствии с пунктом 2 настоящего решения
title:
  rus: Об установлении стимулирующей надбавки к должностному окладу работников коммунального государственного учреждения «Аппарат акима Кайранкольского сельского округа Жамбылского района Северо-Казахстанской области», финансируемых из местного бюджета
  kaz: Жергілікті бюджеттен қаржыландырылатын «Солтүстік Қазақстан облысы Жамбыл ауданы Қайранкөл ауылдық округі әкімінің аппараты» коммуналдық мемлекеттік мекемесі жұмыскерлерінің лауазымдық айлықақыларына ынталандыру үстемеақыларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-03-06
approved_by:
- '165007000002'
version_date:
  kaz: 2025-03-06
  rus: 2025-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/208003/kaz/06.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208003/rus/06.03.2025
