act_code: '1015'
requisite: Решение акима Северо-Казахстанской области от 11 мая 1998 года № 112. Зарегистрировано Управлением юстиции Северо-Казахстанской области 5 июня 1998 года за № 17. Утратило силу решением акима Северо-Казахстанской области от 20 декабря 2017 года № 41
title:
  rus: О создании областного Центра проблем формирования здорового образа жизни
  kaz: Салауатты өмір қалыптастыру проблемаларының облыстық орталығын құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 1998-05-10
approved_by:
- '165000000003'
version_date:
  kaz: 1998-05-10
  rus: 1998-05-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/1015/kaz/10.05.1998
  rus: https://zan.gov.kz/client/#!/doc/1015/rus/10.05.1998
