act_code: '149723'
requisite: Решение акима Коктерекского сельского округа Уалихановского района Северо-Казахстанской области от 10 декабря 2020 года № 14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 10 декабря 2020 года № 6795
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-10
approved_by:
- '165013009002'
version_date:
  kaz: 2020-12-10
  rus: 2020-12-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/149723/kaz/10.12.2020
  rus: https://zan.gov.kz/client/#!/doc/149723/rus/10.12.2020
