act_code: '39254'
requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 20 марта 2008 № 7/4. Зарегистрировано Управлением юстиции Кызылжарского района Северо-Казахстанской области 28 апреля 2008 года № 13-8-75. Утратило силу - решением маслихата Кызылжарского района Северо-Казахстанской области от 5 ноября 2012 № 8/12
title:
  rus: О установлении повышенных на 25 процентов должностных окладов и тарифных ставок специалистам социального обеспечения, образования и культуры, работающих на территории района
  kaz: Аудан аумағында жұмыс істейтін әлеуметтік қамтамасыз ету, білім және мәдениет мамандарына лауазымдық еңбекақылары мен тарифтік ставкаларына 25 пайыздық жоғарылатуды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2008-03-20
approved_by:
- '165008000002'
version_date:
  kaz: 2008-03-20
  rus: 2008-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/39254/kaz/20.03.2008
  rus: https://zan.gov.kz/client/#!/doc/39254/rus/20.03.2008
