act_code: '202612'
requisite: Решение Тайыншинского районного маслихата Северо-Казахстанской области от 8 ноября 2024 года № 227/18. Зарегистрирован в Департаменте юстиции Северо-Казахстанской области 12 ноября 2024 года № 7823-15
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога на 2025 год в Тайыншинском районе Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Тайынша ауданының 2025 жылға арналған бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-08
approved_by:
- '165011000002'
version_date:
  kaz: 2024-11-08
  rus: 2024-11-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/202612/kaz/08.11.2024
  rus: https://zan.gov.kz/client/#!/doc/202612/rus/08.11.2024
