act_code: '85505'
requisite: Решение маслихата Северо-Казахстанской области от 12 декабря 2014 года № 31/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 декабря 2014 года № 3035
title:
  rus: Об областном бюджете Северо-Казахстанской области на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған Солтүстік Қазақстан облысының облыстық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-12
approved_by:
- '165000000002'
version_date:
  kaz: 2015-08-17
  rus: 2015-08-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/85505/kaz/17.08.2015
  rus: https://zan.gov.kz/client/#!/doc/85505/rus/17.08.2015
caused_by:
  code: '93398'
  requisite: Решение маслихата Северо-Казахстанской области от 17 августа 2015 года № 37/15. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 3 сентября 2015 года № 3367
  title:
    rus: О внесении изменений в решение Северо-Казахстанского областного маслихата от 12 декабря 2014 года № 31/1 «Об областном бюджете Северо-Казахстанской области на 2015-2017 годы»
    kaz: «2015-2017 жылдарға арналған Солтүстік Қазақстан облысының облыстық бюджеті туралы» Солтүстік Қазақстан облыстық мәслихаттың 2014 жылғы 12 желтоқсандағы № 31/1 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/93398/rus
