act_code: '173440'
requisite: Решение акима сельского округа Үлкен Қараой Акжарского района Северо-Казахстанской области от 31 октября 2022 года № 16. Зарегистрирован в Министерстве юстиции Республики Казахстан 4 ноября 2022 года № 30416
title:
  rus: О переименовании улиц села Баймырза сельского округа Үлкен Қараой Акжарского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Ақжар ауданы Үлкен Қараой ауылдық округінің Баймырза ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-10-31
approved_by:
- '165004010002'
version_date:
  kaz: 2022-10-31
  rus: 2022-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/173440/kaz/31.10.2022
  rus: https://zan.gov.kz/client/#!/doc/173440/rus/31.10.2022
