act_code: '192687'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 28 декабря 2023 года № 2-13 с
title:
  rus: Об утверждении бюджета Акбулакского сельского округа Уалихановского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Уәлиханов ауданы Ақбұлақ ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '165013000002'
version_date:
  kaz: 2024-10-09
  rus: 2024-10-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/192687/kaz/09.10.2024
  rus: https://zan.gov.kz/client/#!/doc/192687/rus/09.10.2024
caused_by:
  code: '201766'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 9 октября 2024 года № 2-22 с
  title:
    rus: О внесении изменений в решение Уалихановского районного маслихата от 28 декабря 2023 года № 2-13 с «Об утверждении бюджета Акбулакского сельского округа Уалихановского района на 2024-2026 годы»
    kaz: Уәлиханов аудандық мәслихатының 2023 жылғы 28 желтоқсандағы № 2-13 с «2024-2026 жылдарға арналған Уәлиханов ауданы Ақбұлақ ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістерді енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201766/rus
