act_code: '3232'
requisite: Решение акима Северо-Казахстанской области от 15 января 1999 года № 10. Зарегистрировано Управлением юстиции Северо-Казахстанской области 7 апреля 1999 года за № 68. Утратило силу - решением акима  Северо-Казахстанской областиот 4 декабря 2000 года № 228
title:
  rus: Вопросы учреждений-администраторов программ, финансируемых из областного бюджета
  kaz: Облыстық бюджеттен қаржыландырылатын мекемелердің-бағдарлама администраторларының мәселелері
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 1999-01-15
approved_by:
- '165000000003'
version_date:
  kaz: 1999-01-15
  rus: 1999-01-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/3232/kaz/15.01.1999
  rus: https://zan.gov.kz/client/#!/doc/3232/rus/15.01.1999
