act_code: '179553'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 7 апреля 2023 года № 04. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 8 августа 2025 года № 365/25 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» коммунального государственного учреждения «Аппарат маслихата Тайыншинского района Северо-Казахстанской области»
  kaz: «Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының аппараты» коммуналдық мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-04-07
approved_by:
- '165011000002'
version_date:
  kaz: 2025-06-12
  rus: 2025-06-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/179553/kaz/12.06.2025
  rus: https://zan.gov.kz/client/#!/doc/179553/rus/12.06.2025
caused_by:
  code: '211319'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 12 июня 2025 года № 321/24. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 8 августа 2025 года № 365/25 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение маслихата  Тайыншинского района Северо-Казахстанской области от 7 апреля 2023 года № 04 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» коммунального государственного учреждения «Аппарат маслихата Тайыншинского района Северо-Казахстанской области»»
    kaz: Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының  2023 жылғы 7 сәуірдегі № 04 ««Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының аппараты» коммуналдық мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211319/rus
