act_code: '137610'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 24 декабря 2019 года № 62/2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 декабря 2019 года № 5765
title:
  rus: Об утверждении районного бюджета на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған аудандық бюджетті бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-24
approved_by:
- '165009000002'
version_date:
  kaz: 2019-12-24
  rus: 2019-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/137610/kaz/24.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137610/rus/24.12.2019
