act_code: '62859'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2011 жылғы 21 желтоқсандағы № 4-37с шешімі. Солтүстік Қазақстан облысының Әділет департаментінде 2012 жылғы 18 қаңтарда № 13-13-154 тіркелді. Күші жойылды - Солтүстік Қазақстан облысы Уәлиханов аудандық әкімдігінің 2012 жылғы 8 тамыздағы № 5-5с шешімімен
title:
  rus: 2012 жылы Уәлиханов ауданының ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
  kaz: 2012 жылы Уәлиханов ауданының ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет және спорт мамандарына көтерме жәрдемақы және тұрғын үй сатып алу үшін әлеуметтік қолдауды ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-12-21
approved_by:
- '165013000002'
version_date:
  kaz: 2011-12-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/62859/kaz/21.12.2011
