act_code: '153334'
requisite: Решение акима Нежинского сельского округа района имени Габита Мусрепова Северо-Казахстанской области от 4 марта 2021 года № 10. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 марта 2021 года № 7151
title:
  rus: Об установлении публичного сервитута на земельный участок товариществу с ограниченной ответственностью «Нежинка-Ерке»
  kaz: «Нежинка-Ерке» жауапкершілігі шектеулі серіктестігіне жер учаскесіне қауымдық сервитут белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-03-04
approved_by:
- '165014010002'
version_date:
  kaz: 2021-03-04
  rus: 2021-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/153334/kaz/04.03.2021
  rus: https://zan.gov.kz/client/#!/doc/153334/rus/04.03.2021
