act_code: '138442'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 8 января 2020 года № 332. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 14 января 2020 года № 5954
title:
  rus: Об утверждении бюджета Чкаловского сельского округа Тайыншинского района Северо-Казахстанской области на 2020 - 2022 годы
  kaz: Солтүстік Қазақстан облысы Тайынша ауданы Чкалов ауылдық округінің 2020 – 2022 жылдарға арналған бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-01-08
approved_by:
- '165011000002'
version_date:
  kaz: 2020-12-09
  rus: 2020-12-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/138442/kaz/09.12.2020
  rus: https://zan.gov.kz/client/#!/doc/138442/rus/09.12.2020
caused_by:
  code: '149755'
  requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 9 декабря 2020 года № 412. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 декабря 2020 года № 6799
  title:
    rus: О внесении изменений в решение маслихата Тайыншинского района Северо-Казахстанской области от 8 января 2020 года № 332 «Об утверждении бюджета Чкаловского сельского округа Тайыншинского района Северо-Казахстанской области на 2020 - 2022 годы»
    kaz: Солтүстік Қазақстан облысы Тайынша ауданы мәслихатының 2020 жылғы 8 қаңтардағы № 332 «Солтүстік Қазақстан облысы Тайынша ауданы Чкалов ауылдық округінің 2020 - 2022 жылдарға арналған бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/149755/rus
