act_code: '191874'
requisite: Решение Акжарского районного маслихата Северо-Казахстанской области от 27 декабря 2023 года № 13-15
title:
  rus: Об утверждении бюджета Ленинградского сельского округа Акжарского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Ақжар ауданы Ленинград ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '165004000002'
version_date:
  kaz: 2023-12-27
  rus: 2023-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/191874/kaz/27.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191874/rus/27.12.2023
