act_code: '186535'
requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 19 сентября 2023 года № 10/5
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и количественного состава представителей жителей улиц города Мамлютка и сел сельских округов Мамлютского района Северо-Казахстанской области для участия в сходе местного сообщества
  kaz: Солтүстік Қазақстан облысы Мамлют ауданының жергілікті қоғамдастық бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиындарына қатысу үшін Мамлютка қаласы көшелері және ауылдық округтердің ауыл тұрғындары өкілдерінің сандық құрамын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-09-19
approved_by:
- '165009000002'
version_date:
  kaz: 2025-03-14
  rus: 2025-03-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/186535/kaz/14.03.2025
  rus: https://zan.gov.kz/client/#!/doc/186535/rus/14.03.2025
caused_by:
  code: '208318'
  requisite: Решение маслихата Мамлютского района Северо-Казахстанской области от 14 марта 2025 года № 39/7
  title:
    rus: О внесении изменений в решение маслихата Мамлютского района Северо-Казахстанской области от 19 сентября 2023 года № 10/5 «Об утверждении Правил проведения раздельных сходов местного сообщества и  количественного состава представителей жителей улиц города Мамлютка и сел сельских округов Мамлютского района Северо-Казахстанской области для участия в сходе местного сообщества»
    kaz: Солтүстік Қазақстан облысы Мамлют ауданы мәслихатының 2023 жылғы 19 қыркүйектегі № 10/5 «Солтүстік Қазақстан облысы Мамлют ауданының жергілікті қоғамдастық бөлек жиындарын өткізудің қағидаларын және жергілікті қоғамдастық жиындарына қатысу үшін Мамлютка қаласы көшелері және ауылдық округтердің ауыл тұрғындары  өкілдерінің сандық құрамын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208318/rus
