act_code: '92676'
requisite: Решение Северо-Казахстанского областного маслихата от 14 июля 2015 года № 36/7. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 12 августа 2015 года № 3346
title:
  rus: Об утверждении Правил содержания животных на территории Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы аумағында жануарларды ұстау Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2015-07-14
approved_by:
- '165000000002'
version_date:
  kaz: 2023-12-15
  rus: 2023-12-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/92676/kaz/15.12.2023
  rus: https://zan.gov.kz/client/#!/doc/92676/rus/15.12.2023
caused_by:
  code: '190371'
  requisite: Решение Северо-Казахстанского областного маслихата от 15 декабря 2023 года № 9/4. Зарегистрировано в Департаменте юстиции Северо-Казахстанской области 21 декабря 2023 года № 7656-15
  title:
    rus: О внесении изменений в решение Северо-Казахстанского областного маслихата от 14 июля 2015 года № 36/7 «Об утверждении Правил содержания животных на территории Северо-Казахстанской области»
    kaz: «Солтүстік Қазақстан облысы аумағында жануарларды ұстау Қағидаларын бекіту туралы» Солтүстік Қазақстан облыстық мәслихатының 2015 жылғы 14 шілдедегі № 36/7 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190371/rus
