act_code: '223871'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 27 марта 2026 года № 39/5
title:
  rus: Об установлении стимулирующих надбавок к должностным окладам работников организаций, финансируемых из местного бюджета Жамбылского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Жамбыл ауданының жергілікті бюджеттен қаржыландырылатын ұйымдар жұмыскерлерінің лауазымдық айлықақыларына ынталандыру үстемеақыларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-27
approved_by:
- '165007000002'
version_date:
  kaz: 2026-03-27
  rus: 2026-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/223871/kaz/27.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223871/rus/27.03.2026
