act_code: '98002'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 23 декабря 2015 года № 10-36 с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 18 января 2016 года № 3564. Утратило силу решением Уалихановского районного маслихата Северо-Казахстанской области от 8 декабря 2016 года № 7-9с
title:
  rus: Об утверждении Положения государственного учреждения «Аппарат Уалихановского районного маслихата»
  kaz: Уәлиханов аудандық мәслихаттың аппараты»мемлекеттік мекемесінің Ережесін бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2015-12-23
approved_by:
- '165013000002'
version_date:
  kaz: 2015-12-23
  rus: 2015-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/98002/kaz/23.12.2015
  rus: https://zan.gov.kz/client/#!/doc/98002/rus/23.12.2015
