act_code: '72117'
requisite: Решение маслихата Айыртауского района Северо-Казахстанской области от 29 марта 2013 года № 5-12-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 23 апреля 2013 года № 2252. Утратило силу (письмо маслихата Айыртауского района Северо-Казахстанской области от 30 апреля 2015 года № 3.2.3-2/61)
title:
  rus: О предоставлении в 2013 году мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Айыртауского района
  kaz: Айыртау ауданының ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына 2013 жылға әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2013-03-29
approved_by:
- '165003000002'
version_date:
  kaz: 2013-03-29
  rus: 2013-03-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/72117/kaz/29.03.2013
  rus: https://zan.gov.kz/client/#!/doc/72117/rus/29.03.2013
