act_code: '126678'
requisite: Решение акима сельского округа Шагалалы Аккайынского района Северо-Казахстанской области от 5 декабря 2018 года № 16. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 11 декабря 2018 года № 5065. Утратило силу решением акима сельского округа Шагалалы Аккайынского района Северо-Казахстанской области от 15 августа 2019 года № 7 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ветеринарного режима с введением ограничительных мероприятий
  kaz: Шектеу іс-шараларын енгізуге байланысты ветеринариялық режимін белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-05
approved_by:
- '165005010002'
version_date:
  kaz: 2018-12-05
  rus: 2018-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/126678/kaz/05.12.2018
  rus: https://zan.gov.kz/client/#!/doc/126678/rus/05.12.2018
