act_code: '137089'
requisite: Решение акима Алматинского сельского округа Есильского района Северо-Казахстанской области от 12 декабря 2019 года № 5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 18 декабря 2019 года № 5734
title:
  rus: О снятии ограничительных мероприятий
  kaz: Шектеу іс-шараларын тоқтату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-12
approved_by:
- '165006001002'
version_date:
  kaz: 2019-12-12
  rus: 2019-12-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/137089/kaz/12.12.2019
  rus: https://zan.gov.kz/client/#!/doc/137089/rus/12.12.2019
