act_code: '18925'
requisite: Решение Кызылжарского районного маслихата от 29 января 2004 года № 4/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 марта 2004 года № 1181. Утратило силу - решением маслихата Кызылжарского района Северо-Казахстанской области от 14 декабря 2007 года № 5/5
title:
  rus: О правилах оказания социальной помощи специалистам здравоохранения, образования, социального обеспечения, культуры и спорта, проживающим в сельской местности, на приобретение топлива
  kaz: Селолық аймақта тұратын денсаулық сақтау, бiлiм, әлеуметтiк қорғау, мәдениет және спорт бөлiмдерiнiң мамандарына отын сатып алуға әлеуметтiк көмек көрсету бойынша ережелер туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2004-01-29
approved_by:
- '165008000002'
version_date:
  kaz: 2004-01-29
  rus: 2004-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/18925/kaz/29.01.2004
  rus: https://zan.gov.kz/client/#!/doc/18925/rus/29.01.2004
