act_code: '192613'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 28 декабря 2023 года № 12-13 с
title:
  rus: Об утверждении бюджета Тельжанского сельского округа Уалихановского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Уәлиханов ауданы Телжан ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '165013000002'
version_date:
  kaz: 2024-08-15
  rus: 2024-08-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/192613/kaz/15.08.2024
  rus: https://zan.gov.kz/client/#!/doc/192613/rus/15.08.2024
caused_by:
  code: '200247'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 15 августа 2024 года № 7-21 с
  title:
    rus: О внесении изменений в решение Уалихановского районного маслихата от 28 декабря 2023 года № 12-13 с «Об утверждении бюджета Тельжанского сельского округа Уалихановского района на 2024-2026 годы»
    kaz: Уәлиханов аудандық мәслихатының 2023 жылғы 28 желтоқсандағы № 12-13 с «2024-2026 жылдарға арналған Уәлиханов ауданы Телжан ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/200247/rus
