act_code: '110457'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 27 февраля 2017 года № 10-3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 марта 2017 года № 4097
title:
  rus: О предоставлении в 2017 году мер социальной поддержки специалистам в области здравоохранения, образования, социального обеспечения, культуры, спорта и агропромышленного комплекса, прибывшим для работы и проживания в сельские населенные пункты района Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданының ауылдық елді мекендеріне жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және агроөнеркәсіптік кешен саласындағы мамандарға 2017 жылы әлеуметтік қолдау шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2017-02-27
approved_by:
- '165015000002'
version_date:
  kaz: 2017-02-27
  rus: 2017-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/110457/kaz/27.02.2017
  rus: https://zan.gov.kz/client/#!/doc/110457/rus/27.02.2017
