act_code: '186818'
requisite: Решение маслихата Уалихановского района Северо-Казахстанской области от 28 сентября 2023 года № 4-8 с
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей жителей сел, улиц, многоквартирных жилых домов для участия в сходе местного сообщества на территории Уалихановского района
  kaz: Уәлиханов ауданының аумағында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауылдар, көшелер, көппәтерлі тұрғын үйлер тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-09-28
approved_by:
- '165013000002'
version_date:
  kaz: 2025-05-21
  rus: 2025-05-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/186818/kaz/21.05.2025
  rus: https://zan.gov.kz/client/#!/doc/186818/rus/21.05.2025
caused_by:
  code: '210766'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 21 мая 2025 года № 16-31 с
  title:
    rus: О внесении изменений в решение Уалихановского районного маслихата от 28 сентября 2023 года № 4-8 с «Об утверждении Правил проведения раздельных сходов местного сообщества и определения количества представителей жителей сел, улиц, многоквартирных жилых домов для участия в сходе местного сообщества на территории Уалихановского района»
    kaz: Уәлиханов аудандық мәслихатының 2023 жылғы 28 қыркүйектегі № 4-8 с «Уәлиханов ауданының аумағында бөлек жергілікті қоғамдастық жиындарын өткізу және жергілікті қоғамдастық жиынына қатысу үшін ауылдар, көшелер, көппәтерлі тұрғын үйлер тұрғындары өкілдерінің санын айқындау қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210766/rus
