act_code: '55924'
requisite: Решение акима Дубровинского сельского округа Мамлютского района Северо-Казахстанской области от 25 ноября 2010 года № 01-12/11. Зарегистрировано Управлением юстиции Мамлютского района Северо-Казахстанской области 13 декабря 2010 года № 13-10-125
title:
  rus: О присвоении наименований составных частей населенных пунктов Дубровинского сельского округа Мамлютского района
  kaz: Мамлют ауданы Дубровин ауылдық округінің елді мекендерінің құрамдас бөліктеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-11-25
approved_by:
- '165009004001'
version_date:
  kaz: 2018-06-19
  rus: 2018-06-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/55924/kaz/19.06.2018
  rus: https://zan.gov.kz/client/#!/doc/55924/rus/19.06.2018
caused_by:
  code: '123150'
  requisite: Решение акима Дубровинского сельского округа Мамлютского района Северо-Казахстанской области от 19 июня 2018 года № 6. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 июля 2018 года № 4797
  title:
    rus: О внесении изменений в решение акима Дубровинского сельского округа Мамлютского района Северо-Казахстанской области от 25 ноября 2010 года № 01-12/11 «О присвоении наименований составных частей населенных пунктов Дубровинского сельского округа Мамлютского района»
    kaz: «Мамлют ауданы Дубровное селолық округінің елді мекендерінің құрамдас бөліктеріне атау беру туралы» Солтүстік Қазақстан облысы Мамлют ауданы Дубровное ауылдық округі әкімінің 2010 жылғы 25 қарашадағы № 01-12/11 шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/123150/rus
