act_code: '210626'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 19 мая 2025 года № 23/33
title:
  rus: Об утверждении бюджета Кызылжарского сельского округа Кызылжарского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қызылжар ауданының Қызылжар ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-05-19
approved_by:
- '165008000002'
version_date:
  kaz: 2025-05-19
  rus: 2025-05-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/210626/kaz/19.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210626/rus/19.05.2025
