act_code: '128164'
requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 27 декабря 2018 года № 38-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 4 января 2019 года № 5141
title:
  rus: Об утверждении бюджета района имени Габита Мусрепова на 2019-2021 годы
  kaz: 2019-2021 жылдарға арналған Ғабит Мүсірепов атындағы ауданының бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-27
approved_by:
- '165014000002'
version_date:
  kaz: 2019-05-13
  rus: 2019-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/128164/kaz/13.05.2019
  rus: https://zan.gov.kz/client/#!/doc/128164/rus/13.05.2019
caused_by:
  code: '131390'
  requisite: Решение маслихата района имени Габита Мусрепова Северо-Казахстанской области от 13 мая 2019 года № 47-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 мая 2019 года № 5406
  title:
    rus: О внесении изменений и дополнений в решение маслихата района имени Габита Мусрепова от 27 декабря 2018 года № 38-1 «Об утверждении бюджета района имени Габита Мусрепова на 2019-2021 годы»
    kaz: Ғабит Мүсірепов атындағы ауданы мәслихатының 2018 жылғы 27 желтоқсандағы № 38-1 «2019-2021 жылдарға арналған Ғабит Мүсірепов атындағы ауданының бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/131390/rus
