act_code: '65803'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 28 мая 2012 года № 4/2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 1 июня 2012 года № 13-7-176. Утратило силу (письмо маслихата Жамбылского района Северо-Казахстанской области от 3 апреля 2013 года № 03-31/43)
title:
  rus: О предоставлении в 2012 году мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты Жамбылского района
  kaz: Жамбыл ауданының ауылдық елді мекендерге жұмыс істеу және тұру үшін келген денсаулық сақтау, білім беру, әлеуметтік қамсыздандыру, мәдениет, спорт және ветеринария мамандарына 2012 жылға әлеуметтік шараларын ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-05-28
approved_by:
- '165007000002'
version_date:
  kaz: 2012-05-28
  rus: 2012-05-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/65803/kaz/28.05.2012
  rus: https://zan.gov.kz/client/#!/doc/65803/rus/28.05.2012
