act_code: '139755'
requisite: Решение акима Петерфельдского сельского округа Кызылжарского района Северо-Казахстанской области от 20 февраля 2020 года № 10. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 24 февраля 2020 года № 6025
title:
  rus: О присвоении наименований безымянным улицам села Затон Петерфельдского сельского округа Кызылжарского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Қызылжар ауданы Петерфельд ауылдық округінің Затон ауылындағы атауы жоқ көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-02-20
approved_by:
- '165008014002'
version_date:
  kaz: 2020-02-20
  rus: 2020-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/139755/kaz/20.02.2020
  rus: https://zan.gov.kz/client/#!/doc/139755/rus/20.02.2020
