act_code: '97633'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 23 декабря 2015 года № 44/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 января 2016 года № 3544
title:
  rus: О районном бюджете на 2016-2018 годы
  kaz: 2016-2018 жылдарға арналған аудан бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-12-23
approved_by:
- '165010000002'
version_date:
  kaz: 2016-04-26
  rus: 2016-04-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/97633/kaz/26.04.2016
  rus: https://zan.gov.kz/client/#!/doc/97633/rus/26.04.2016
caused_by:
  code: '102209'
  requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 26 апреля 2016 года № 3/2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 мая 2016 № 3738
  title:
    rus: О внесении изменений и дополнений в решение маслихата района Шал акына от 23 декабря 2015 года № 44/1 «О районном бюджете на 2016-2018 годы»
    kaz: «2016-2018 жылдарға арналған аудан бюджеті туралы» Шал ақын ауданы мәслихатының 2015 жылғы 23 желтоқсандағы № 44/1 шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/102209/rus
