act_code: '152278'
requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 8 января 2021 года № 46-14. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 января 2021 года № 7074
title:
  rus: Об утверждении бюджета Полудинского сельского округа района Магжана Жумабаева на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Мағжан Жұмабаев ауданы Полудин ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-01-08
approved_by:
- '165015000002'
version_date:
  kaz: 2021-08-26
  rus: 2021-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/152278/kaz/26.08.2021
  rus: https://zan.gov.kz/client/#!/doc/152278/rus/26.08.2021
caused_by:
  code: '158448'
  requisite: Решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 26 августа 2021 года № 8-14
  title:
    rus: О внесении изменений и дополнения в решение маслихата района Магжана Жумабаева Северо-Казахстанской области от 8 января 2021 года № 46-14 «Об утверждении бюджета Полудинского сельского округа района Магжана Жумабаева на 2021-2023 годы»
    kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы мәслихатының 2021 жылғы 8 қаңтардағы № 46-14 «2021-2023 жылдарға арналған Мағжан Жұмабаев ауданы Полудин ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/158448/rus
