act_code: '52129'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 31 марта 2010 года № 23-2. Зарегистрировано Управлением юстиции Акжарского района Северо-Казахстанской области 27 апреля 2010 года № 13-4-99
title:
  rus: Об оказании социальной помощи отдельным категориям граждан Акжарского района на 2010 год
  kaz: 2010 жылдағы Ақжар ауданының жеке санаттағы азаматтарға әлеуметтік көмек көрсету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2010-03-31
approved_by:
- '165004000002'
version_date:
  kaz: 2010-03-31
  rus: 2010-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/52129/kaz/31.03.2010
  rus: https://zan.gov.kz/client/#!/doc/52129/rus/31.03.2010
