act_code: '151038'
requisite: Решение Кызылжарского районного маслихата Северо-Казахстанской области от 25 декабря 2020 года № 60/1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 31 декабря 2020 года № 6881
title:
  rus: Об утверждении Кызылжарского районного бюджета на 2021-2023 годы
  kaz: 2021-2023 жылдарға арналған Қызылжар аудандық бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2020-12-25
approved_by:
- '165008000002'
version_date:
  kaz: 2021-10-01
  rus: 2021-10-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/151038/kaz/01.10.2021
  rus: https://zan.gov.kz/client/#!/doc/151038/rus/01.10.2021
caused_by:
  code: '159361'
  requisite: Решение маслихата Кызылжарского района Северо-Казахстанской области от 1 октября 2021 года № 8/5. Зарегистрировано в Министерстве юстиции Республики Казахстан 12 октября 2021 года № 24720
  title:
    rus: О внесении изменений в решение Кызылжарского районного маслихата Северо-Казахстанской области от 25 декабря 2020 года № 60/1 «Об утверждении Кызылжарского районного бюджета на 2021-2023 годы»
    kaz: Солтүстік Қазақстан облысы Қызылжар аудандық мәслихатының 2020 жылғы 25 желтоқсандағы № 60/1 «2021-2023 жылдарға арналған Қызылжар аудандық бюджетін бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/159361/rus
