act_code: '77733'
requisite: Решение маслихата Айыртауского района Северо-Казахстанской области от 29 января 2014 года № 5-22-2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 февраля 2014 года № 2571. Утратило силу решением Айыртауского районного маслихата Северо-Казахстанской области от 10 октября 2016 года № 6-5-7
title:
  rus: Об утверждении регламента Айыртауского районного маслихата
  kaz: Айыртау аудандық мәслихатының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕГЛ
- РЕШ
approved_on: 2014-01-29
approved_by:
- '165003000002'
version_date:
  kaz: 2014-01-29
  rus: 2014-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/77733/kaz/29.01.2014
  rus: https://zan.gov.kz/client/#!/doc/77733/rus/29.01.2014
