act_code: '154872'
requisite: Решение акима Полудинского сельского округа района Магжана Жумабаева Северо-Казахстанской области от 19 апреля 2021 года № 8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 19 апреля 2021 года № 7302
title:
  rus: О присвоении наименований безымянным улицам станции Ганькино Полудинского сельского округа района Магжана Жумабаева Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Мағжан Жұмабаев ауданы Полудин ауылдық округінің Ганькин станциясындағы атауы жоқ көшелеріне атаулар беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-04-19
approved_by:
- '165015018002'
version_date:
  kaz: 2021-04-19
  rus: 2021-04-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/154872/kaz/19.04.2021
  rus: https://zan.gov.kz/client/#!/doc/154872/rus/19.04.2021
