act_code: '180229'
requisite: Решение Петропавловского городского маслихата Северо-Казахстанской области от 18 апреля 2023 года № 2. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 25 апреля 2023 года № 7481-15
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по городу Петропавловск
  kaz: Петропавл қаласы бойынша халық үшін тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-04-18
approved_by:
- '165002000002'
version_date:
  kaz: 2023-04-18
  rus: 2023-04-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/180229/kaz/18.04.2023
  rus: https://zan.gov.kz/client/#!/doc/180229/rus/18.04.2023
