act_code: '44954'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 29 января 2009 года № 100. Зарегистрировано Управлением юстиции Тайыншинского района Северо-Казахстанской области 10 марта 2009 года № 13-11-140. Утратило силу решением маслихата Тайыншинского района Северо-Казахстанской области от 15 мая 2013 года № 104
title:
  rus: О повышении ставок земельного налога по Тайыншинскому району
  kaz: Тайынша ауданы бойынша жер салық ставкаларын жоғарылату туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2009-01-29
approved_by:
- '165011000002'
version_date:
  kaz: 2009-01-29
  rus: 2009-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/44954/kaz/29.01.2009
  rus: https://zan.gov.kz/client/#!/doc/44954/rus/29.01.2009
