act_code: '166157'
requisite: Решение акима Карасуского сельского округа Уалихановского района Северо-Казахстанской области от 30 марта 2022 года № 13. Зарегистрирован в Министерстве юстиции Республики Казахстан 6 апреля 2022 года № 27458. Утратило силу решением акима Карасуского сельского округа Уалихановского района Северо-Казахстанской области от 9 июня 2022 года № 16 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-03-30
approved_by:
- '165013006002'
version_date:
  kaz: 2022-03-30
  rus: 2022-03-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/166157/kaz/30.03.2022
  rus: https://zan.gov.kz/client/#!/doc/166157/rus/30.03.2022
