act_code: '95792'
requisite: Решение Северо-Казахстанского областного маслихата от 6 ноября 2015 года № 39/4. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 26 ноября 2015 года № 3476. Утратило силу решением Северо-Казахстанского областного маслихата от 28 мая 2020 года № 43/8 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении границ охранных зон, зон регулирования застройки объектов историко-культурного наследия города Петропавловска Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Петропавл қаласының тарихи-мәдени мұра объектілері құрылысын салуды реттеу аймақтарының, қорғау аймақтарының шекараларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-06
approved_by:
- '165000000002'
version_date:
  kaz: 2015-11-06
  rus: 2015-11-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/95792/kaz/06.11.2015
  rus: https://zan.gov.kz/client/#!/doc/95792/rus/06.11.2015
