act_code: '163368'
requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 29 декабря 2021 года № 11/9
title:
  rus: Об утверждении бюджета Озерного сельского округа Жамбылского района Северо-Казахстанской области на 2022-2024 годы
  kaz: 2022-2024 жылдарға арналған Солтүстік Қазақстан облысы Жамбыл ауданы Озерный ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2021-12-29
approved_by:
- '165007000002'
version_date:
  kaz: 2022-11-25
  rus: 2022-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/163368/kaz/25.11.2022
  rus: https://zan.gov.kz/client/#!/doc/163368/rus/25.11.2022
caused_by:
  code: '174875'
  requisite: Решение маслихата Жамбылского района Северо-Казахстанской области от 25 ноября 2022 года № 21/9
  title:
    rus: О внесении изменений и дополнений в решение маслихата Жамбылского района от 29 декабря 2021 года № 11/9 «Об утверждении бюджета Озерного сельского округа Жамбылского района Северо-Казахстанской области на 2022-2024 годы»
    kaz: Солтүстік Қазақстан облысы Жамбыл ауданы мәслихатының 2021 жылғы 29 желтоқсандағы № 11/9 «2022-2024 жылдарға арналған Солтүстік Қазақстан облысы Жамбыл ауданы Озерный ауылдық округінің бюджетін бекіту туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/174875/rus
