act_code: '121360'
requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 16 апреля 2018 года № 3-25 с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 28 апреля 2018 года № 4694
title:
  rus: О ставках земельного налога
  kaz: Жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-04-16
approved_by:
- '165013000002'
version_date:
  kaz: 2020-03-27
  rus: 2020-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/121360/kaz/27.03.2020
  rus: https://zan.gov.kz/client/#!/doc/121360/rus/27.03.2020
caused_by:
  code: '140772'
  requisite: Решение Уалихановского районного маслихата Северо-Казахстанской области от 27 марта 2020 года № 6-52 с. Зарегистрировано Департаментом юстиции Северо-Казахстанской области от 30 марта 2020 года № 6128
  title:
    rus: О внесении изменений в решение Уалихановского районого маслихата от 16 апреля 2018 года № 3-25с «О ставках на земельный налог»
    kaz: Уәлиханов аудандық мәслихатының 2018 жылғы 16 сәуірдегі № 3-25с «Жер салығының мөлшерлемелері туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/140772/rus
