act_code: '85726'
requisite: Решение маслихата Акжарского района Северо-Казахстанской области от 25 декабря 2014 года № 32-1. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 9 января 2015 года № 3050
title:
  rus: О бюджете Акжарского района Северо-Казахстанской области на 2015-2017 годы
  kaz: 2015-2017 жылдарға арналған Солтүстік Қазақстан облысы Ақжар аудандық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2014-12-25
approved_by:
- '165004000002'
version_date:
  kaz: 2014-12-25
  rus: 2014-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/85726/kaz/25.12.2014
  rus: https://zan.gov.kz/client/#!/doc/85726/rus/25.12.2014
