act_code: '6712'
requisite: Решение акима Северо-Казахстанской области от 29 декабря 1999 года № 257. Зарегистрировано Управлением юстиции Северо-Казахстанской области 7 апреля 2000 года № 106. Утратило силу решением акима Северо-Казахстанской области от 20 января 2005 года № 4
title:
  rus: О государственном учреждении «Северо-Казахстанский комитет по управлению коммунальной собственностью и приватизации»
  kaz: «Коммуналдық меншікті басқару және жекешелендіру жөніндегі Солтүстік Қазақстан комитеті» мемлекеттік мекемесі туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 1999-12-29
approved_by:
- '165000000003'
version_date:
  kaz: 1999-12-29
  rus: 1999-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/6712/kaz/29.12.1999
  rus: https://zan.gov.kz/client/#!/doc/6712/rus/29.12.1999
