act_code: '187503'
requisite: Решение Северо-Казахстанского областного маслихата от 18 октября 2023 года № 7/9
title:
  rus: Об утверждении Правил регулирования миграционных процессов в Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысындағы көші-қон процестерін реттеу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-18
approved_by:
- '165000000002'
version_date:
  kaz: 2023-10-18
  rus: 2023-10-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/187503/kaz/18.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187503/rus/18.10.2023
