act_code: '95922'
requisite: Решение маслихата Тайыншинского района Северо-Казахстанской области от 4 ноября 2015 года № 324. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 30 ноября 2015 года № 3482. Утратило силу решшением маслихата Тайыншинского района Северо-Казахстанской области от 14 апреля 2022 года № 162 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка возмещения затрат на обучение на дому детей с ограниченными возможностями из числа инвалидов по индивидуальному учебному плану
  kaz: Мүгедектер қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу мөлшерін және тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2015-11-04
approved_by:
- '165011000002'
version_date:
  kaz: 2015-11-04
  rus: 2015-11-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/95922/kaz/04.11.2015
  rus: https://zan.gov.kz/client/#!/doc/95922/rus/04.11.2015
