act_code: '138023'
requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 30 декабря 2019 года № 6-38-25. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 8 января 2020 года № 5791
title:
  rus: Об утверждении бюджета Сырымбетского сельского округа Айыртауского района на 2020-2022 годы
  kaz: 2020-2022 жылдарға арналған Айыртау ауданы Сырымбет ауылдық округінің бюджетін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2019-12-30
approved_by:
- '165003000002'
version_date:
  kaz: 2020-04-15
  rus: 2020-04-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/138023/kaz/15.04.2020
  rus: https://zan.gov.kz/client/#!/doc/138023/rus/15.04.2020
caused_by:
  code: '141724'
  requisite: Решение Айыртауского районного маслихата Северо-Казахстанской области от 15 апреля 2020 года № 6-41-8. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 15 апреля 2020 года № 6200
  title:
    rus: О внесении изменений и дополнения в решение Айыртауского районного маслихата от 30 декабря 2019 года № 6-38-25 «Об утверждении бюджета Сырымбетского сельского округа Айыртауского района на 2020-2022 годы»
    kaz: «2020-2022 жылдарға арналған Айыртау ауданы Сырымбет ауылдық округінің бюджетін бекіту туралы» Айыртау аудандық мәслихатының 2019 жылғы 30 желтоқсандағы № 6-38-25 шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/141724/rus
