act_code: '195446'
requisite: Решение акима Есильского района Северо-Казахстанской области от 9 апреля 2024 года № 3. Утратил силу решением и.о. акима Есильского района Северо-Казахстанской области от 13 июня 2024 года № 06 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении на территории Есильского района Северо-Казахстанской области чрезвычайной ситуации природного характера местного масштаба
  kaz: Солтүстік Қазақстан облысы Есіл ауданының аумағында жергілікті ауқымдағы табиғи сипаттағы төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-09
approved_by:
- '165006000003'
version_date:
  kaz: 2024-04-09
  rus: 2024-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/195446/kaz/09.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195446/rus/09.04.2024
