act_code: '67397'
requisite: Решение маслихата района Шал акына Северо-Казахстанской области от 1 августа 2012 года № 5/5. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 23 августа 2012 года № 13-14-156. Утратило силу - решением маслихата района Шал акына Северо-Казахстанской области от 20 декабря 2012 года № 11/10
title:
  rus: О предоставлении мер социальной поддержки специалистам здравоохранения, образования, социального обеспечения, культуры, спорта и ветеринарии, прибывшим для работы и проживания в сельские населенные пункты района Шал акына в 2012 году
  kaz: 2012 жылы Шал ақын ауданының селолық елді мекендеріне жұмыс істеуге және тұруға келген денсаулық сақтау, білім беру, әлеуметтік қамтамасыз ету, мәдениет, спорт және ветеринария мамандарына әлеуметтік қолдау ұсыну туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2012-08-01
approved_by:
- '165010000002'
version_date:
  kaz: 2012-08-01
  rus: 2012-08-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/67397/kaz/01.08.2012
  rus: https://zan.gov.kz/client/#!/doc/67397/rus/01.08.2012
