act_code: '61466'
requisite: Солтүстік Қазақстан облысы Уәлиханов ауданы әкімінің 2011 жылғы 18 қарашадағы № 31 шешімі. Солтүстік Қазақстан облысының Әділет департаментінде 2011 жылғы 21 қарашада № 13-13-147 тіркелді. Қолдану мерзімінің өтуіне байланысты күшін жойды (Солтүстік Қазақстан облысы Уәлиханов ауданы әкімі аппаратының 2012 жылғы 29 желтоқсандағы № 02.12-06-09/362 хаты)
title:
  rus: Солтүстік Қазақстан облысы Уәлиханов ауданы бойынша сайлау учаскелерін құру туралы
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы бойынша сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2011-11-18
approved_by:
- '165013000003'
version_date:
  kaz: 2011-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/61466/kaz/18.11.2011
