act_code: '127988'
requisite: Решение акима Уалихановского района Северо-Казахстанской области от 29 декабря 2018 года № 10. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 29 декабря 2018 года № 5122. Утратило силу решением акима Уалихановского района Северо-Казахстанской области от 10 декабря 2020 года № 25 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об образовании избирательных участков на территории Уалихановского района Северо-Казахстанской области
  kaz: Солтүстік Қазақстан облысы Уәлиханов ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2018-12-29
approved_by:
- '165013000003'
version_date:
  kaz: 2019-03-11
  rus: 2019-03-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/127988/kaz/11.03.2019
  rus: https://zan.gov.kz/client/#!/doc/127988/rus/11.03.2019
caused_by:
  code: '129765'
  requisite: Решение акима Уалихановского района Северо-Казахстанской области от 11 марта 2019 года № 3. Зарегистрировано Департаментом юстиции Северо-Казахстанской области 13 марта 2019 года № 5253. Утратило силу решением акима Уалихановского района Северо-Казахстанской области от 10 декабря 2020 года № 25 (вводится в действие со дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение акима Уалихановского района Северо-Казахстанской области от 29 декабря 2018 года №10 «Об образовании избирательных участков на территории Уалихановского района Северо-Казахстанской области»
    kaz: Солтүстік Қазақстан облысы Уәлиханов ауданы әкімінің 2018 жылғы 29 желтоқсандағы №10 «Солтүстік Қазақстан облысы Уәлиханов ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/129765/rus
