act_code: '175428'
requisite: Решение акима Мирного сельского округа Жамбылского района Северо-Казахстанской области от 8 декабря 2022 года № 25. Зарегистрировано в Министерстве юстиции Республики Казахстан 14 декабря 2022 года № 31112
title:
  rus: О присвоении наименования улице
  kaz: Көшеге атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-08
approved_by:
- '165007010002'
version_date:
  kaz: 2022-12-08
  rus: 2022-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/175428/kaz/08.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175428/rus/08.12.2022
