act_code: '46814'
requisite: Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2009 жылғы 22 маусымдағы № 8-14с шешімі. Солтүстік Қазақстан облысы Уәлиханов ауданының Әділет басқармасында 2009 жылғы 10 шілдеде № 13-13-106 тіркелді. Күші жойылды - Солтүстік Қазақстан облысы Уәлиханов аудандық мәслихатының 2012 жылғы 14 маусымдағы № 14-4с шешімімен
title:
  rus: Уәлиханов ауданы аумағында иттер мен мысықтарды күтіп ұстау Ережелері туралы
  kaz: Уәлиханов ауданы аумағында иттер мен мысықтарды күтіп ұстау Ережелері туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2009-06-22
approved_by:
- '165013000002'
version_date:
  kaz: 2009-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/46814/kaz/22.06.2009
